package com.timebank.domain;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class ActpartExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table dbo.ACTPART
     *
     * @mbg.generated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table dbo.ACTPART
     *
     * @mbg.generated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table dbo.ACTPART
     *
     * @mbg.generated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dbo.ACTPART
     *
     * @mbg.generated
     */
    public ActpartExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dbo.ACTPART
     *
     * @mbg.generated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dbo.ACTPART
     *
     * @mbg.generated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dbo.ACTPART
     *
     * @mbg.generated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dbo.ACTPART
     *
     * @mbg.generated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dbo.ACTPART
     *
     * @mbg.generated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dbo.ACTPART
     *
     * @mbg.generated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dbo.ACTPART
     *
     * @mbg.generated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dbo.ACTPART
     *
     * @mbg.generated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dbo.ACTPART
     *
     * @mbg.generated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dbo.ACTPART
     *
     * @mbg.generated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table dbo.ACTPART
     *
     * @mbg.generated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andActpartGuidIsNull() {
            addCriterion("ACTPART_GUID is null");
            return (Criteria) this;
        }

        public Criteria andActpartGuidIsNotNull() {
            addCriterion("ACTPART_GUID is not null");
            return (Criteria) this;
        }

        public Criteria andActpartGuidEqualTo(String value) {
            addCriterion("ACTPART_GUID =", value, "actpartGuid");
            return (Criteria) this;
        }

        public Criteria andActpartGuidNotEqualTo(String value) {
            addCriterion("ACTPART_GUID <>", value, "actpartGuid");
            return (Criteria) this;
        }

        public Criteria andActpartGuidGreaterThan(String value) {
            addCriterion("ACTPART_GUID >", value, "actpartGuid");
            return (Criteria) this;
        }

        public Criteria andActpartGuidGreaterThanOrEqualTo(String value) {
            addCriterion("ACTPART_GUID >=", value, "actpartGuid");
            return (Criteria) this;
        }

        public Criteria andActpartGuidLessThan(String value) {
            addCriterion("ACTPART_GUID <", value, "actpartGuid");
            return (Criteria) this;
        }

        public Criteria andActpartGuidLessThanOrEqualTo(String value) {
            addCriterion("ACTPART_GUID <=", value, "actpartGuid");
            return (Criteria) this;
        }

        public Criteria andActpartGuidLike(String value) {
            addCriterion("ACTPART_GUID like", value, "actpartGuid");
            return (Criteria) this;
        }

        public Criteria andActpartGuidNotLike(String value) {
            addCriterion("ACTPART_GUID not like", value, "actpartGuid");
            return (Criteria) this;
        }

        public Criteria andActpartGuidIn(List<String> values) {
            addCriterion("ACTPART_GUID in", values, "actpartGuid");
            return (Criteria) this;
        }

        public Criteria andActpartGuidNotIn(List<String> values) {
            addCriterion("ACTPART_GUID not in", values, "actpartGuid");
            return (Criteria) this;
        }

        public Criteria andActpartGuidBetween(String value1, String value2) {
            addCriterion("ACTPART_GUID between", value1, value2, "actpartGuid");
            return (Criteria) this;
        }

        public Criteria andActpartGuidNotBetween(String value1, String value2) {
            addCriterion("ACTPART_GUID not between", value1, value2, "actpartGuid");
            return (Criteria) this;
        }

        public Criteria andActpartActivityGuidIsNull() {
            addCriterion("ACTPART_ACTIVITY_GUID is null");
            return (Criteria) this;
        }

        public Criteria andActpartActivityGuidIsNotNull() {
            addCriterion("ACTPART_ACTIVITY_GUID is not null");
            return (Criteria) this;
        }

        public Criteria andActpartActivityGuidEqualTo(String value) {
            addCriterion("ACTPART_ACTIVITY_GUID =", value, "actpartActivityGuid");
            return (Criteria) this;
        }

        public Criteria andActpartActivityGuidNotEqualTo(String value) {
            addCriterion("ACTPART_ACTIVITY_GUID <>", value, "actpartActivityGuid");
            return (Criteria) this;
        }

        public Criteria andActpartActivityGuidGreaterThan(String value) {
            addCriterion("ACTPART_ACTIVITY_GUID >", value, "actpartActivityGuid");
            return (Criteria) this;
        }

        public Criteria andActpartActivityGuidGreaterThanOrEqualTo(String value) {
            addCriterion("ACTPART_ACTIVITY_GUID >=", value, "actpartActivityGuid");
            return (Criteria) this;
        }

        public Criteria andActpartActivityGuidLessThan(String value) {
            addCriterion("ACTPART_ACTIVITY_GUID <", value, "actpartActivityGuid");
            return (Criteria) this;
        }

        public Criteria andActpartActivityGuidLessThanOrEqualTo(String value) {
            addCriterion("ACTPART_ACTIVITY_GUID <=", value, "actpartActivityGuid");
            return (Criteria) this;
        }

        public Criteria andActpartActivityGuidLike(String value) {
            addCriterion("ACTPART_ACTIVITY_GUID like", value, "actpartActivityGuid");
            return (Criteria) this;
        }

        public Criteria andActpartActivityGuidNotLike(String value) {
            addCriterion("ACTPART_ACTIVITY_GUID not like", value, "actpartActivityGuid");
            return (Criteria) this;
        }

        public Criteria andActpartActivityGuidIn(List<String> values) {
            addCriterion("ACTPART_ACTIVITY_GUID in", values, "actpartActivityGuid");
            return (Criteria) this;
        }

        public Criteria andActpartActivityGuidNotIn(List<String> values) {
            addCriterion("ACTPART_ACTIVITY_GUID not in", values, "actpartActivityGuid");
            return (Criteria) this;
        }

        public Criteria andActpartActivityGuidBetween(String value1, String value2) {
            addCriterion("ACTPART_ACTIVITY_GUID between", value1, value2, "actpartActivityGuid");
            return (Criteria) this;
        }

        public Criteria andActpartActivityGuidNotBetween(String value1, String value2) {
            addCriterion("ACTPART_ACTIVITY_GUID not between", value1, value2, "actpartActivityGuid");
            return (Criteria) this;
        }

        public Criteria andActpartUserGuidIsNull() {
            addCriterion("ACTPART_USER_GUID is null");
            return (Criteria) this;
        }

        public Criteria andActpartUserGuidIsNotNull() {
            addCriterion("ACTPART_USER_GUID is not null");
            return (Criteria) this;
        }

        public Criteria andActpartUserGuidEqualTo(String value) {
            addCriterion("ACTPART_USER_GUID =", value, "actpartUserGuid");
            return (Criteria) this;
        }

        public Criteria andActpartUserGuidNotEqualTo(String value) {
            addCriterion("ACTPART_USER_GUID <>", value, "actpartUserGuid");
            return (Criteria) this;
        }

        public Criteria andActpartUserGuidGreaterThan(String value) {
            addCriterion("ACTPART_USER_GUID >", value, "actpartUserGuid");
            return (Criteria) this;
        }

        public Criteria andActpartUserGuidGreaterThanOrEqualTo(String value) {
            addCriterion("ACTPART_USER_GUID >=", value, "actpartUserGuid");
            return (Criteria) this;
        }

        public Criteria andActpartUserGuidLessThan(String value) {
            addCriterion("ACTPART_USER_GUID <", value, "actpartUserGuid");
            return (Criteria) this;
        }

        public Criteria andActpartUserGuidLessThanOrEqualTo(String value) {
            addCriterion("ACTPART_USER_GUID <=", value, "actpartUserGuid");
            return (Criteria) this;
        }

        public Criteria andActpartUserGuidLike(String value) {
            addCriterion("ACTPART_USER_GUID like", value, "actpartUserGuid");
            return (Criteria) this;
        }

        public Criteria andActpartUserGuidNotLike(String value) {
            addCriterion("ACTPART_USER_GUID not like", value, "actpartUserGuid");
            return (Criteria) this;
        }

        public Criteria andActpartUserGuidIn(List<String> values) {
            addCriterion("ACTPART_USER_GUID in", values, "actpartUserGuid");
            return (Criteria) this;
        }

        public Criteria andActpartUserGuidNotIn(List<String> values) {
            addCriterion("ACTPART_USER_GUID not in", values, "actpartUserGuid");
            return (Criteria) this;
        }

        public Criteria andActpartUserGuidBetween(String value1, String value2) {
            addCriterion("ACTPART_USER_GUID between", value1, value2, "actpartUserGuid");
            return (Criteria) this;
        }

        public Criteria andActpartUserGuidNotBetween(String value1, String value2) {
            addCriterion("ACTPART_USER_GUID not between", value1, value2, "actpartUserGuid");
            return (Criteria) this;
        }

        public Criteria andActpartDespIsNull() {
            addCriterion("ACTPART_DESP is null");
            return (Criteria) this;
        }

        public Criteria andActpartDespIsNotNull() {
            addCriterion("ACTPART_DESP is not null");
            return (Criteria) this;
        }

        public Criteria andActpartDespEqualTo(String value) {
            addCriterion("ACTPART_DESP =", value, "actpartDesp");
            return (Criteria) this;
        }

        public Criteria andActpartDespNotEqualTo(String value) {
            addCriterion("ACTPART_DESP <>", value, "actpartDesp");
            return (Criteria) this;
        }

        public Criteria andActpartDespGreaterThan(String value) {
            addCriterion("ACTPART_DESP >", value, "actpartDesp");
            return (Criteria) this;
        }

        public Criteria andActpartDespGreaterThanOrEqualTo(String value) {
            addCriterion("ACTPART_DESP >=", value, "actpartDesp");
            return (Criteria) this;
        }

        public Criteria andActpartDespLessThan(String value) {
            addCriterion("ACTPART_DESP <", value, "actpartDesp");
            return (Criteria) this;
        }

        public Criteria andActpartDespLessThanOrEqualTo(String value) {
            addCriterion("ACTPART_DESP <=", value, "actpartDesp");
            return (Criteria) this;
        }

        public Criteria andActpartDespLike(String value) {
            addCriterion("ACTPART_DESP like", value, "actpartDesp");
            return (Criteria) this;
        }

        public Criteria andActpartDespNotLike(String value) {
            addCriterion("ACTPART_DESP not like", value, "actpartDesp");
            return (Criteria) this;
        }

        public Criteria andActpartDespIn(List<String> values) {
            addCriterion("ACTPART_DESP in", values, "actpartDesp");
            return (Criteria) this;
        }

        public Criteria andActpartDespNotIn(List<String> values) {
            addCriterion("ACTPART_DESP not in", values, "actpartDesp");
            return (Criteria) this;
        }

        public Criteria andActpartDespBetween(String value1, String value2) {
            addCriterion("ACTPART_DESP between", value1, value2, "actpartDesp");
            return (Criteria) this;
        }

        public Criteria andActpartDespNotBetween(String value1, String value2) {
            addCriterion("ACTPART_DESP not between", value1, value2, "actpartDesp");
            return (Criteria) this;
        }

        public Criteria andActparStartTimeIsNull() {
            addCriterion("ACTPAR_START_TIME is null");
            return (Criteria) this;
        }

        public Criteria andActparStartTimeIsNotNull() {
            addCriterion("ACTPAR_START_TIME is not null");
            return (Criteria) this;
        }

        public Criteria andActparStartTimeEqualTo(Date value) {
            addCriterion("ACTPAR_START_TIME =", value, "actparStartTime");
            return (Criteria) this;
        }

        public Criteria andActparStartTimeNotEqualTo(Date value) {
            addCriterion("ACTPAR_START_TIME <>", value, "actparStartTime");
            return (Criteria) this;
        }

        public Criteria andActparStartTimeGreaterThan(Date value) {
            addCriterion("ACTPAR_START_TIME >", value, "actparStartTime");
            return (Criteria) this;
        }

        public Criteria andActparStartTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("ACTPAR_START_TIME >=", value, "actparStartTime");
            return (Criteria) this;
        }

        public Criteria andActparStartTimeLessThan(Date value) {
            addCriterion("ACTPAR_START_TIME <", value, "actparStartTime");
            return (Criteria) this;
        }

        public Criteria andActparStartTimeLessThanOrEqualTo(Date value) {
            addCriterion("ACTPAR_START_TIME <=", value, "actparStartTime");
            return (Criteria) this;
        }

        public Criteria andActparStartTimeIn(List<Date> values) {
            addCriterion("ACTPAR_START_TIME in", values, "actparStartTime");
            return (Criteria) this;
        }

        public Criteria andActparStartTimeNotIn(List<Date> values) {
            addCriterion("ACTPAR_START_TIME not in", values, "actparStartTime");
            return (Criteria) this;
        }

        public Criteria andActparStartTimeBetween(Date value1, Date value2) {
            addCriterion("ACTPAR_START_TIME between", value1, value2, "actparStartTime");
            return (Criteria) this;
        }

        public Criteria andActparStartTimeNotBetween(Date value1, Date value2) {
            addCriterion("ACTPAR_START_TIME not between", value1, value2, "actparStartTime");
            return (Criteria) this;
        }

        public Criteria andActparEndTimeIsNull() {
            addCriterion("ACTPAR_END_TIME is null");
            return (Criteria) this;
        }

        public Criteria andActparEndTimeIsNotNull() {
            addCriterion("ACTPAR_END_TIME is not null");
            return (Criteria) this;
        }

        public Criteria andActparEndTimeEqualTo(Date value) {
            addCriterion("ACTPAR_END_TIME =", value, "actparEndTime");
            return (Criteria) this;
        }

        public Criteria andActparEndTimeNotEqualTo(Date value) {
            addCriterion("ACTPAR_END_TIME <>", value, "actparEndTime");
            return (Criteria) this;
        }

        public Criteria andActparEndTimeGreaterThan(Date value) {
            addCriterion("ACTPAR_END_TIME >", value, "actparEndTime");
            return (Criteria) this;
        }

        public Criteria andActparEndTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("ACTPAR_END_TIME >=", value, "actparEndTime");
            return (Criteria) this;
        }

        public Criteria andActparEndTimeLessThan(Date value) {
            addCriterion("ACTPAR_END_TIME <", value, "actparEndTime");
            return (Criteria) this;
        }

        public Criteria andActparEndTimeLessThanOrEqualTo(Date value) {
            addCriterion("ACTPAR_END_TIME <=", value, "actparEndTime");
            return (Criteria) this;
        }

        public Criteria andActparEndTimeIn(List<Date> values) {
            addCriterion("ACTPAR_END_TIME in", values, "actparEndTime");
            return (Criteria) this;
        }

        public Criteria andActparEndTimeNotIn(List<Date> values) {
            addCriterion("ACTPAR_END_TIME not in", values, "actparEndTime");
            return (Criteria) this;
        }

        public Criteria andActparEndTimeBetween(Date value1, Date value2) {
            addCriterion("ACTPAR_END_TIME between", value1, value2, "actparEndTime");
            return (Criteria) this;
        }

        public Criteria andActparEndTimeNotBetween(Date value1, Date value2) {
            addCriterion("ACTPAR_END_TIME not between", value1, value2, "actparEndTime");
            return (Criteria) this;
        }

        public Criteria andActpartEvaluateIsNull() {
            addCriterion("ACTPART_EVALUATE is null");
            return (Criteria) this;
        }

        public Criteria andActpartEvaluateIsNotNull() {
            addCriterion("ACTPART_EVALUATE is not null");
            return (Criteria) this;
        }

        public Criteria andActpartEvaluateEqualTo(Integer value) {
            addCriterion("ACTPART_EVALUATE =", value, "actpartEvaluate");
            return (Criteria) this;
        }

        public Criteria andActpartEvaluateNotEqualTo(Integer value) {
            addCriterion("ACTPART_EVALUATE <>", value, "actpartEvaluate");
            return (Criteria) this;
        }

        public Criteria andActpartEvaluateGreaterThan(Integer value) {
            addCriterion("ACTPART_EVALUATE >", value, "actpartEvaluate");
            return (Criteria) this;
        }

        public Criteria andActpartEvaluateGreaterThanOrEqualTo(Integer value) {
            addCriterion("ACTPART_EVALUATE >=", value, "actpartEvaluate");
            return (Criteria) this;
        }

        public Criteria andActpartEvaluateLessThan(Integer value) {
            addCriterion("ACTPART_EVALUATE <", value, "actpartEvaluate");
            return (Criteria) this;
        }

        public Criteria andActpartEvaluateLessThanOrEqualTo(Integer value) {
            addCriterion("ACTPART_EVALUATE <=", value, "actpartEvaluate");
            return (Criteria) this;
        }

        public Criteria andActpartEvaluateIn(List<Integer> values) {
            addCriterion("ACTPART_EVALUATE in", values, "actpartEvaluate");
            return (Criteria) this;
        }

        public Criteria andActpartEvaluateNotIn(List<Integer> values) {
            addCriterion("ACTPART_EVALUATE not in", values, "actpartEvaluate");
            return (Criteria) this;
        }

        public Criteria andActpartEvaluateBetween(Integer value1, Integer value2) {
            addCriterion("ACTPART_EVALUATE between", value1, value2, "actpartEvaluate");
            return (Criteria) this;
        }

        public Criteria andActpartEvaluateNotBetween(Integer value1, Integer value2) {
            addCriterion("ACTPART_EVALUATE not between", value1, value2, "actpartEvaluate");
            return (Criteria) this;
        }

        public Criteria andActpartEarnCurrencyIsNull() {
            addCriterion("ACTPART_EARN_CURRENCY is null");
            return (Criteria) this;
        }

        public Criteria andActpartEarnCurrencyIsNotNull() {
            addCriterion("ACTPART_EARN_CURRENCY is not null");
            return (Criteria) this;
        }

        public Criteria andActpartEarnCurrencyEqualTo(Double value) {
            addCriterion("ACTPART_EARN_CURRENCY =", value, "actpartEarnCurrency");
            return (Criteria) this;
        }

        public Criteria andActpartEarnCurrencyNotEqualTo(Double value) {
            addCriterion("ACTPART_EARN_CURRENCY <>", value, "actpartEarnCurrency");
            return (Criteria) this;
        }

        public Criteria andActpartEarnCurrencyGreaterThan(Double value) {
            addCriterion("ACTPART_EARN_CURRENCY >", value, "actpartEarnCurrency");
            return (Criteria) this;
        }

        public Criteria andActpartEarnCurrencyGreaterThanOrEqualTo(Double value) {
            addCriterion("ACTPART_EARN_CURRENCY >=", value, "actpartEarnCurrency");
            return (Criteria) this;
        }

        public Criteria andActpartEarnCurrencyLessThan(Double value) {
            addCriterion("ACTPART_EARN_CURRENCY <", value, "actpartEarnCurrency");
            return (Criteria) this;
        }

        public Criteria andActpartEarnCurrencyLessThanOrEqualTo(Double value) {
            addCriterion("ACTPART_EARN_CURRENCY <=", value, "actpartEarnCurrency");
            return (Criteria) this;
        }

        public Criteria andActpartEarnCurrencyIn(List<Double> values) {
            addCriterion("ACTPART_EARN_CURRENCY in", values, "actpartEarnCurrency");
            return (Criteria) this;
        }

        public Criteria andActpartEarnCurrencyNotIn(List<Double> values) {
            addCriterion("ACTPART_EARN_CURRENCY not in", values, "actpartEarnCurrency");
            return (Criteria) this;
        }

        public Criteria andActpartEarnCurrencyBetween(Double value1, Double value2) {
            addCriterion("ACTPART_EARN_CURRENCY between", value1, value2, "actpartEarnCurrency");
            return (Criteria) this;
        }

        public Criteria andActpartEarnCurrencyNotBetween(Double value1, Double value2) {
            addCriterion("ACTPART_EARN_CURRENCY not between", value1, value2, "actpartEarnCurrency");
            return (Criteria) this;
        }

        public Criteria andAcpartProcessUserGuidIsNull() {
            addCriterion("ACPART_PROCESS_USER_GUID is null");
            return (Criteria) this;
        }

        public Criteria andAcpartProcessUserGuidIsNotNull() {
            addCriterion("ACPART_PROCESS_USER_GUID is not null");
            return (Criteria) this;
        }

        public Criteria andAcpartProcessUserGuidEqualTo(String value) {
            addCriterion("ACPART_PROCESS_USER_GUID =", value, "acpartProcessUserGuid");
            return (Criteria) this;
        }

        public Criteria andAcpartProcessUserGuidNotEqualTo(String value) {
            addCriterion("ACPART_PROCESS_USER_GUID <>", value, "acpartProcessUserGuid");
            return (Criteria) this;
        }

        public Criteria andAcpartProcessUserGuidGreaterThan(String value) {
            addCriterion("ACPART_PROCESS_USER_GUID >", value, "acpartProcessUserGuid");
            return (Criteria) this;
        }

        public Criteria andAcpartProcessUserGuidGreaterThanOrEqualTo(String value) {
            addCriterion("ACPART_PROCESS_USER_GUID >=", value, "acpartProcessUserGuid");
            return (Criteria) this;
        }

        public Criteria andAcpartProcessUserGuidLessThan(String value) {
            addCriterion("ACPART_PROCESS_USER_GUID <", value, "acpartProcessUserGuid");
            return (Criteria) this;
        }

        public Criteria andAcpartProcessUserGuidLessThanOrEqualTo(String value) {
            addCriterion("ACPART_PROCESS_USER_GUID <=", value, "acpartProcessUserGuid");
            return (Criteria) this;
        }

        public Criteria andAcpartProcessUserGuidLike(String value) {
            addCriterion("ACPART_PROCESS_USER_GUID like", value, "acpartProcessUserGuid");
            return (Criteria) this;
        }

        public Criteria andAcpartProcessUserGuidNotLike(String value) {
            addCriterion("ACPART_PROCESS_USER_GUID not like", value, "acpartProcessUserGuid");
            return (Criteria) this;
        }

        public Criteria andAcpartProcessUserGuidIn(List<String> values) {
            addCriterion("ACPART_PROCESS_USER_GUID in", values, "acpartProcessUserGuid");
            return (Criteria) this;
        }

        public Criteria andAcpartProcessUserGuidNotIn(List<String> values) {
            addCriterion("ACPART_PROCESS_USER_GUID not in", values, "acpartProcessUserGuid");
            return (Criteria) this;
        }

        public Criteria andAcpartProcessUserGuidBetween(String value1, String value2) {
            addCriterion("ACPART_PROCESS_USER_GUID between", value1, value2, "acpartProcessUserGuid");
            return (Criteria) this;
        }

        public Criteria andAcpartProcessUserGuidNotBetween(String value1, String value2) {
            addCriterion("ACPART_PROCESS_USER_GUID not between", value1, value2, "acpartProcessUserGuid");
            return (Criteria) this;
        }

        public Criteria andAcpartTypeGuidProcessStatusIsNull() {
            addCriterion("ACPART_TYPE_GUID_PROCESS_STATUS is null");
            return (Criteria) this;
        }

        public Criteria andAcpartTypeGuidProcessStatusIsNotNull() {
            addCriterion("ACPART_TYPE_GUID_PROCESS_STATUS is not null");
            return (Criteria) this;
        }

        public Criteria andAcpartTypeGuidProcessStatusEqualTo(String value) {
            addCriterion("ACPART_TYPE_GUID_PROCESS_STATUS =", value, "acpartTypeGuidProcessStatus");
            return (Criteria) this;
        }

        public Criteria andAcpartTypeGuidProcessStatusNotEqualTo(String value) {
            addCriterion("ACPART_TYPE_GUID_PROCESS_STATUS <>", value, "acpartTypeGuidProcessStatus");
            return (Criteria) this;
        }

        public Criteria andAcpartTypeGuidProcessStatusGreaterThan(String value) {
            addCriterion("ACPART_TYPE_GUID_PROCESS_STATUS >", value, "acpartTypeGuidProcessStatus");
            return (Criteria) this;
        }

        public Criteria andAcpartTypeGuidProcessStatusGreaterThanOrEqualTo(String value) {
            addCriterion("ACPART_TYPE_GUID_PROCESS_STATUS >=", value, "acpartTypeGuidProcessStatus");
            return (Criteria) this;
        }

        public Criteria andAcpartTypeGuidProcessStatusLessThan(String value) {
            addCriterion("ACPART_TYPE_GUID_PROCESS_STATUS <", value, "acpartTypeGuidProcessStatus");
            return (Criteria) this;
        }

        public Criteria andAcpartTypeGuidProcessStatusLessThanOrEqualTo(String value) {
            addCriterion("ACPART_TYPE_GUID_PROCESS_STATUS <=", value, "acpartTypeGuidProcessStatus");
            return (Criteria) this;
        }

        public Criteria andAcpartTypeGuidProcessStatusLike(String value) {
            addCriterion("ACPART_TYPE_GUID_PROCESS_STATUS like", value, "acpartTypeGuidProcessStatus");
            return (Criteria) this;
        }

        public Criteria andAcpartTypeGuidProcessStatusNotLike(String value) {
            addCriterion("ACPART_TYPE_GUID_PROCESS_STATUS not like", value, "acpartTypeGuidProcessStatus");
            return (Criteria) this;
        }

        public Criteria andAcpartTypeGuidProcessStatusIn(List<String> values) {
            addCriterion("ACPART_TYPE_GUID_PROCESS_STATUS in", values, "acpartTypeGuidProcessStatus");
            return (Criteria) this;
        }

        public Criteria andAcpartTypeGuidProcessStatusNotIn(List<String> values) {
            addCriterion("ACPART_TYPE_GUID_PROCESS_STATUS not in", values, "acpartTypeGuidProcessStatus");
            return (Criteria) this;
        }

        public Criteria andAcpartTypeGuidProcessStatusBetween(String value1, String value2) {
            addCriterion("ACPART_TYPE_GUID_PROCESS_STATUS between", value1, value2, "acpartTypeGuidProcessStatus");
            return (Criteria) this;
        }

        public Criteria andAcpartTypeGuidProcessStatusNotBetween(String value1, String value2) {
            addCriterion("ACPART_TYPE_GUID_PROCESS_STATUS not between", value1, value2, "acpartTypeGuidProcessStatus");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table dbo.ACTPART
     *
     * @mbg.generated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table dbo.ACTPART
     *
     * @mbg.generated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}