package com.timebank.domain;

import org.springframework.format.annotation.DateTimeFormat;

import java.util.Date;

public class Actpart {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.ACTPART.ACTPART_GUID
     *
     * @mbg.generated
     */
    private String actpartGuid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.ACTPART.ACTPART_ACTIVITY_GUID
     *
     * @mbg.generated
     */
    private String actpartActivityGuid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.ACTPART.ACTPART_USER_GUID
     *
     * @mbg.generated
     */
    private String actpartUserGuid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.ACTPART.ACTPART_DESP
     *
     * @mbg.generated
     */
    private String actpartDesp;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.ACTPART.ACTPAR_START_TIME
     *
     * @mbg.generated
     */
    @DateTimeFormat(pattern = "yyyy-MM-dd HH:mm:ss")
    private Date actparStartTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.ACTPART.ACTPAR_END_TIME
     *
     * @mbg.generated
     */
    @DateTimeFormat(pattern = "yyyy-MM-dd HH:mm:ss")
    private Date actparEndTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.ACTPART.ACTPART_EVALUATE
     *
     * @mbg.generated
     */
    private Integer actpartEvaluate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.ACTPART.ACTPART_EARN_CURRENCY
     *
     * @mbg.generated
     */
    private Double actpartEarnCurrency;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.ACTPART.ACPART_PROCESS_USER_GUID
     *
     * @mbg.generated
     */
    private String acpartProcessUserGuid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.ACTPART.ACTPART_GUID
     *
     * @return the value of dbo.ACTPART.ACTPART_GUID
     *
     * @mbg.generated
     */
    public String getActpartGuid() {
        return actpartGuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.ACTPART.ACTPART_GUID
     *
     * @param actpartGuid the value for dbo.ACTPART.ACTPART_GUID
     *
     * @mbg.generated
     */
    public void setActpartGuid(String actpartGuid) {
        this.actpartGuid = actpartGuid == null ? null : actpartGuid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.ACTPART.ACTPART_ACTIVITY_GUID
     *
     * @return the value of dbo.ACTPART.ACTPART_ACTIVITY_GUID
     *
     * @mbg.generated
     */
    public String getActpartActivityGuid() {
        return actpartActivityGuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.ACTPART.ACTPART_ACTIVITY_GUID
     *
     * @param actpartActivityGuid the value for dbo.ACTPART.ACTPART_ACTIVITY_GUID
     *
     * @mbg.generated
     */
    public void setActpartActivityGuid(String actpartActivityGuid) {
        this.actpartActivityGuid = actpartActivityGuid == null ? null : actpartActivityGuid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.ACTPART.ACTPART_USER_GUID
     *
     * @return the value of dbo.ACTPART.ACTPART_USER_GUID
     *
     * @mbg.generated
     */
    public String getActpartUserGuid() {
        return actpartUserGuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.ACTPART.ACTPART_USER_GUID
     *
     * @param actpartUserGuid the value for dbo.ACTPART.ACTPART_USER_GUID
     *
     * @mbg.generated
     */
    public void setActpartUserGuid(String actpartUserGuid) {
        this.actpartUserGuid = actpartUserGuid == null ? null : actpartUserGuid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.ACTPART.ACTPART_DESP
     *
     * @return the value of dbo.ACTPART.ACTPART_DESP
     *
     * @mbg.generated
     */
    public String getActpartDesp() {
        return actpartDesp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.ACTPART.ACTPART_DESP
     *
     * @param actpartDesp the value for dbo.ACTPART.ACTPART_DESP
     *
     * @mbg.generated
     */
    public void setActpartDesp(String actpartDesp) {
        this.actpartDesp = actpartDesp == null ? null : actpartDesp.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.ACTPART.ACTPAR_START_TIME
     *
     * @return the value of dbo.ACTPART.ACTPAR_START_TIME
     *
     * @mbg.generated
     */
    public Date getActparStartTime() {
        return actparStartTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.ACTPART.ACTPAR_START_TIME
     *
     * @param actparStartTime the value for dbo.ACTPART.ACTPAR_START_TIME
     *
     * @mbg.generated
     */
    public void setActparStartTime(Date actparStartTime) {
        this.actparStartTime = actparStartTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.ACTPART.ACTPAR_END_TIME
     *
     * @return the value of dbo.ACTPART.ACTPAR_END_TIME
     *
     * @mbg.generated
     */
    public Date getActparEndTime() {
        return actparEndTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.ACTPART.ACTPAR_END_TIME
     *
     * @param actparEndTime the value for dbo.ACTPART.ACTPAR_END_TIME
     *
     * @mbg.generated
     */
    public void setActparEndTime(Date actparEndTime) {
        this.actparEndTime = actparEndTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.ACTPART.ACTPART_EVALUATE
     *
     * @return the value of dbo.ACTPART.ACTPART_EVALUATE
     *
     * @mbg.generated
     */
    public Integer getActpartEvaluate() {
        return actpartEvaluate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.ACTPART.ACTPART_EVALUATE
     *
     * @param actpartEvaluate the value for dbo.ACTPART.ACTPART_EVALUATE
     *
     * @mbg.generated
     */
    public void setActpartEvaluate(Integer actpartEvaluate) {
        this.actpartEvaluate = actpartEvaluate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.ACTPART.ACTPART_EARN_CURRENCY
     *
     * @return the value of dbo.ACTPART.ACTPART_EARN_CURRENCY
     *
     * @mbg.generated
     */
    public Double getActpartEarnCurrency() {
        return actpartEarnCurrency;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.ACTPART.ACTPART_EARN_CURRENCY
     *
     * @param actpartEarnCurrency the value for dbo.ACTPART.ACTPART_EARN_CURRENCY
     *
     * @mbg.generated
     */
    public void setActpartEarnCurrency(Double actpartEarnCurrency) {
        this.actpartEarnCurrency = actpartEarnCurrency;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.ACTPART.ACPART_PROCESS_USER_GUID
     *
     * @return the value of dbo.ACTPART.ACPART_PROCESS_USER_GUID
     *
     * @mbg.generated
     */
    public String getAcpartProcessUserGuid() {
        return acpartProcessUserGuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.ACTPART.ACPART_PROCESS_USER_GUID
     *
     * @param acpartProcessUserGuid the value for dbo.ACTPART.ACPART_PROCESS_USER_GUID
     *
     * @mbg.generated
     */
    public void setAcpartProcessUserGuid(String acpartProcessUserGuid) {
        this.acpartProcessUserGuid = acpartProcessUserGuid == null ? null : acpartProcessUserGuid.trim();
    }
}