package com.timebank.domain;

import java.util.ArrayList;
import java.util.List;

public class CommunityExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table dbo.COMMUNITY
     *
     * @mbg.generated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table dbo.COMMUNITY
     *
     * @mbg.generated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table dbo.COMMUNITY
     *
     * @mbg.generated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dbo.COMMUNITY
     *
     * @mbg.generated
     */
    public CommunityExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dbo.COMMUNITY
     *
     * @mbg.generated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dbo.COMMUNITY
     *
     * @mbg.generated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dbo.COMMUNITY
     *
     * @mbg.generated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dbo.COMMUNITY
     *
     * @mbg.generated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dbo.COMMUNITY
     *
     * @mbg.generated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dbo.COMMUNITY
     *
     * @mbg.generated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dbo.COMMUNITY
     *
     * @mbg.generated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dbo.COMMUNITY
     *
     * @mbg.generated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dbo.COMMUNITY
     *
     * @mbg.generated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dbo.COMMUNITY
     *
     * @mbg.generated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table dbo.COMMUNITY
     *
     * @mbg.generated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andCommGuidIsNull() {
            addCriterion("COMM_GUID is null");
            return (Criteria) this;
        }

        public Criteria andCommGuidIsNotNull() {
            addCriterion("COMM_GUID is not null");
            return (Criteria) this;
        }

        public Criteria andCommGuidEqualTo(String value) {
            addCriterion("COMM_GUID =", value, "commGuid");
            return (Criteria) this;
        }

        public Criteria andCommGuidNotEqualTo(String value) {
            addCriterion("COMM_GUID <>", value, "commGuid");
            return (Criteria) this;
        }

        public Criteria andCommGuidGreaterThan(String value) {
            addCriterion("COMM_GUID >", value, "commGuid");
            return (Criteria) this;
        }

        public Criteria andCommGuidGreaterThanOrEqualTo(String value) {
            addCriterion("COMM_GUID >=", value, "commGuid");
            return (Criteria) this;
        }

        public Criteria andCommGuidLessThan(String value) {
            addCriterion("COMM_GUID <", value, "commGuid");
            return (Criteria) this;
        }

        public Criteria andCommGuidLessThanOrEqualTo(String value) {
            addCriterion("COMM_GUID <=", value, "commGuid");
            return (Criteria) this;
        }

        public Criteria andCommGuidLike(String value) {
            addCriterion("COMM_GUID like", value, "commGuid");
            return (Criteria) this;
        }

        public Criteria andCommGuidNotLike(String value) {
            addCriterion("COMM_GUID not like", value, "commGuid");
            return (Criteria) this;
        }

        public Criteria andCommGuidIn(List<String> values) {
            addCriterion("COMM_GUID in", values, "commGuid");
            return (Criteria) this;
        }

        public Criteria andCommGuidNotIn(List<String> values) {
            addCriterion("COMM_GUID not in", values, "commGuid");
            return (Criteria) this;
        }

        public Criteria andCommGuidBetween(String value1, String value2) {
            addCriterion("COMM_GUID between", value1, value2, "commGuid");
            return (Criteria) this;
        }

        public Criteria andCommGuidNotBetween(String value1, String value2) {
            addCriterion("COMM_GUID not between", value1, value2, "commGuid");
            return (Criteria) this;
        }

        public Criteria andCommTitleIsNull() {
            addCriterion("COMM_TITLE is null");
            return (Criteria) this;
        }

        public Criteria andCommTitleIsNotNull() {
            addCriterion("COMM_TITLE is not null");
            return (Criteria) this;
        }

        public Criteria andCommTitleEqualTo(String value) {
            addCriterion("COMM_TITLE =", value, "commTitle");
            return (Criteria) this;
        }

        public Criteria andCommTitleNotEqualTo(String value) {
            addCriterion("COMM_TITLE <>", value, "commTitle");
            return (Criteria) this;
        }

        public Criteria andCommTitleGreaterThan(String value) {
            addCriterion("COMM_TITLE >", value, "commTitle");
            return (Criteria) this;
        }

        public Criteria andCommTitleGreaterThanOrEqualTo(String value) {
            addCriterion("COMM_TITLE >=", value, "commTitle");
            return (Criteria) this;
        }

        public Criteria andCommTitleLessThan(String value) {
            addCriterion("COMM_TITLE <", value, "commTitle");
            return (Criteria) this;
        }

        public Criteria andCommTitleLessThanOrEqualTo(String value) {
            addCriterion("COMM_TITLE <=", value, "commTitle");
            return (Criteria) this;
        }

        public Criteria andCommTitleLike(String value) {
            addCriterion("COMM_TITLE like", value, "commTitle");
            return (Criteria) this;
        }

        public Criteria andCommTitleNotLike(String value) {
            addCriterion("COMM_TITLE not like", value, "commTitle");
            return (Criteria) this;
        }

        public Criteria andCommTitleIn(List<String> values) {
            addCriterion("COMM_TITLE in", values, "commTitle");
            return (Criteria) this;
        }

        public Criteria andCommTitleNotIn(List<String> values) {
            addCriterion("COMM_TITLE not in", values, "commTitle");
            return (Criteria) this;
        }

        public Criteria andCommTitleBetween(String value1, String value2) {
            addCriterion("COMM_TITLE between", value1, value2, "commTitle");
            return (Criteria) this;
        }

        public Criteria andCommTitleNotBetween(String value1, String value2) {
            addCriterion("COMM_TITLE not between", value1, value2, "commTitle");
            return (Criteria) this;
        }

        public Criteria andCommAddressIsNull() {
            addCriterion("COMM_ADDRESS is null");
            return (Criteria) this;
        }

        public Criteria andCommAddressIsNotNull() {
            addCriterion("COMM_ADDRESS is not null");
            return (Criteria) this;
        }

        public Criteria andCommAddressEqualTo(String value) {
            addCriterion("COMM_ADDRESS =", value, "commAddress");
            return (Criteria) this;
        }

        public Criteria andCommAddressNotEqualTo(String value) {
            addCriterion("COMM_ADDRESS <>", value, "commAddress");
            return (Criteria) this;
        }

        public Criteria andCommAddressGreaterThan(String value) {
            addCriterion("COMM_ADDRESS >", value, "commAddress");
            return (Criteria) this;
        }

        public Criteria andCommAddressGreaterThanOrEqualTo(String value) {
            addCriterion("COMM_ADDRESS >=", value, "commAddress");
            return (Criteria) this;
        }

        public Criteria andCommAddressLessThan(String value) {
            addCriterion("COMM_ADDRESS <", value, "commAddress");
            return (Criteria) this;
        }

        public Criteria andCommAddressLessThanOrEqualTo(String value) {
            addCriterion("COMM_ADDRESS <=", value, "commAddress");
            return (Criteria) this;
        }

        public Criteria andCommAddressLike(String value) {
            addCriterion("COMM_ADDRESS like", value, "commAddress");
            return (Criteria) this;
        }

        public Criteria andCommAddressNotLike(String value) {
            addCriterion("COMM_ADDRESS not like", value, "commAddress");
            return (Criteria) this;
        }

        public Criteria andCommAddressIn(List<String> values) {
            addCriterion("COMM_ADDRESS in", values, "commAddress");
            return (Criteria) this;
        }

        public Criteria andCommAddressNotIn(List<String> values) {
            addCriterion("COMM_ADDRESS not in", values, "commAddress");
            return (Criteria) this;
        }

        public Criteria andCommAddressBetween(String value1, String value2) {
            addCriterion("COMM_ADDRESS between", value1, value2, "commAddress");
            return (Criteria) this;
        }

        public Criteria andCommAddressNotBetween(String value1, String value2) {
            addCriterion("COMM_ADDRESS not between", value1, value2, "commAddress");
            return (Criteria) this;
        }

        public Criteria andCommDespIsNull() {
            addCriterion("COMM_DESP is null");
            return (Criteria) this;
        }

        public Criteria andCommDespIsNotNull() {
            addCriterion("COMM_DESP is not null");
            return (Criteria) this;
        }

        public Criteria andCommDespEqualTo(String value) {
            addCriterion("COMM_DESP =", value, "commDesp");
            return (Criteria) this;
        }

        public Criteria andCommDespNotEqualTo(String value) {
            addCriterion("COMM_DESP <>", value, "commDesp");
            return (Criteria) this;
        }

        public Criteria andCommDespGreaterThan(String value) {
            addCriterion("COMM_DESP >", value, "commDesp");
            return (Criteria) this;
        }

        public Criteria andCommDespGreaterThanOrEqualTo(String value) {
            addCriterion("COMM_DESP >=", value, "commDesp");
            return (Criteria) this;
        }

        public Criteria andCommDespLessThan(String value) {
            addCriterion("COMM_DESP <", value, "commDesp");
            return (Criteria) this;
        }

        public Criteria andCommDespLessThanOrEqualTo(String value) {
            addCriterion("COMM_DESP <=", value, "commDesp");
            return (Criteria) this;
        }

        public Criteria andCommDespLike(String value) {
            addCriterion("COMM_DESP like", value, "commDesp");
            return (Criteria) this;
        }

        public Criteria andCommDespNotLike(String value) {
            addCriterion("COMM_DESP not like", value, "commDesp");
            return (Criteria) this;
        }

        public Criteria andCommDespIn(List<String> values) {
            addCriterion("COMM_DESP in", values, "commDesp");
            return (Criteria) this;
        }

        public Criteria andCommDespNotIn(List<String> values) {
            addCriterion("COMM_DESP not in", values, "commDesp");
            return (Criteria) this;
        }

        public Criteria andCommDespBetween(String value1, String value2) {
            addCriterion("COMM_DESP between", value1, value2, "commDesp");
            return (Criteria) this;
        }

        public Criteria andCommDespNotBetween(String value1, String value2) {
            addCriterion("COMM_DESP not between", value1, value2, "commDesp");
            return (Criteria) this;
        }

        public Criteria andCommCoordinateIsNull() {
            addCriterion("COMM_COORDINATE is null");
            return (Criteria) this;
        }

        public Criteria andCommCoordinateIsNotNull() {
            addCriterion("COMM_COORDINATE is not null");
            return (Criteria) this;
        }

        public Criteria andCommCoordinateEqualTo(String value) {
            addCriterion("COMM_COORDINATE =", value, "commCoordinate");
            return (Criteria) this;
        }

        public Criteria andCommCoordinateNotEqualTo(String value) {
            addCriterion("COMM_COORDINATE <>", value, "commCoordinate");
            return (Criteria) this;
        }

        public Criteria andCommCoordinateGreaterThan(String value) {
            addCriterion("COMM_COORDINATE >", value, "commCoordinate");
            return (Criteria) this;
        }

        public Criteria andCommCoordinateGreaterThanOrEqualTo(String value) {
            addCriterion("COMM_COORDINATE >=", value, "commCoordinate");
            return (Criteria) this;
        }

        public Criteria andCommCoordinateLessThan(String value) {
            addCriterion("COMM_COORDINATE <", value, "commCoordinate");
            return (Criteria) this;
        }

        public Criteria andCommCoordinateLessThanOrEqualTo(String value) {
            addCriterion("COMM_COORDINATE <=", value, "commCoordinate");
            return (Criteria) this;
        }

        public Criteria andCommCoordinateLike(String value) {
            addCriterion("COMM_COORDINATE like", value, "commCoordinate");
            return (Criteria) this;
        }

        public Criteria andCommCoordinateNotLike(String value) {
            addCriterion("COMM_COORDINATE not like", value, "commCoordinate");
            return (Criteria) this;
        }

        public Criteria andCommCoordinateIn(List<String> values) {
            addCriterion("COMM_COORDINATE in", values, "commCoordinate");
            return (Criteria) this;
        }

        public Criteria andCommCoordinateNotIn(List<String> values) {
            addCriterion("COMM_COORDINATE not in", values, "commCoordinate");
            return (Criteria) this;
        }

        public Criteria andCommCoordinateBetween(String value1, String value2) {
            addCriterion("COMM_COORDINATE between", value1, value2, "commCoordinate");
            return (Criteria) this;
        }

        public Criteria andCommCoordinateNotBetween(String value1, String value2) {
            addCriterion("COMM_COORDINATE not between", value1, value2, "commCoordinate");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table dbo.COMMUNITY
     *
     * @mbg.generated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table dbo.COMMUNITY
     *
     * @mbg.generated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}