package com.timebank.domain;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class ComplainExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table dbo.COMPLAIN
     *
     * @mbg.generated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table dbo.COMPLAIN
     *
     * @mbg.generated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table dbo.COMPLAIN
     *
     * @mbg.generated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dbo.COMPLAIN
     *
     * @mbg.generated
     */
    public ComplainExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dbo.COMPLAIN
     *
     * @mbg.generated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dbo.COMPLAIN
     *
     * @mbg.generated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dbo.COMPLAIN
     *
     * @mbg.generated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dbo.COMPLAIN
     *
     * @mbg.generated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dbo.COMPLAIN
     *
     * @mbg.generated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dbo.COMPLAIN
     *
     * @mbg.generated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dbo.COMPLAIN
     *
     * @mbg.generated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dbo.COMPLAIN
     *
     * @mbg.generated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dbo.COMPLAIN
     *
     * @mbg.generated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dbo.COMPLAIN
     *
     * @mbg.generated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table dbo.COMPLAIN
     *
     * @mbg.generated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andCompGuidIsNull() {
            addCriterion("COMP_GUID is null");
            return (Criteria) this;
        }

        public Criteria andCompGuidIsNotNull() {
            addCriterion("COMP_GUID is not null");
            return (Criteria) this;
        }

        public Criteria andCompGuidEqualTo(String value) {
            addCriterion("COMP_GUID =", value, "compGuid");
            return (Criteria) this;
        }

        public Criteria andCompGuidNotEqualTo(String value) {
            addCriterion("COMP_GUID <>", value, "compGuid");
            return (Criteria) this;
        }

        public Criteria andCompGuidGreaterThan(String value) {
            addCriterion("COMP_GUID >", value, "compGuid");
            return (Criteria) this;
        }

        public Criteria andCompGuidGreaterThanOrEqualTo(String value) {
            addCriterion("COMP_GUID >=", value, "compGuid");
            return (Criteria) this;
        }

        public Criteria andCompGuidLessThan(String value) {
            addCriterion("COMP_GUID <", value, "compGuid");
            return (Criteria) this;
        }

        public Criteria andCompGuidLessThanOrEqualTo(String value) {
            addCriterion("COMP_GUID <=", value, "compGuid");
            return (Criteria) this;
        }

        public Criteria andCompGuidLike(String value) {
            addCriterion("COMP_GUID like", value, "compGuid");
            return (Criteria) this;
        }

        public Criteria andCompGuidNotLike(String value) {
            addCriterion("COMP_GUID not like", value, "compGuid");
            return (Criteria) this;
        }

        public Criteria andCompGuidIn(List<String> values) {
            addCriterion("COMP_GUID in", values, "compGuid");
            return (Criteria) this;
        }

        public Criteria andCompGuidNotIn(List<String> values) {
            addCriterion("COMP_GUID not in", values, "compGuid");
            return (Criteria) this;
        }

        public Criteria andCompGuidBetween(String value1, String value2) {
            addCriterion("COMP_GUID between", value1, value2, "compGuid");
            return (Criteria) this;
        }

        public Criteria andCompGuidNotBetween(String value1, String value2) {
            addCriterion("COMP_GUID not between", value1, value2, "compGuid");
            return (Criteria) this;
        }

        public Criteria andCompFromGuidIsNull() {
            addCriterion("COMP_FROM_GUID is null");
            return (Criteria) this;
        }

        public Criteria andCompFromGuidIsNotNull() {
            addCriterion("COMP_FROM_GUID is not null");
            return (Criteria) this;
        }

        public Criteria andCompFromGuidEqualTo(String value) {
            addCriterion("COMP_FROM_GUID =", value, "compFromGuid");
            return (Criteria) this;
        }

        public Criteria andCompFromGuidNotEqualTo(String value) {
            addCriterion("COMP_FROM_GUID <>", value, "compFromGuid");
            return (Criteria) this;
        }

        public Criteria andCompFromGuidGreaterThan(String value) {
            addCriterion("COMP_FROM_GUID >", value, "compFromGuid");
            return (Criteria) this;
        }

        public Criteria andCompFromGuidGreaterThanOrEqualTo(String value) {
            addCriterion("COMP_FROM_GUID >=", value, "compFromGuid");
            return (Criteria) this;
        }

        public Criteria andCompFromGuidLessThan(String value) {
            addCriterion("COMP_FROM_GUID <", value, "compFromGuid");
            return (Criteria) this;
        }

        public Criteria andCompFromGuidLessThanOrEqualTo(String value) {
            addCriterion("COMP_FROM_GUID <=", value, "compFromGuid");
            return (Criteria) this;
        }

        public Criteria andCompFromGuidLike(String value) {
            addCriterion("COMP_FROM_GUID like", value, "compFromGuid");
            return (Criteria) this;
        }

        public Criteria andCompFromGuidNotLike(String value) {
            addCriterion("COMP_FROM_GUID not like", value, "compFromGuid");
            return (Criteria) this;
        }

        public Criteria andCompFromGuidIn(List<String> values) {
            addCriterion("COMP_FROM_GUID in", values, "compFromGuid");
            return (Criteria) this;
        }

        public Criteria andCompFromGuidNotIn(List<String> values) {
            addCriterion("COMP_FROM_GUID not in", values, "compFromGuid");
            return (Criteria) this;
        }

        public Criteria andCompFromGuidBetween(String value1, String value2) {
            addCriterion("COMP_FROM_GUID between", value1, value2, "compFromGuid");
            return (Criteria) this;
        }

        public Criteria andCompFromGuidNotBetween(String value1, String value2) {
            addCriterion("COMP_FROM_GUID not between", value1, value2, "compFromGuid");
            return (Criteria) this;
        }

        public Criteria andCompToGuidIsNull() {
            addCriterion("COMP_TO_GUID is null");
            return (Criteria) this;
        }

        public Criteria andCompToGuidIsNotNull() {
            addCriterion("COMP_TO_GUID is not null");
            return (Criteria) this;
        }

        public Criteria andCompToGuidEqualTo(String value) {
            addCriterion("COMP_TO_GUID =", value, "compToGuid");
            return (Criteria) this;
        }

        public Criteria andCompToGuidNotEqualTo(String value) {
            addCriterion("COMP_TO_GUID <>", value, "compToGuid");
            return (Criteria) this;
        }

        public Criteria andCompToGuidGreaterThan(String value) {
            addCriterion("COMP_TO_GUID >", value, "compToGuid");
            return (Criteria) this;
        }

        public Criteria andCompToGuidGreaterThanOrEqualTo(String value) {
            addCriterion("COMP_TO_GUID >=", value, "compToGuid");
            return (Criteria) this;
        }

        public Criteria andCompToGuidLessThan(String value) {
            addCriterion("COMP_TO_GUID <", value, "compToGuid");
            return (Criteria) this;
        }

        public Criteria andCompToGuidLessThanOrEqualTo(String value) {
            addCriterion("COMP_TO_GUID <=", value, "compToGuid");
            return (Criteria) this;
        }

        public Criteria andCompToGuidLike(String value) {
            addCriterion("COMP_TO_GUID like", value, "compToGuid");
            return (Criteria) this;
        }

        public Criteria andCompToGuidNotLike(String value) {
            addCriterion("COMP_TO_GUID not like", value, "compToGuid");
            return (Criteria) this;
        }

        public Criteria andCompToGuidIn(List<String> values) {
            addCriterion("COMP_TO_GUID in", values, "compToGuid");
            return (Criteria) this;
        }

        public Criteria andCompToGuidNotIn(List<String> values) {
            addCriterion("COMP_TO_GUID not in", values, "compToGuid");
            return (Criteria) this;
        }

        public Criteria andCompToGuidBetween(String value1, String value2) {
            addCriterion("COMP_TO_GUID between", value1, value2, "compToGuid");
            return (Criteria) this;
        }

        public Criteria andCompToGuidNotBetween(String value1, String value2) {
            addCriterion("COMP_TO_GUID not between", value1, value2, "compToGuid");
            return (Criteria) this;
        }

        public Criteria andCompDespIsNull() {
            addCriterion("COMP_DESP is null");
            return (Criteria) this;
        }

        public Criteria andCompDespIsNotNull() {
            addCriterion("COMP_DESP is not null");
            return (Criteria) this;
        }

        public Criteria andCompDespEqualTo(String value) {
            addCriterion("COMP_DESP =", value, "compDesp");
            return (Criteria) this;
        }

        public Criteria andCompDespNotEqualTo(String value) {
            addCriterion("COMP_DESP <>", value, "compDesp");
            return (Criteria) this;
        }

        public Criteria andCompDespGreaterThan(String value) {
            addCriterion("COMP_DESP >", value, "compDesp");
            return (Criteria) this;
        }

        public Criteria andCompDespGreaterThanOrEqualTo(String value) {
            addCriterion("COMP_DESP >=", value, "compDesp");
            return (Criteria) this;
        }

        public Criteria andCompDespLessThan(String value) {
            addCriterion("COMP_DESP <", value, "compDesp");
            return (Criteria) this;
        }

        public Criteria andCompDespLessThanOrEqualTo(String value) {
            addCriterion("COMP_DESP <=", value, "compDesp");
            return (Criteria) this;
        }

        public Criteria andCompDespLike(String value) {
            addCriterion("COMP_DESP like", value, "compDesp");
            return (Criteria) this;
        }

        public Criteria andCompDespNotLike(String value) {
            addCriterion("COMP_DESP not like", value, "compDesp");
            return (Criteria) this;
        }

        public Criteria andCompDespIn(List<String> values) {
            addCriterion("COMP_DESP in", values, "compDesp");
            return (Criteria) this;
        }

        public Criteria andCompDespNotIn(List<String> values) {
            addCriterion("COMP_DESP not in", values, "compDesp");
            return (Criteria) this;
        }

        public Criteria andCompDespBetween(String value1, String value2) {
            addCriterion("COMP_DESP between", value1, value2, "compDesp");
            return (Criteria) this;
        }

        public Criteria andCompDespNotBetween(String value1, String value2) {
            addCriterion("COMP_DESP not between", value1, value2, "compDesp");
            return (Criteria) this;
        }

        public Criteria andCompIssueTimeIsNull() {
            addCriterion("COMP_ISSUE_TIME is null");
            return (Criteria) this;
        }

        public Criteria andCompIssueTimeIsNotNull() {
            addCriterion("COMP_ISSUE_TIME is not null");
            return (Criteria) this;
        }

        public Criteria andCompIssueTimeEqualTo(Date value) {
            addCriterion("COMP_ISSUE_TIME =", value, "compIssueTime");
            return (Criteria) this;
        }

        public Criteria andCompIssueTimeNotEqualTo(Date value) {
            addCriterion("COMP_ISSUE_TIME <>", value, "compIssueTime");
            return (Criteria) this;
        }

        public Criteria andCompIssueTimeGreaterThan(Date value) {
            addCriterion("COMP_ISSUE_TIME >", value, "compIssueTime");
            return (Criteria) this;
        }

        public Criteria andCompIssueTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("COMP_ISSUE_TIME >=", value, "compIssueTime");
            return (Criteria) this;
        }

        public Criteria andCompIssueTimeLessThan(Date value) {
            addCriterion("COMP_ISSUE_TIME <", value, "compIssueTime");
            return (Criteria) this;
        }

        public Criteria andCompIssueTimeLessThanOrEqualTo(Date value) {
            addCriterion("COMP_ISSUE_TIME <=", value, "compIssueTime");
            return (Criteria) this;
        }

        public Criteria andCompIssueTimeIn(List<Date> values) {
            addCriterion("COMP_ISSUE_TIME in", values, "compIssueTime");
            return (Criteria) this;
        }

        public Criteria andCompIssueTimeNotIn(List<Date> values) {
            addCriterion("COMP_ISSUE_TIME not in", values, "compIssueTime");
            return (Criteria) this;
        }

        public Criteria andCompIssueTimeBetween(Date value1, Date value2) {
            addCriterion("COMP_ISSUE_TIME between", value1, value2, "compIssueTime");
            return (Criteria) this;
        }

        public Criteria andCompIssueTimeNotBetween(Date value1, Date value2) {
            addCriterion("COMP_ISSUE_TIME not between", value1, value2, "compIssueTime");
            return (Criteria) this;
        }

        public Criteria andCompProcessTimeIsNull() {
            addCriterion("COMP_PROCESS_TIME is null");
            return (Criteria) this;
        }

        public Criteria andCompProcessTimeIsNotNull() {
            addCriterion("COMP_PROCESS_TIME is not null");
            return (Criteria) this;
        }

        public Criteria andCompProcessTimeEqualTo(Date value) {
            addCriterion("COMP_PROCESS_TIME =", value, "compProcessTime");
            return (Criteria) this;
        }

        public Criteria andCompProcessTimeNotEqualTo(Date value) {
            addCriterion("COMP_PROCESS_TIME <>", value, "compProcessTime");
            return (Criteria) this;
        }

        public Criteria andCompProcessTimeGreaterThan(Date value) {
            addCriterion("COMP_PROCESS_TIME >", value, "compProcessTime");
            return (Criteria) this;
        }

        public Criteria andCompProcessTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("COMP_PROCESS_TIME >=", value, "compProcessTime");
            return (Criteria) this;
        }

        public Criteria andCompProcessTimeLessThan(Date value) {
            addCriterion("COMP_PROCESS_TIME <", value, "compProcessTime");
            return (Criteria) this;
        }

        public Criteria andCompProcessTimeLessThanOrEqualTo(Date value) {
            addCriterion("COMP_PROCESS_TIME <=", value, "compProcessTime");
            return (Criteria) this;
        }

        public Criteria andCompProcessTimeIn(List<Date> values) {
            addCriterion("COMP_PROCESS_TIME in", values, "compProcessTime");
            return (Criteria) this;
        }

        public Criteria andCompProcessTimeNotIn(List<Date> values) {
            addCriterion("COMP_PROCESS_TIME not in", values, "compProcessTime");
            return (Criteria) this;
        }

        public Criteria andCompProcessTimeBetween(Date value1, Date value2) {
            addCriterion("COMP_PROCESS_TIME between", value1, value2, "compProcessTime");
            return (Criteria) this;
        }

        public Criteria andCompProcessTimeNotBetween(Date value1, Date value2) {
            addCriterion("COMP_PROCESS_TIME not between", value1, value2, "compProcessTime");
            return (Criteria) this;
        }

        public Criteria andCompProcessResultIsNull() {
            addCriterion("COMP_PROCESS_RESULT is null");
            return (Criteria) this;
        }

        public Criteria andCompProcessResultIsNotNull() {
            addCriterion("COMP_PROCESS_RESULT is not null");
            return (Criteria) this;
        }

        public Criteria andCompProcessResultEqualTo(String value) {
            addCriterion("COMP_PROCESS_RESULT =", value, "compProcessResult");
            return (Criteria) this;
        }

        public Criteria andCompProcessResultNotEqualTo(String value) {
            addCriterion("COMP_PROCESS_RESULT <>", value, "compProcessResult");
            return (Criteria) this;
        }

        public Criteria andCompProcessResultGreaterThan(String value) {
            addCriterion("COMP_PROCESS_RESULT >", value, "compProcessResult");
            return (Criteria) this;
        }

        public Criteria andCompProcessResultGreaterThanOrEqualTo(String value) {
            addCriterion("COMP_PROCESS_RESULT >=", value, "compProcessResult");
            return (Criteria) this;
        }

        public Criteria andCompProcessResultLessThan(String value) {
            addCriterion("COMP_PROCESS_RESULT <", value, "compProcessResult");
            return (Criteria) this;
        }

        public Criteria andCompProcessResultLessThanOrEqualTo(String value) {
            addCriterion("COMP_PROCESS_RESULT <=", value, "compProcessResult");
            return (Criteria) this;
        }

        public Criteria andCompProcessResultLike(String value) {
            addCriterion("COMP_PROCESS_RESULT like", value, "compProcessResult");
            return (Criteria) this;
        }

        public Criteria andCompProcessResultNotLike(String value) {
            addCriterion("COMP_PROCESS_RESULT not like", value, "compProcessResult");
            return (Criteria) this;
        }

        public Criteria andCompProcessResultIn(List<String> values) {
            addCriterion("COMP_PROCESS_RESULT in", values, "compProcessResult");
            return (Criteria) this;
        }

        public Criteria andCompProcessResultNotIn(List<String> values) {
            addCriterion("COMP_PROCESS_RESULT not in", values, "compProcessResult");
            return (Criteria) this;
        }

        public Criteria andCompProcessResultBetween(String value1, String value2) {
            addCriterion("COMP_PROCESS_RESULT between", value1, value2, "compProcessResult");
            return (Criteria) this;
        }

        public Criteria andCompProcessResultNotBetween(String value1, String value2) {
            addCriterion("COMP_PROCESS_RESULT not between", value1, value2, "compProcessResult");
            return (Criteria) this;
        }

        public Criteria andCompTypeProcessStatusIsNull() {
            addCriterion("COMP_TYPE_PROCESS_STATUS is null");
            return (Criteria) this;
        }

        public Criteria andCompTypeProcessStatusIsNotNull() {
            addCriterion("COMP_TYPE_PROCESS_STATUS is not null");
            return (Criteria) this;
        }

        public Criteria andCompTypeProcessStatusEqualTo(String value) {
            addCriterion("COMP_TYPE_PROCESS_STATUS =", value, "compTypeProcessStatus");
            return (Criteria) this;
        }

        public Criteria andCompTypeProcessStatusNotEqualTo(String value) {
            addCriterion("COMP_TYPE_PROCESS_STATUS <>", value, "compTypeProcessStatus");
            return (Criteria) this;
        }

        public Criteria andCompTypeProcessStatusGreaterThan(String value) {
            addCriterion("COMP_TYPE_PROCESS_STATUS >", value, "compTypeProcessStatus");
            return (Criteria) this;
        }

        public Criteria andCompTypeProcessStatusGreaterThanOrEqualTo(String value) {
            addCriterion("COMP_TYPE_PROCESS_STATUS >=", value, "compTypeProcessStatus");
            return (Criteria) this;
        }

        public Criteria andCompTypeProcessStatusLessThan(String value) {
            addCriterion("COMP_TYPE_PROCESS_STATUS <", value, "compTypeProcessStatus");
            return (Criteria) this;
        }

        public Criteria andCompTypeProcessStatusLessThanOrEqualTo(String value) {
            addCriterion("COMP_TYPE_PROCESS_STATUS <=", value, "compTypeProcessStatus");
            return (Criteria) this;
        }

        public Criteria andCompTypeProcessStatusLike(String value) {
            addCriterion("COMP_TYPE_PROCESS_STATUS like", value, "compTypeProcessStatus");
            return (Criteria) this;
        }

        public Criteria andCompTypeProcessStatusNotLike(String value) {
            addCriterion("COMP_TYPE_PROCESS_STATUS not like", value, "compTypeProcessStatus");
            return (Criteria) this;
        }

        public Criteria andCompTypeProcessStatusIn(List<String> values) {
            addCriterion("COMP_TYPE_PROCESS_STATUS in", values, "compTypeProcessStatus");
            return (Criteria) this;
        }

        public Criteria andCompTypeProcessStatusNotIn(List<String> values) {
            addCriterion("COMP_TYPE_PROCESS_STATUS not in", values, "compTypeProcessStatus");
            return (Criteria) this;
        }

        public Criteria andCompTypeProcessStatusBetween(String value1, String value2) {
            addCriterion("COMP_TYPE_PROCESS_STATUS between", value1, value2, "compTypeProcessStatus");
            return (Criteria) this;
        }

        public Criteria andCompTypeProcessStatusNotBetween(String value1, String value2) {
            addCriterion("COMP_TYPE_PROCESS_STATUS not between", value1, value2, "compTypeProcessStatus");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table dbo.COMPLAIN
     *
     * @mbg.generated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table dbo.COMPLAIN
     *
     * @mbg.generated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}