package com.timebank.domain;

import java.util.Date;

public class Complain {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.COMPLAIN.COMP_GUID
     *
     * @mbg.generated
     */
    private String compGuid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.COMPLAIN.COMP_FROM_GUID
     *
     * @mbg.generated
     */
    private String compFromGuid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.COMPLAIN.COMP_TO_GUID
     *
     * @mbg.generated
     */
    private String compToGuid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.COMPLAIN.COMP_DESP
     *
     * @mbg.generated
     */
    private String compDesp;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.COMPLAIN.COMP_ISSUE_TIME
     *
     * @mbg.generated
     */
    private Date compIssueTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.COMPLAIN.COMP_PROCESS_TIME
     *
     * @mbg.generated
     */
    private Date compProcessTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.COMPLAIN.COMP_PROCESS_RESULT
     *
     * @mbg.generated
     */
    private String compProcessResult;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.COMPLAIN.COMP_TYPE_PROCESS_STATUS
     *
     * @mbg.generated
     */
    private String compTypeProcessStatus;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.COMPLAIN.COMP_GUID
     *
     * @return the value of dbo.COMPLAIN.COMP_GUID
     *
     * @mbg.generated
     */
    public String getCompGuid() {
        return compGuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.COMPLAIN.COMP_GUID
     *
     * @param compGuid the value for dbo.COMPLAIN.COMP_GUID
     *
     * @mbg.generated
     */
    public void setCompGuid(String compGuid) {
        this.compGuid = compGuid == null ? null : compGuid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.COMPLAIN.COMP_FROM_GUID
     *
     * @return the value of dbo.COMPLAIN.COMP_FROM_GUID
     *
     * @mbg.generated
     */
    public String getCompFromGuid() {
        return compFromGuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.COMPLAIN.COMP_FROM_GUID
     *
     * @param compFromGuid the value for dbo.COMPLAIN.COMP_FROM_GUID
     *
     * @mbg.generated
     */
    public void setCompFromGuid(String compFromGuid) {
        this.compFromGuid = compFromGuid == null ? null : compFromGuid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.COMPLAIN.COMP_TO_GUID
     *
     * @return the value of dbo.COMPLAIN.COMP_TO_GUID
     *
     * @mbg.generated
     */
    public String getCompToGuid() {
        return compToGuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.COMPLAIN.COMP_TO_GUID
     *
     * @param compToGuid the value for dbo.COMPLAIN.COMP_TO_GUID
     *
     * @mbg.generated
     */
    public void setCompToGuid(String compToGuid) {
        this.compToGuid = compToGuid == null ? null : compToGuid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.COMPLAIN.COMP_DESP
     *
     * @return the value of dbo.COMPLAIN.COMP_DESP
     *
     * @mbg.generated
     */
    public String getCompDesp() {
        return compDesp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.COMPLAIN.COMP_DESP
     *
     * @param compDesp the value for dbo.COMPLAIN.COMP_DESP
     *
     * @mbg.generated
     */
    public void setCompDesp(String compDesp) {
        this.compDesp = compDesp == null ? null : compDesp.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.COMPLAIN.COMP_ISSUE_TIME
     *
     * @return the value of dbo.COMPLAIN.COMP_ISSUE_TIME
     *
     * @mbg.generated
     */
    public Date getCompIssueTime() {
        return compIssueTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.COMPLAIN.COMP_ISSUE_TIME
     *
     * @param compIssueTime the value for dbo.COMPLAIN.COMP_ISSUE_TIME
     *
     * @mbg.generated
     */
    public void setCompIssueTime(Date compIssueTime) {
        this.compIssueTime = compIssueTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.COMPLAIN.COMP_PROCESS_TIME
     *
     * @return the value of dbo.COMPLAIN.COMP_PROCESS_TIME
     *
     * @mbg.generated
     */
    public Date getCompProcessTime() {
        return compProcessTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.COMPLAIN.COMP_PROCESS_TIME
     *
     * @param compProcessTime the value for dbo.COMPLAIN.COMP_PROCESS_TIME
     *
     * @mbg.generated
     */
    public void setCompProcessTime(Date compProcessTime) {
        this.compProcessTime = compProcessTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.COMPLAIN.COMP_PROCESS_RESULT
     *
     * @return the value of dbo.COMPLAIN.COMP_PROCESS_RESULT
     *
     * @mbg.generated
     */
    public String getCompProcessResult() {
        return compProcessResult;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.COMPLAIN.COMP_PROCESS_RESULT
     *
     * @param compProcessResult the value for dbo.COMPLAIN.COMP_PROCESS_RESULT
     *
     * @mbg.generated
     */
    public void setCompProcessResult(String compProcessResult) {
        this.compProcessResult = compProcessResult == null ? null : compProcessResult.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.COMPLAIN.COMP_TYPE_PROCESS_STATUS
     *
     * @return the value of dbo.COMPLAIN.COMP_TYPE_PROCESS_STATUS
     *
     * @mbg.generated
     */
    public String getCompTypeProcessStatus() {
        return compTypeProcessStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.COMPLAIN.COMP_TYPE_PROCESS_STATUS
     *
     * @param compTypeProcessStatus the value for dbo.COMPLAIN.COMP_TYPE_PROCESS_STATUS
     *
     * @mbg.generated
     */
    public void setCompTypeProcessStatus(String compTypeProcessStatus) {
        this.compTypeProcessStatus = compTypeProcessStatus == null ? null : compTypeProcessStatus.trim();
    }
}