package com.timebank.domain;

public class Group {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.GROUP.GROUP_GUID
     *
     * @mbg.generated
     */
    private String groupGuid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.GROUP.GROUP_TYPE_GROUP_ID
     *
     * @mbg.generated
     */
    private Integer groupTypeGroupId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.GROUP.GROUP_TYPE_GROUP_TITLE
     *
     * @mbg.generated
     */
    private String groupTypeGroupTitle;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.GROUP.GROUP_TYPE_GROUP_DESP
     *
     * @mbg.generated
     */
    private String groupTypeGroupDesp;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.GROUP.GROUP_GUID
     *
     * @return the value of dbo.GROUP.GROUP_GUID
     *
     * @mbg.generated
     */
    public String getGroupGuid() {
        return groupGuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.GROUP.GROUP_GUID
     *
     * @param groupGuid the value for dbo.GROUP.GROUP_GUID
     *
     * @mbg.generated
     */
    public void setGroupGuid(String groupGuid) {
        this.groupGuid = groupGuid == null ? null : groupGuid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.GROUP.GROUP_TYPE_GROUP_ID
     *
     * @return the value of dbo.GROUP.GROUP_TYPE_GROUP_ID
     *
     * @mbg.generated
     */
    public Integer getGroupTypeGroupId() {
        return groupTypeGroupId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.GROUP.GROUP_TYPE_GROUP_ID
     *
     * @param groupTypeGroupId the value for dbo.GROUP.GROUP_TYPE_GROUP_ID
     *
     * @mbg.generated
     */
    public void setGroupTypeGroupId(Integer groupTypeGroupId) {
        this.groupTypeGroupId = groupTypeGroupId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.GROUP.GROUP_TYPE_GROUP_TITLE
     *
     * @return the value of dbo.GROUP.GROUP_TYPE_GROUP_TITLE
     *
     * @mbg.generated
     */
    public String getGroupTypeGroupTitle() {
        return groupTypeGroupTitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.GROUP.GROUP_TYPE_GROUP_TITLE
     *
     * @param groupTypeGroupTitle the value for dbo.GROUP.GROUP_TYPE_GROUP_TITLE
     *
     * @mbg.generated
     */
    public void setGroupTypeGroupTitle(String groupTypeGroupTitle) {
        this.groupTypeGroupTitle = groupTypeGroupTitle == null ? null : groupTypeGroupTitle.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.GROUP.GROUP_TYPE_GROUP_DESP
     *
     * @return the value of dbo.GROUP.GROUP_TYPE_GROUP_DESP
     *
     * @mbg.generated
     */
    public String getGroupTypeGroupDesp() {
        return groupTypeGroupDesp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.GROUP.GROUP_TYPE_GROUP_DESP
     *
     * @param groupTypeGroupDesp the value for dbo.GROUP.GROUP_TYPE_GROUP_DESP
     *
     * @mbg.generated
     */
    public void setGroupTypeGroupDesp(String groupTypeGroupDesp) {
        this.groupTypeGroupDesp = groupTypeGroupDesp == null ? null : groupTypeGroupDesp.trim();
    }
}