package com.timebank.domain;

import java.util.ArrayList;
import java.util.List;

public class GroupExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table dbo.GROUP
     *
     * @mbg.generated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table dbo.GROUP
     *
     * @mbg.generated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table dbo.GROUP
     *
     * @mbg.generated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dbo.GROUP
     *
     * @mbg.generated
     */
    public GroupExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dbo.GROUP
     *
     * @mbg.generated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dbo.GROUP
     *
     * @mbg.generated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dbo.GROUP
     *
     * @mbg.generated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dbo.GROUP
     *
     * @mbg.generated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dbo.GROUP
     *
     * @mbg.generated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dbo.GROUP
     *
     * @mbg.generated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dbo.GROUP
     *
     * @mbg.generated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dbo.GROUP
     *
     * @mbg.generated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dbo.GROUP
     *
     * @mbg.generated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dbo.GROUP
     *
     * @mbg.generated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table dbo.GROUP
     *
     * @mbg.generated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andGroupGuidIsNull() {
            addCriterion("GROUP_GUID is null");
            return (Criteria) this;
        }

        public Criteria andGroupGuidIsNotNull() {
            addCriterion("GROUP_GUID is not null");
            return (Criteria) this;
        }

        public Criteria andGroupGuidEqualTo(String value) {
            addCriterion("GROUP_GUID =", value, "groupGuid");
            return (Criteria) this;
        }

        public Criteria andGroupGuidNotEqualTo(String value) {
            addCriterion("GROUP_GUID <>", value, "groupGuid");
            return (Criteria) this;
        }

        public Criteria andGroupGuidGreaterThan(String value) {
            addCriterion("GROUP_GUID >", value, "groupGuid");
            return (Criteria) this;
        }

        public Criteria andGroupGuidGreaterThanOrEqualTo(String value) {
            addCriterion("GROUP_GUID >=", value, "groupGuid");
            return (Criteria) this;
        }

        public Criteria andGroupGuidLessThan(String value) {
            addCriterion("GROUP_GUID <", value, "groupGuid");
            return (Criteria) this;
        }

        public Criteria andGroupGuidLessThanOrEqualTo(String value) {
            addCriterion("GROUP_GUID <=", value, "groupGuid");
            return (Criteria) this;
        }

        public Criteria andGroupGuidLike(String value) {
            addCriterion("GROUP_GUID like", value, "groupGuid");
            return (Criteria) this;
        }

        public Criteria andGroupGuidNotLike(String value) {
            addCriterion("GROUP_GUID not like", value, "groupGuid");
            return (Criteria) this;
        }

        public Criteria andGroupGuidIn(List<String> values) {
            addCriterion("GROUP_GUID in", values, "groupGuid");
            return (Criteria) this;
        }

        public Criteria andGroupGuidNotIn(List<String> values) {
            addCriterion("GROUP_GUID not in", values, "groupGuid");
            return (Criteria) this;
        }

        public Criteria andGroupGuidBetween(String value1, String value2) {
            addCriterion("GROUP_GUID between", value1, value2, "groupGuid");
            return (Criteria) this;
        }

        public Criteria andGroupGuidNotBetween(String value1, String value2) {
            addCriterion("GROUP_GUID not between", value1, value2, "groupGuid");
            return (Criteria) this;
        }

        public Criteria andGroupTypeGroupIdIsNull() {
            addCriterion("GROUP_TYPE_GROUP_ID is null");
            return (Criteria) this;
        }

        public Criteria andGroupTypeGroupIdIsNotNull() {
            addCriterion("GROUP_TYPE_GROUP_ID is not null");
            return (Criteria) this;
        }

        public Criteria andGroupTypeGroupIdEqualTo(Integer value) {
            addCriterion("GROUP_TYPE_GROUP_ID =", value, "groupTypeGroupId");
            return (Criteria) this;
        }

        public Criteria andGroupTypeGroupIdNotEqualTo(Integer value) {
            addCriterion("GROUP_TYPE_GROUP_ID <>", value, "groupTypeGroupId");
            return (Criteria) this;
        }

        public Criteria andGroupTypeGroupIdGreaterThan(Integer value) {
            addCriterion("GROUP_TYPE_GROUP_ID >", value, "groupTypeGroupId");
            return (Criteria) this;
        }

        public Criteria andGroupTypeGroupIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("GROUP_TYPE_GROUP_ID >=", value, "groupTypeGroupId");
            return (Criteria) this;
        }

        public Criteria andGroupTypeGroupIdLessThan(Integer value) {
            addCriterion("GROUP_TYPE_GROUP_ID <", value, "groupTypeGroupId");
            return (Criteria) this;
        }

        public Criteria andGroupTypeGroupIdLessThanOrEqualTo(Integer value) {
            addCriterion("GROUP_TYPE_GROUP_ID <=", value, "groupTypeGroupId");
            return (Criteria) this;
        }

        public Criteria andGroupTypeGroupIdIn(List<Integer> values) {
            addCriterion("GROUP_TYPE_GROUP_ID in", values, "groupTypeGroupId");
            return (Criteria) this;
        }

        public Criteria andGroupTypeGroupIdNotIn(List<Integer> values) {
            addCriterion("GROUP_TYPE_GROUP_ID not in", values, "groupTypeGroupId");
            return (Criteria) this;
        }

        public Criteria andGroupTypeGroupIdBetween(Integer value1, Integer value2) {
            addCriterion("GROUP_TYPE_GROUP_ID between", value1, value2, "groupTypeGroupId");
            return (Criteria) this;
        }

        public Criteria andGroupTypeGroupIdNotBetween(Integer value1, Integer value2) {
            addCriterion("GROUP_TYPE_GROUP_ID not between", value1, value2, "groupTypeGroupId");
            return (Criteria) this;
        }

        public Criteria andGroupTypeGroupTitleIsNull() {
            addCriterion("GROUP_TYPE_GROUP_TITLE is null");
            return (Criteria) this;
        }

        public Criteria andGroupTypeGroupTitleIsNotNull() {
            addCriterion("GROUP_TYPE_GROUP_TITLE is not null");
            return (Criteria) this;
        }

        public Criteria andGroupTypeGroupTitleEqualTo(String value) {
            addCriterion("GROUP_TYPE_GROUP_TITLE =", value, "groupTypeGroupTitle");
            return (Criteria) this;
        }

        public Criteria andGroupTypeGroupTitleNotEqualTo(String value) {
            addCriterion("GROUP_TYPE_GROUP_TITLE <>", value, "groupTypeGroupTitle");
            return (Criteria) this;
        }

        public Criteria andGroupTypeGroupTitleGreaterThan(String value) {
            addCriterion("GROUP_TYPE_GROUP_TITLE >", value, "groupTypeGroupTitle");
            return (Criteria) this;
        }

        public Criteria andGroupTypeGroupTitleGreaterThanOrEqualTo(String value) {
            addCriterion("GROUP_TYPE_GROUP_TITLE >=", value, "groupTypeGroupTitle");
            return (Criteria) this;
        }

        public Criteria andGroupTypeGroupTitleLessThan(String value) {
            addCriterion("GROUP_TYPE_GROUP_TITLE <", value, "groupTypeGroupTitle");
            return (Criteria) this;
        }

        public Criteria andGroupTypeGroupTitleLessThanOrEqualTo(String value) {
            addCriterion("GROUP_TYPE_GROUP_TITLE <=", value, "groupTypeGroupTitle");
            return (Criteria) this;
        }

        public Criteria andGroupTypeGroupTitleLike(String value) {
            addCriterion("GROUP_TYPE_GROUP_TITLE like", value, "groupTypeGroupTitle");
            return (Criteria) this;
        }

        public Criteria andGroupTypeGroupTitleNotLike(String value) {
            addCriterion("GROUP_TYPE_GROUP_TITLE not like", value, "groupTypeGroupTitle");
            return (Criteria) this;
        }

        public Criteria andGroupTypeGroupTitleIn(List<String> values) {
            addCriterion("GROUP_TYPE_GROUP_TITLE in", values, "groupTypeGroupTitle");
            return (Criteria) this;
        }

        public Criteria andGroupTypeGroupTitleNotIn(List<String> values) {
            addCriterion("GROUP_TYPE_GROUP_TITLE not in", values, "groupTypeGroupTitle");
            return (Criteria) this;
        }

        public Criteria andGroupTypeGroupTitleBetween(String value1, String value2) {
            addCriterion("GROUP_TYPE_GROUP_TITLE between", value1, value2, "groupTypeGroupTitle");
            return (Criteria) this;
        }

        public Criteria andGroupTypeGroupTitleNotBetween(String value1, String value2) {
            addCriterion("GROUP_TYPE_GROUP_TITLE not between", value1, value2, "groupTypeGroupTitle");
            return (Criteria) this;
        }

        public Criteria andGroupTypeGroupDespIsNull() {
            addCriterion("GROUP_TYPE_GROUP_DESP is null");
            return (Criteria) this;
        }

        public Criteria andGroupTypeGroupDespIsNotNull() {
            addCriterion("GROUP_TYPE_GROUP_DESP is not null");
            return (Criteria) this;
        }

        public Criteria andGroupTypeGroupDespEqualTo(String value) {
            addCriterion("GROUP_TYPE_GROUP_DESP =", value, "groupTypeGroupDesp");
            return (Criteria) this;
        }

        public Criteria andGroupTypeGroupDespNotEqualTo(String value) {
            addCriterion("GROUP_TYPE_GROUP_DESP <>", value, "groupTypeGroupDesp");
            return (Criteria) this;
        }

        public Criteria andGroupTypeGroupDespGreaterThan(String value) {
            addCriterion("GROUP_TYPE_GROUP_DESP >", value, "groupTypeGroupDesp");
            return (Criteria) this;
        }

        public Criteria andGroupTypeGroupDespGreaterThanOrEqualTo(String value) {
            addCriterion("GROUP_TYPE_GROUP_DESP >=", value, "groupTypeGroupDesp");
            return (Criteria) this;
        }

        public Criteria andGroupTypeGroupDespLessThan(String value) {
            addCriterion("GROUP_TYPE_GROUP_DESP <", value, "groupTypeGroupDesp");
            return (Criteria) this;
        }

        public Criteria andGroupTypeGroupDespLessThanOrEqualTo(String value) {
            addCriterion("GROUP_TYPE_GROUP_DESP <=", value, "groupTypeGroupDesp");
            return (Criteria) this;
        }

        public Criteria andGroupTypeGroupDespLike(String value) {
            addCriterion("GROUP_TYPE_GROUP_DESP like", value, "groupTypeGroupDesp");
            return (Criteria) this;
        }

        public Criteria andGroupTypeGroupDespNotLike(String value) {
            addCriterion("GROUP_TYPE_GROUP_DESP not like", value, "groupTypeGroupDesp");
            return (Criteria) this;
        }

        public Criteria andGroupTypeGroupDespIn(List<String> values) {
            addCriterion("GROUP_TYPE_GROUP_DESP in", values, "groupTypeGroupDesp");
            return (Criteria) this;
        }

        public Criteria andGroupTypeGroupDespNotIn(List<String> values) {
            addCriterion("GROUP_TYPE_GROUP_DESP not in", values, "groupTypeGroupDesp");
            return (Criteria) this;
        }

        public Criteria andGroupTypeGroupDespBetween(String value1, String value2) {
            addCriterion("GROUP_TYPE_GROUP_DESP between", value1, value2, "groupTypeGroupDesp");
            return (Criteria) this;
        }

        public Criteria andGroupTypeGroupDespNotBetween(String value1, String value2) {
            addCriterion("GROUP_TYPE_GROUP_DESP not between", value1, value2, "groupTypeGroupDesp");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table dbo.GROUP
     *
     * @mbg.generated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table dbo.GROUP
     *
     * @mbg.generated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}