package com.timebank.domain;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class ReqestExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table dbo.REQEST
     *
     * @mbg.generated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table dbo.REQEST
     *
     * @mbg.generated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table dbo.REQEST
     *
     * @mbg.generated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dbo.REQEST
     *
     * @mbg.generated
     */
    public ReqestExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dbo.REQEST
     *
     * @mbg.generated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dbo.REQEST
     *
     * @mbg.generated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dbo.REQEST
     *
     * @mbg.generated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dbo.REQEST
     *
     * @mbg.generated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dbo.REQEST
     *
     * @mbg.generated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dbo.REQEST
     *
     * @mbg.generated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dbo.REQEST
     *
     * @mbg.generated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dbo.REQEST
     *
     * @mbg.generated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dbo.REQEST
     *
     * @mbg.generated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dbo.REQEST
     *
     * @mbg.generated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table dbo.REQEST
     *
     * @mbg.generated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andReqGuidIsNull() {
            addCriterion("REQ_GUID is null");
            return (Criteria) this;
        }

        public Criteria andReqGuidIsNotNull() {
            addCriterion("REQ_GUID is not null");
            return (Criteria) this;
        }

        public Criteria andReqGuidEqualTo(String value) {
            addCriterion("REQ_GUID =", value, "reqGuid");
            return (Criteria) this;
        }

        public Criteria andReqGuidNotEqualTo(String value) {
            addCriterion("REQ_GUID <>", value, "reqGuid");
            return (Criteria) this;
        }

        public Criteria andReqGuidGreaterThan(String value) {
            addCriterion("REQ_GUID >", value, "reqGuid");
            return (Criteria) this;
        }

        public Criteria andReqGuidGreaterThanOrEqualTo(String value) {
            addCriterion("REQ_GUID >=", value, "reqGuid");
            return (Criteria) this;
        }

        public Criteria andReqGuidLessThan(String value) {
            addCriterion("REQ_GUID <", value, "reqGuid");
            return (Criteria) this;
        }

        public Criteria andReqGuidLessThanOrEqualTo(String value) {
            addCriterion("REQ_GUID <=", value, "reqGuid");
            return (Criteria) this;
        }

        public Criteria andReqGuidLike(String value) {
            addCriterion("REQ_GUID like", value, "reqGuid");
            return (Criteria) this;
        }

        public Criteria andReqGuidNotLike(String value) {
            addCriterion("REQ_GUID not like", value, "reqGuid");
            return (Criteria) this;
        }

        public Criteria andReqGuidIn(List<String> values) {
            addCriterion("REQ_GUID in", values, "reqGuid");
            return (Criteria) this;
        }

        public Criteria andReqGuidNotIn(List<String> values) {
            addCriterion("REQ_GUID not in", values, "reqGuid");
            return (Criteria) this;
        }

        public Criteria andReqGuidBetween(String value1, String value2) {
            addCriterion("REQ_GUID between", value1, value2, "reqGuid");
            return (Criteria) this;
        }

        public Criteria andReqGuidNotBetween(String value1, String value2) {
            addCriterion("REQ_GUID not between", value1, value2, "reqGuid");
            return (Criteria) this;
        }

        public Criteria andReqIssueUserGuidIsNull() {
            addCriterion("REQ_ISSUE_USER_GUID is null");
            return (Criteria) this;
        }

        public Criteria andReqIssueUserGuidIsNotNull() {
            addCriterion("REQ_ISSUE_USER_GUID is not null");
            return (Criteria) this;
        }

        public Criteria andReqIssueUserGuidEqualTo(String value) {
            addCriterion("REQ_ISSUE_USER_GUID =", value, "reqIssueUserGuid");
            return (Criteria) this;
        }

        public Criteria andReqIssueUserGuidNotEqualTo(String value) {
            addCriterion("REQ_ISSUE_USER_GUID <>", value, "reqIssueUserGuid");
            return (Criteria) this;
        }

        public Criteria andReqIssueUserGuidGreaterThan(String value) {
            addCriterion("REQ_ISSUE_USER_GUID >", value, "reqIssueUserGuid");
            return (Criteria) this;
        }

        public Criteria andReqIssueUserGuidGreaterThanOrEqualTo(String value) {
            addCriterion("REQ_ISSUE_USER_GUID >=", value, "reqIssueUserGuid");
            return (Criteria) this;
        }

        public Criteria andReqIssueUserGuidLessThan(String value) {
            addCriterion("REQ_ISSUE_USER_GUID <", value, "reqIssueUserGuid");
            return (Criteria) this;
        }

        public Criteria andReqIssueUserGuidLessThanOrEqualTo(String value) {
            addCriterion("REQ_ISSUE_USER_GUID <=", value, "reqIssueUserGuid");
            return (Criteria) this;
        }

        public Criteria andReqIssueUserGuidLike(String value) {
            addCriterion("REQ_ISSUE_USER_GUID like", value, "reqIssueUserGuid");
            return (Criteria) this;
        }

        public Criteria andReqIssueUserGuidNotLike(String value) {
            addCriterion("REQ_ISSUE_USER_GUID not like", value, "reqIssueUserGuid");
            return (Criteria) this;
        }

        public Criteria andReqIssueUserGuidIn(List<String> values) {
            addCriterion("REQ_ISSUE_USER_GUID in", values, "reqIssueUserGuid");
            return (Criteria) this;
        }

        public Criteria andReqIssueUserGuidNotIn(List<String> values) {
            addCriterion("REQ_ISSUE_USER_GUID not in", values, "reqIssueUserGuid");
            return (Criteria) this;
        }

        public Criteria andReqIssueUserGuidBetween(String value1, String value2) {
            addCriterion("REQ_ISSUE_USER_GUID between", value1, value2, "reqIssueUserGuid");
            return (Criteria) this;
        }

        public Criteria andReqIssueUserGuidNotBetween(String value1, String value2) {
            addCriterion("REQ_ISSUE_USER_GUID not between", value1, value2, "reqIssueUserGuid");
            return (Criteria) this;
        }

        public Criteria andReqIssueTimeIsNull() {
            addCriterion("REQ_ISSUE_TIME is null");
            return (Criteria) this;
        }

        public Criteria andReqIssueTimeIsNotNull() {
            addCriterion("REQ_ISSUE_TIME is not null");
            return (Criteria) this;
        }

        public Criteria andReqIssueTimeEqualTo(Date value) {
            addCriterion("REQ_ISSUE_TIME =", value, "reqIssueTime");
            return (Criteria) this;
        }

        public Criteria andReqIssueTimeNotEqualTo(Date value) {
            addCriterion("REQ_ISSUE_TIME <>", value, "reqIssueTime");
            return (Criteria) this;
        }

        public Criteria andReqIssueTimeGreaterThan(Date value) {
            addCriterion("REQ_ISSUE_TIME >", value, "reqIssueTime");
            return (Criteria) this;
        }

        public Criteria andReqIssueTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("REQ_ISSUE_TIME >=", value, "reqIssueTime");
            return (Criteria) this;
        }

        public Criteria andReqIssueTimeLessThan(Date value) {
            addCriterion("REQ_ISSUE_TIME <", value, "reqIssueTime");
            return (Criteria) this;
        }

        public Criteria andReqIssueTimeLessThanOrEqualTo(Date value) {
            addCriterion("REQ_ISSUE_TIME <=", value, "reqIssueTime");
            return (Criteria) this;
        }

        public Criteria andReqIssueTimeIn(List<Date> values) {
            addCriterion("REQ_ISSUE_TIME in", values, "reqIssueTime");
            return (Criteria) this;
        }

        public Criteria andReqIssueTimeNotIn(List<Date> values) {
            addCriterion("REQ_ISSUE_TIME not in", values, "reqIssueTime");
            return (Criteria) this;
        }

        public Criteria andReqIssueTimeBetween(Date value1, Date value2) {
            addCriterion("REQ_ISSUE_TIME between", value1, value2, "reqIssueTime");
            return (Criteria) this;
        }

        public Criteria andReqIssueTimeNotBetween(Date value1, Date value2) {
            addCriterion("REQ_ISSUE_TIME not between", value1, value2, "reqIssueTime");
            return (Criteria) this;
        }

        public Criteria andReqAddressIsNull() {
            addCriterion("REQ_ADDRESS is null");
            return (Criteria) this;
        }

        public Criteria andReqAddressIsNotNull() {
            addCriterion("REQ_ADDRESS is not null");
            return (Criteria) this;
        }

        public Criteria andReqAddressEqualTo(String value) {
            addCriterion("REQ_ADDRESS =", value, "reqAddress");
            return (Criteria) this;
        }

        public Criteria andReqAddressNotEqualTo(String value) {
            addCriterion("REQ_ADDRESS <>", value, "reqAddress");
            return (Criteria) this;
        }

        public Criteria andReqAddressGreaterThan(String value) {
            addCriterion("REQ_ADDRESS >", value, "reqAddress");
            return (Criteria) this;
        }

        public Criteria andReqAddressGreaterThanOrEqualTo(String value) {
            addCriterion("REQ_ADDRESS >=", value, "reqAddress");
            return (Criteria) this;
        }

        public Criteria andReqAddressLessThan(String value) {
            addCriterion("REQ_ADDRESS <", value, "reqAddress");
            return (Criteria) this;
        }

        public Criteria andReqAddressLessThanOrEqualTo(String value) {
            addCriterion("REQ_ADDRESS <=", value, "reqAddress");
            return (Criteria) this;
        }

        public Criteria andReqAddressLike(String value) {
            addCriterion("REQ_ADDRESS like", value, "reqAddress");
            return (Criteria) this;
        }

        public Criteria andReqAddressNotLike(String value) {
            addCriterion("REQ_ADDRESS not like", value, "reqAddress");
            return (Criteria) this;
        }

        public Criteria andReqAddressIn(List<String> values) {
            addCriterion("REQ_ADDRESS in", values, "reqAddress");
            return (Criteria) this;
        }

        public Criteria andReqAddressNotIn(List<String> values) {
            addCriterion("REQ_ADDRESS not in", values, "reqAddress");
            return (Criteria) this;
        }

        public Criteria andReqAddressBetween(String value1, String value2) {
            addCriterion("REQ_ADDRESS between", value1, value2, "reqAddress");
            return (Criteria) this;
        }

        public Criteria andReqAddressNotBetween(String value1, String value2) {
            addCriterion("REQ_ADDRESS not between", value1, value2, "reqAddress");
            return (Criteria) this;
        }

        public Criteria andReqTitleIsNull() {
            addCriterion("REQ_TITLE is null");
            return (Criteria) this;
        }

        public Criteria andReqTitleIsNotNull() {
            addCriterion("REQ_TITLE is not null");
            return (Criteria) this;
        }

        public Criteria andReqTitleEqualTo(String value) {
            addCriterion("REQ_TITLE =", value, "reqTitle");
            return (Criteria) this;
        }

        public Criteria andReqTitleNotEqualTo(String value) {
            addCriterion("REQ_TITLE <>", value, "reqTitle");
            return (Criteria) this;
        }

        public Criteria andReqTitleGreaterThan(String value) {
            addCriterion("REQ_TITLE >", value, "reqTitle");
            return (Criteria) this;
        }

        public Criteria andReqTitleGreaterThanOrEqualTo(String value) {
            addCriterion("REQ_TITLE >=", value, "reqTitle");
            return (Criteria) this;
        }

        public Criteria andReqTitleLessThan(String value) {
            addCriterion("REQ_TITLE <", value, "reqTitle");
            return (Criteria) this;
        }

        public Criteria andReqTitleLessThanOrEqualTo(String value) {
            addCriterion("REQ_TITLE <=", value, "reqTitle");
            return (Criteria) this;
        }

        public Criteria andReqTitleLike(String value) {
            addCriterion("REQ_TITLE like", value, "reqTitle");
            return (Criteria) this;
        }

        public Criteria andReqTitleNotLike(String value) {
            addCriterion("REQ_TITLE not like", value, "reqTitle");
            return (Criteria) this;
        }

        public Criteria andReqTitleIn(List<String> values) {
            addCriterion("REQ_TITLE in", values, "reqTitle");
            return (Criteria) this;
        }

        public Criteria andReqTitleNotIn(List<String> values) {
            addCriterion("REQ_TITLE not in", values, "reqTitle");
            return (Criteria) this;
        }

        public Criteria andReqTitleBetween(String value1, String value2) {
            addCriterion("REQ_TITLE between", value1, value2, "reqTitle");
            return (Criteria) this;
        }

        public Criteria andReqTitleNotBetween(String value1, String value2) {
            addCriterion("REQ_TITLE not between", value1, value2, "reqTitle");
            return (Criteria) this;
        }

        public Criteria andReqDespIsNull() {
            addCriterion("REQ_DESP is null");
            return (Criteria) this;
        }

        public Criteria andReqDespIsNotNull() {
            addCriterion("REQ_DESP is not null");
            return (Criteria) this;
        }

        public Criteria andReqDespEqualTo(String value) {
            addCriterion("REQ_DESP =", value, "reqDesp");
            return (Criteria) this;
        }

        public Criteria andReqDespNotEqualTo(String value) {
            addCriterion("REQ_DESP <>", value, "reqDesp");
            return (Criteria) this;
        }

        public Criteria andReqDespGreaterThan(String value) {
            addCriterion("REQ_DESP >", value, "reqDesp");
            return (Criteria) this;
        }

        public Criteria andReqDespGreaterThanOrEqualTo(String value) {
            addCriterion("REQ_DESP >=", value, "reqDesp");
            return (Criteria) this;
        }

        public Criteria andReqDespLessThan(String value) {
            addCriterion("REQ_DESP <", value, "reqDesp");
            return (Criteria) this;
        }

        public Criteria andReqDespLessThanOrEqualTo(String value) {
            addCriterion("REQ_DESP <=", value, "reqDesp");
            return (Criteria) this;
        }

        public Criteria andReqDespLike(String value) {
            addCriterion("REQ_DESP like", value, "reqDesp");
            return (Criteria) this;
        }

        public Criteria andReqDespNotLike(String value) {
            addCriterion("REQ_DESP not like", value, "reqDesp");
            return (Criteria) this;
        }

        public Criteria andReqDespIn(List<String> values) {
            addCriterion("REQ_DESP in", values, "reqDesp");
            return (Criteria) this;
        }

        public Criteria andReqDespNotIn(List<String> values) {
            addCriterion("REQ_DESP not in", values, "reqDesp");
            return (Criteria) this;
        }

        public Criteria andReqDespBetween(String value1, String value2) {
            addCriterion("REQ_DESP between", value1, value2, "reqDesp");
            return (Criteria) this;
        }

        public Criteria andReqDespNotBetween(String value1, String value2) {
            addCriterion("REQ_DESP not between", value1, value2, "reqDesp");
            return (Criteria) this;
        }

        public Criteria andReqCommentIsNull() {
            addCriterion("REQ_COMMENT is null");
            return (Criteria) this;
        }

        public Criteria andReqCommentIsNotNull() {
            addCriterion("REQ_COMMENT is not null");
            return (Criteria) this;
        }

        public Criteria andReqCommentEqualTo(String value) {
            addCriterion("REQ_COMMENT =", value, "reqComment");
            return (Criteria) this;
        }

        public Criteria andReqCommentNotEqualTo(String value) {
            addCriterion("REQ_COMMENT <>", value, "reqComment");
            return (Criteria) this;
        }

        public Criteria andReqCommentGreaterThan(String value) {
            addCriterion("REQ_COMMENT >", value, "reqComment");
            return (Criteria) this;
        }

        public Criteria andReqCommentGreaterThanOrEqualTo(String value) {
            addCriterion("REQ_COMMENT >=", value, "reqComment");
            return (Criteria) this;
        }

        public Criteria andReqCommentLessThan(String value) {
            addCriterion("REQ_COMMENT <", value, "reqComment");
            return (Criteria) this;
        }

        public Criteria andReqCommentLessThanOrEqualTo(String value) {
            addCriterion("REQ_COMMENT <=", value, "reqComment");
            return (Criteria) this;
        }

        public Criteria andReqCommentLike(String value) {
            addCriterion("REQ_COMMENT like", value, "reqComment");
            return (Criteria) this;
        }

        public Criteria andReqCommentNotLike(String value) {
            addCriterion("REQ_COMMENT not like", value, "reqComment");
            return (Criteria) this;
        }

        public Criteria andReqCommentIn(List<String> values) {
            addCriterion("REQ_COMMENT in", values, "reqComment");
            return (Criteria) this;
        }

        public Criteria andReqCommentNotIn(List<String> values) {
            addCriterion("REQ_COMMENT not in", values, "reqComment");
            return (Criteria) this;
        }

        public Criteria andReqCommentBetween(String value1, String value2) {
            addCriterion("REQ_COMMENT between", value1, value2, "reqComment");
            return (Criteria) this;
        }

        public Criteria andReqCommentNotBetween(String value1, String value2) {
            addCriterion("REQ_COMMENT not between", value1, value2, "reqComment");
            return (Criteria) this;
        }

        public Criteria andReqDispatchTimeIsNull() {
            addCriterion("REQ_DISPATCH_TIME is null");
            return (Criteria) this;
        }

        public Criteria andReqDispatchTimeIsNotNull() {
            addCriterion("REQ_DISPATCH_TIME is not null");
            return (Criteria) this;
        }

        public Criteria andReqDispatchTimeEqualTo(Date value) {
            addCriterion("REQ_DISPATCH_TIME =", value, "reqDispatchTime");
            return (Criteria) this;
        }

        public Criteria andReqDispatchTimeNotEqualTo(Date value) {
            addCriterion("REQ_DISPATCH_TIME <>", value, "reqDispatchTime");
            return (Criteria) this;
        }

        public Criteria andReqDispatchTimeGreaterThan(Date value) {
            addCriterion("REQ_DISPATCH_TIME >", value, "reqDispatchTime");
            return (Criteria) this;
        }

        public Criteria andReqDispatchTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("REQ_DISPATCH_TIME >=", value, "reqDispatchTime");
            return (Criteria) this;
        }

        public Criteria andReqDispatchTimeLessThan(Date value) {
            addCriterion("REQ_DISPATCH_TIME <", value, "reqDispatchTime");
            return (Criteria) this;
        }

        public Criteria andReqDispatchTimeLessThanOrEqualTo(Date value) {
            addCriterion("REQ_DISPATCH_TIME <=", value, "reqDispatchTime");
            return (Criteria) this;
        }

        public Criteria andReqDispatchTimeIn(List<Date> values) {
            addCriterion("REQ_DISPATCH_TIME in", values, "reqDispatchTime");
            return (Criteria) this;
        }

        public Criteria andReqDispatchTimeNotIn(List<Date> values) {
            addCriterion("REQ_DISPATCH_TIME not in", values, "reqDispatchTime");
            return (Criteria) this;
        }

        public Criteria andReqDispatchTimeBetween(Date value1, Date value2) {
            addCriterion("REQ_DISPATCH_TIME between", value1, value2, "reqDispatchTime");
            return (Criteria) this;
        }

        public Criteria andReqDispatchTimeNotBetween(Date value1, Date value2) {
            addCriterion("REQ_DISPATCH_TIME not between", value1, value2, "reqDispatchTime");
            return (Criteria) this;
        }

        public Criteria andReqTypeGuidClassIsNull() {
            addCriterion("REQ_TYPE_GUID_CLASS is null");
            return (Criteria) this;
        }

        public Criteria andReqTypeGuidClassIsNotNull() {
            addCriterion("REQ_TYPE_GUID_CLASS is not null");
            return (Criteria) this;
        }

        public Criteria andReqTypeGuidClassEqualTo(String value) {
            addCriterion("REQ_TYPE_GUID_CLASS =", value, "reqTypeGuidClass");
            return (Criteria) this;
        }

        public Criteria andReqTypeGuidClassNotEqualTo(String value) {
            addCriterion("REQ_TYPE_GUID_CLASS <>", value, "reqTypeGuidClass");
            return (Criteria) this;
        }

        public Criteria andReqTypeGuidClassGreaterThan(String value) {
            addCriterion("REQ_TYPE_GUID_CLASS >", value, "reqTypeGuidClass");
            return (Criteria) this;
        }

        public Criteria andReqTypeGuidClassGreaterThanOrEqualTo(String value) {
            addCriterion("REQ_TYPE_GUID_CLASS >=", value, "reqTypeGuidClass");
            return (Criteria) this;
        }

        public Criteria andReqTypeGuidClassLessThan(String value) {
            addCriterion("REQ_TYPE_GUID_CLASS <", value, "reqTypeGuidClass");
            return (Criteria) this;
        }

        public Criteria andReqTypeGuidClassLessThanOrEqualTo(String value) {
            addCriterion("REQ_TYPE_GUID_CLASS <=", value, "reqTypeGuidClass");
            return (Criteria) this;
        }

        public Criteria andReqTypeGuidClassLike(String value) {
            addCriterion("REQ_TYPE_GUID_CLASS like", value, "reqTypeGuidClass");
            return (Criteria) this;
        }

        public Criteria andReqTypeGuidClassNotLike(String value) {
            addCriterion("REQ_TYPE_GUID_CLASS not like", value, "reqTypeGuidClass");
            return (Criteria) this;
        }

        public Criteria andReqTypeGuidClassIn(List<String> values) {
            addCriterion("REQ_TYPE_GUID_CLASS in", values, "reqTypeGuidClass");
            return (Criteria) this;
        }

        public Criteria andReqTypeGuidClassNotIn(List<String> values) {
            addCriterion("REQ_TYPE_GUID_CLASS not in", values, "reqTypeGuidClass");
            return (Criteria) this;
        }

        public Criteria andReqTypeGuidClassBetween(String value1, String value2) {
            addCriterion("REQ_TYPE_GUID_CLASS between", value1, value2, "reqTypeGuidClass");
            return (Criteria) this;
        }

        public Criteria andReqTypeGuidClassNotBetween(String value1, String value2) {
            addCriterion("REQ_TYPE_GUID_CLASS not between", value1, value2, "reqTypeGuidClass");
            return (Criteria) this;
        }

        public Criteria andReqAvailableStartTimeIsNull() {
            addCriterion("REQ_AVAILABLE_START_TIME is null");
            return (Criteria) this;
        }

        public Criteria andReqAvailableStartTimeIsNotNull() {
            addCriterion("REQ_AVAILABLE_START_TIME is not null");
            return (Criteria) this;
        }

        public Criteria andReqAvailableStartTimeEqualTo(Date value) {
            addCriterion("REQ_AVAILABLE_START_TIME =", value, "reqAvailableStartTime");
            return (Criteria) this;
        }

        public Criteria andReqAvailableStartTimeNotEqualTo(Date value) {
            addCriterion("REQ_AVAILABLE_START_TIME <>", value, "reqAvailableStartTime");
            return (Criteria) this;
        }

        public Criteria andReqAvailableStartTimeGreaterThan(Date value) {
            addCriterion("REQ_AVAILABLE_START_TIME >", value, "reqAvailableStartTime");
            return (Criteria) this;
        }

        public Criteria andReqAvailableStartTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("REQ_AVAILABLE_START_TIME >=", value, "reqAvailableStartTime");
            return (Criteria) this;
        }

        public Criteria andReqAvailableStartTimeLessThan(Date value) {
            addCriterion("REQ_AVAILABLE_START_TIME <", value, "reqAvailableStartTime");
            return (Criteria) this;
        }

        public Criteria andReqAvailableStartTimeLessThanOrEqualTo(Date value) {
            addCriterion("REQ_AVAILABLE_START_TIME <=", value, "reqAvailableStartTime");
            return (Criteria) this;
        }

        public Criteria andReqAvailableStartTimeIn(List<Date> values) {
            addCriterion("REQ_AVAILABLE_START_TIME in", values, "reqAvailableStartTime");
            return (Criteria) this;
        }

        public Criteria andReqAvailableStartTimeNotIn(List<Date> values) {
            addCriterion("REQ_AVAILABLE_START_TIME not in", values, "reqAvailableStartTime");
            return (Criteria) this;
        }

        public Criteria andReqAvailableStartTimeBetween(Date value1, Date value2) {
            addCriterion("REQ_AVAILABLE_START_TIME between", value1, value2, "reqAvailableStartTime");
            return (Criteria) this;
        }

        public Criteria andReqAvailableStartTimeNotBetween(Date value1, Date value2) {
            addCriterion("REQ_AVAILABLE_START_TIME not between", value1, value2, "reqAvailableStartTime");
            return (Criteria) this;
        }

        public Criteria andReqAvailableEndTimeIsNull() {
            addCriterion("REQ_AVAILABLE_END_TIME is null");
            return (Criteria) this;
        }

        public Criteria andReqAvailableEndTimeIsNotNull() {
            addCriterion("REQ_AVAILABLE_END_TIME is not null");
            return (Criteria) this;
        }

        public Criteria andReqAvailableEndTimeEqualTo(Date value) {
            addCriterion("REQ_AVAILABLE_END_TIME =", value, "reqAvailableEndTime");
            return (Criteria) this;
        }

        public Criteria andReqAvailableEndTimeNotEqualTo(Date value) {
            addCriterion("REQ_AVAILABLE_END_TIME <>", value, "reqAvailableEndTime");
            return (Criteria) this;
        }

        public Criteria andReqAvailableEndTimeGreaterThan(Date value) {
            addCriterion("REQ_AVAILABLE_END_TIME >", value, "reqAvailableEndTime");
            return (Criteria) this;
        }

        public Criteria andReqAvailableEndTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("REQ_AVAILABLE_END_TIME >=", value, "reqAvailableEndTime");
            return (Criteria) this;
        }

        public Criteria andReqAvailableEndTimeLessThan(Date value) {
            addCriterion("REQ_AVAILABLE_END_TIME <", value, "reqAvailableEndTime");
            return (Criteria) this;
        }

        public Criteria andReqAvailableEndTimeLessThanOrEqualTo(Date value) {
            addCriterion("REQ_AVAILABLE_END_TIME <=", value, "reqAvailableEndTime");
            return (Criteria) this;
        }

        public Criteria andReqAvailableEndTimeIn(List<Date> values) {
            addCriterion("REQ_AVAILABLE_END_TIME in", values, "reqAvailableEndTime");
            return (Criteria) this;
        }

        public Criteria andReqAvailableEndTimeNotIn(List<Date> values) {
            addCriterion("REQ_AVAILABLE_END_TIME not in", values, "reqAvailableEndTime");
            return (Criteria) this;
        }

        public Criteria andReqAvailableEndTimeBetween(Date value1, Date value2) {
            addCriterion("REQ_AVAILABLE_END_TIME between", value1, value2, "reqAvailableEndTime");
            return (Criteria) this;
        }

        public Criteria andReqAvailableEndTimeNotBetween(Date value1, Date value2) {
            addCriterion("REQ_AVAILABLE_END_TIME not between", value1, value2, "reqAvailableEndTime");
            return (Criteria) this;
        }

        public Criteria andReqRreDurationTimeIsNull() {
            addCriterion("REQ_RRE_DURATION_TIME is null");
            return (Criteria) this;
        }

        public Criteria andReqRreDurationTimeIsNotNull() {
            addCriterion("REQ_RRE_DURATION_TIME is not null");
            return (Criteria) this;
        }

        public Criteria andReqRreDurationTimeEqualTo(Integer value) {
            addCriterion("REQ_RRE_DURATION_TIME =", value, "reqRreDurationTime");
            return (Criteria) this;
        }

        public Criteria andReqRreDurationTimeNotEqualTo(Integer value) {
            addCriterion("REQ_RRE_DURATION_TIME <>", value, "reqRreDurationTime");
            return (Criteria) this;
        }

        public Criteria andReqRreDurationTimeGreaterThan(Integer value) {
            addCriterion("REQ_RRE_DURATION_TIME >", value, "reqRreDurationTime");
            return (Criteria) this;
        }

        public Criteria andReqRreDurationTimeGreaterThanOrEqualTo(Integer value) {
            addCriterion("REQ_RRE_DURATION_TIME >=", value, "reqRreDurationTime");
            return (Criteria) this;
        }

        public Criteria andReqRreDurationTimeLessThan(Integer value) {
            addCriterion("REQ_RRE_DURATION_TIME <", value, "reqRreDurationTime");
            return (Criteria) this;
        }

        public Criteria andReqRreDurationTimeLessThanOrEqualTo(Integer value) {
            addCriterion("REQ_RRE_DURATION_TIME <=", value, "reqRreDurationTime");
            return (Criteria) this;
        }

        public Criteria andReqRreDurationTimeIn(List<Integer> values) {
            addCriterion("REQ_RRE_DURATION_TIME in", values, "reqRreDurationTime");
            return (Criteria) this;
        }

        public Criteria andReqRreDurationTimeNotIn(List<Integer> values) {
            addCriterion("REQ_RRE_DURATION_TIME not in", values, "reqRreDurationTime");
            return (Criteria) this;
        }

        public Criteria andReqRreDurationTimeBetween(Integer value1, Integer value2) {
            addCriterion("REQ_RRE_DURATION_TIME between", value1, value2, "reqRreDurationTime");
            return (Criteria) this;
        }

        public Criteria andReqRreDurationTimeNotBetween(Integer value1, Integer value2) {
            addCriterion("REQ_RRE_DURATION_TIME not between", value1, value2, "reqRreDurationTime");
            return (Criteria) this;
        }

        public Criteria andReqPreCunsumeCurrencyIsNull() {
            addCriterion("REQ_PRE_CUNSUME_CURRENCY is null");
            return (Criteria) this;
        }

        public Criteria andReqPreCunsumeCurrencyIsNotNull() {
            addCriterion("REQ_PRE_CUNSUME_CURRENCY is not null");
            return (Criteria) this;
        }

        public Criteria andReqPreCunsumeCurrencyEqualTo(Double value) {
            addCriterion("REQ_PRE_CUNSUME_CURRENCY =", value, "reqPreCunsumeCurrency");
            return (Criteria) this;
        }

        public Criteria andReqPreCunsumeCurrencyNotEqualTo(Double value) {
            addCriterion("REQ_PRE_CUNSUME_CURRENCY <>", value, "reqPreCunsumeCurrency");
            return (Criteria) this;
        }

        public Criteria andReqPreCunsumeCurrencyGreaterThan(Double value) {
            addCriterion("REQ_PRE_CUNSUME_CURRENCY >", value, "reqPreCunsumeCurrency");
            return (Criteria) this;
        }

        public Criteria andReqPreCunsumeCurrencyGreaterThanOrEqualTo(Double value) {
            addCriterion("REQ_PRE_CUNSUME_CURRENCY >=", value, "reqPreCunsumeCurrency");
            return (Criteria) this;
        }

        public Criteria andReqPreCunsumeCurrencyLessThan(Double value) {
            addCriterion("REQ_PRE_CUNSUME_CURRENCY <", value, "reqPreCunsumeCurrency");
            return (Criteria) this;
        }

        public Criteria andReqPreCunsumeCurrencyLessThanOrEqualTo(Double value) {
            addCriterion("REQ_PRE_CUNSUME_CURRENCY <=", value, "reqPreCunsumeCurrency");
            return (Criteria) this;
        }

        public Criteria andReqPreCunsumeCurrencyIn(List<Double> values) {
            addCriterion("REQ_PRE_CUNSUME_CURRENCY in", values, "reqPreCunsumeCurrency");
            return (Criteria) this;
        }

        public Criteria andReqPreCunsumeCurrencyNotIn(List<Double> values) {
            addCriterion("REQ_PRE_CUNSUME_CURRENCY not in", values, "reqPreCunsumeCurrency");
            return (Criteria) this;
        }

        public Criteria andReqPreCunsumeCurrencyBetween(Double value1, Double value2) {
            addCriterion("REQ_PRE_CUNSUME_CURRENCY between", value1, value2, "reqPreCunsumeCurrency");
            return (Criteria) this;
        }

        public Criteria andReqPreCunsumeCurrencyNotBetween(Double value1, Double value2) {
            addCriterion("REQ_PRE_CUNSUME_CURRENCY not between", value1, value2, "reqPreCunsumeCurrency");
            return (Criteria) this;
        }

        public Criteria andReqStartTimeIsNull() {
            addCriterion("REQ_START_TIME is null");
            return (Criteria) this;
        }

        public Criteria andReqStartTimeIsNotNull() {
            addCriterion("REQ_START_TIME is not null");
            return (Criteria) this;
        }

        public Criteria andReqStartTimeEqualTo(Date value) {
            addCriterion("REQ_START_TIME =", value, "reqStartTime");
            return (Criteria) this;
        }

        public Criteria andReqStartTimeNotEqualTo(Date value) {
            addCriterion("REQ_START_TIME <>", value, "reqStartTime");
            return (Criteria) this;
        }

        public Criteria andReqStartTimeGreaterThan(Date value) {
            addCriterion("REQ_START_TIME >", value, "reqStartTime");
            return (Criteria) this;
        }

        public Criteria andReqStartTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("REQ_START_TIME >=", value, "reqStartTime");
            return (Criteria) this;
        }

        public Criteria andReqStartTimeLessThan(Date value) {
            addCriterion("REQ_START_TIME <", value, "reqStartTime");
            return (Criteria) this;
        }

        public Criteria andReqStartTimeLessThanOrEqualTo(Date value) {
            addCriterion("REQ_START_TIME <=", value, "reqStartTime");
            return (Criteria) this;
        }

        public Criteria andReqStartTimeIn(List<Date> values) {
            addCriterion("REQ_START_TIME in", values, "reqStartTime");
            return (Criteria) this;
        }

        public Criteria andReqStartTimeNotIn(List<Date> values) {
            addCriterion("REQ_START_TIME not in", values, "reqStartTime");
            return (Criteria) this;
        }

        public Criteria andReqStartTimeBetween(Date value1, Date value2) {
            addCriterion("REQ_START_TIME between", value1, value2, "reqStartTime");
            return (Criteria) this;
        }

        public Criteria andReqStartTimeNotBetween(Date value1, Date value2) {
            addCriterion("REQ_START_TIME not between", value1, value2, "reqStartTime");
            return (Criteria) this;
        }

        public Criteria andReqEndTimeIsNull() {
            addCriterion("REQ_END_TIME is null");
            return (Criteria) this;
        }

        public Criteria andReqEndTimeIsNotNull() {
            addCriterion("REQ_END_TIME is not null");
            return (Criteria) this;
        }

        public Criteria andReqEndTimeEqualTo(Date value) {
            addCriterion("REQ_END_TIME =", value, "reqEndTime");
            return (Criteria) this;
        }

        public Criteria andReqEndTimeNotEqualTo(Date value) {
            addCriterion("REQ_END_TIME <>", value, "reqEndTime");
            return (Criteria) this;
        }

        public Criteria andReqEndTimeGreaterThan(Date value) {
            addCriterion("REQ_END_TIME >", value, "reqEndTime");
            return (Criteria) this;
        }

        public Criteria andReqEndTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("REQ_END_TIME >=", value, "reqEndTime");
            return (Criteria) this;
        }

        public Criteria andReqEndTimeLessThan(Date value) {
            addCriterion("REQ_END_TIME <", value, "reqEndTime");
            return (Criteria) this;
        }

        public Criteria andReqEndTimeLessThanOrEqualTo(Date value) {
            addCriterion("REQ_END_TIME <=", value, "reqEndTime");
            return (Criteria) this;
        }

        public Criteria andReqEndTimeIn(List<Date> values) {
            addCriterion("REQ_END_TIME in", values, "reqEndTime");
            return (Criteria) this;
        }

        public Criteria andReqEndTimeNotIn(List<Date> values) {
            addCriterion("REQ_END_TIME not in", values, "reqEndTime");
            return (Criteria) this;
        }

        public Criteria andReqEndTimeBetween(Date value1, Date value2) {
            addCriterion("REQ_END_TIME between", value1, value2, "reqEndTime");
            return (Criteria) this;
        }

        public Criteria andReqEndTimeNotBetween(Date value1, Date value2) {
            addCriterion("REQ_END_TIME not between", value1, value2, "reqEndTime");
            return (Criteria) this;
        }

        public Criteria andReqActualConsumeCurrencyIsNull() {
            addCriterion("REQ_ACTUAL_CONSUME_CURRENCY is null");
            return (Criteria) this;
        }

        public Criteria andReqActualConsumeCurrencyIsNotNull() {
            addCriterion("REQ_ACTUAL_CONSUME_CURRENCY is not null");
            return (Criteria) this;
        }

        public Criteria andReqActualConsumeCurrencyEqualTo(Double value) {
            addCriterion("REQ_ACTUAL_CONSUME_CURRENCY =", value, "reqActualConsumeCurrency");
            return (Criteria) this;
        }

        public Criteria andReqActualConsumeCurrencyNotEqualTo(Double value) {
            addCriterion("REQ_ACTUAL_CONSUME_CURRENCY <>", value, "reqActualConsumeCurrency");
            return (Criteria) this;
        }

        public Criteria andReqActualConsumeCurrencyGreaterThan(Double value) {
            addCriterion("REQ_ACTUAL_CONSUME_CURRENCY >", value, "reqActualConsumeCurrency");
            return (Criteria) this;
        }

        public Criteria andReqActualConsumeCurrencyGreaterThanOrEqualTo(Double value) {
            addCriterion("REQ_ACTUAL_CONSUME_CURRENCY >=", value, "reqActualConsumeCurrency");
            return (Criteria) this;
        }

        public Criteria andReqActualConsumeCurrencyLessThan(Double value) {
            addCriterion("REQ_ACTUAL_CONSUME_CURRENCY <", value, "reqActualConsumeCurrency");
            return (Criteria) this;
        }

        public Criteria andReqActualConsumeCurrencyLessThanOrEqualTo(Double value) {
            addCriterion("REQ_ACTUAL_CONSUME_CURRENCY <=", value, "reqActualConsumeCurrency");
            return (Criteria) this;
        }

        public Criteria andReqActualConsumeCurrencyIn(List<Double> values) {
            addCriterion("REQ_ACTUAL_CONSUME_CURRENCY in", values, "reqActualConsumeCurrency");
            return (Criteria) this;
        }

        public Criteria andReqActualConsumeCurrencyNotIn(List<Double> values) {
            addCriterion("REQ_ACTUAL_CONSUME_CURRENCY not in", values, "reqActualConsumeCurrency");
            return (Criteria) this;
        }

        public Criteria andReqActualConsumeCurrencyBetween(Double value1, Double value2) {
            addCriterion("REQ_ACTUAL_CONSUME_CURRENCY between", value1, value2, "reqActualConsumeCurrency");
            return (Criteria) this;
        }

        public Criteria andReqActualConsumeCurrencyNotBetween(Double value1, Double value2) {
            addCriterion("REQ_ACTUAL_CONSUME_CURRENCY not between", value1, value2, "reqActualConsumeCurrency");
            return (Criteria) this;
        }

        public Criteria andReqTypeApproveStatusIsNull() {
            addCriterion("REQ_TYPE_APPROVE_STATUS is null");
            return (Criteria) this;
        }

        public Criteria andReqTypeApproveStatusIsNotNull() {
            addCriterion("REQ_TYPE_APPROVE_STATUS is not null");
            return (Criteria) this;
        }

        public Criteria andReqTypeApproveStatusEqualTo(String value) {
            addCriterion("REQ_TYPE_APPROVE_STATUS =", value, "reqTypeApproveStatus");
            return (Criteria) this;
        }

        public Criteria andReqTypeApproveStatusNotEqualTo(String value) {
            addCriterion("REQ_TYPE_APPROVE_STATUS <>", value, "reqTypeApproveStatus");
            return (Criteria) this;
        }

        public Criteria andReqTypeApproveStatusGreaterThan(String value) {
            addCriterion("REQ_TYPE_APPROVE_STATUS >", value, "reqTypeApproveStatus");
            return (Criteria) this;
        }

        public Criteria andReqTypeApproveStatusGreaterThanOrEqualTo(String value) {
            addCriterion("REQ_TYPE_APPROVE_STATUS >=", value, "reqTypeApproveStatus");
            return (Criteria) this;
        }

        public Criteria andReqTypeApproveStatusLessThan(String value) {
            addCriterion("REQ_TYPE_APPROVE_STATUS <", value, "reqTypeApproveStatus");
            return (Criteria) this;
        }

        public Criteria andReqTypeApproveStatusLessThanOrEqualTo(String value) {
            addCriterion("REQ_TYPE_APPROVE_STATUS <=", value, "reqTypeApproveStatus");
            return (Criteria) this;
        }

        public Criteria andReqTypeApproveStatusLike(String value) {
            addCriterion("REQ_TYPE_APPROVE_STATUS like", value, "reqTypeApproveStatus");
            return (Criteria) this;
        }

        public Criteria andReqTypeApproveStatusNotLike(String value) {
            addCriterion("REQ_TYPE_APPROVE_STATUS not like", value, "reqTypeApproveStatus");
            return (Criteria) this;
        }

        public Criteria andReqTypeApproveStatusIn(List<String> values) {
            addCriterion("REQ_TYPE_APPROVE_STATUS in", values, "reqTypeApproveStatus");
            return (Criteria) this;
        }

        public Criteria andReqTypeApproveStatusNotIn(List<String> values) {
            addCriterion("REQ_TYPE_APPROVE_STATUS not in", values, "reqTypeApproveStatus");
            return (Criteria) this;
        }

        public Criteria andReqTypeApproveStatusBetween(String value1, String value2) {
            addCriterion("REQ_TYPE_APPROVE_STATUS between", value1, value2, "reqTypeApproveStatus");
            return (Criteria) this;
        }

        public Criteria andReqTypeApproveStatusNotBetween(String value1, String value2) {
            addCriterion("REQ_TYPE_APPROVE_STATUS not between", value1, value2, "reqTypeApproveStatus");
            return (Criteria) this;
        }

        public Criteria andReqTargetsUserGuidIsNull() {
            addCriterion("REQ_TARGETS_USER_GUID is null");
            return (Criteria) this;
        }

        public Criteria andReqTargetsUserGuidIsNotNull() {
            addCriterion("REQ_TARGETS_USER_GUID is not null");
            return (Criteria) this;
        }

        public Criteria andReqTargetsUserGuidEqualTo(String value) {
            addCriterion("REQ_TARGETS_USER_GUID =", value, "reqTargetsUserGuid");
            return (Criteria) this;
        }

        public Criteria andReqTargetsUserGuidNotEqualTo(String value) {
            addCriterion("REQ_TARGETS_USER_GUID <>", value, "reqTargetsUserGuid");
            return (Criteria) this;
        }

        public Criteria andReqTargetsUserGuidGreaterThan(String value) {
            addCriterion("REQ_TARGETS_USER_GUID >", value, "reqTargetsUserGuid");
            return (Criteria) this;
        }

        public Criteria andReqTargetsUserGuidGreaterThanOrEqualTo(String value) {
            addCriterion("REQ_TARGETS_USER_GUID >=", value, "reqTargetsUserGuid");
            return (Criteria) this;
        }

        public Criteria andReqTargetsUserGuidLessThan(String value) {
            addCriterion("REQ_TARGETS_USER_GUID <", value, "reqTargetsUserGuid");
            return (Criteria) this;
        }

        public Criteria andReqTargetsUserGuidLessThanOrEqualTo(String value) {
            addCriterion("REQ_TARGETS_USER_GUID <=", value, "reqTargetsUserGuid");
            return (Criteria) this;
        }

        public Criteria andReqTargetsUserGuidLike(String value) {
            addCriterion("REQ_TARGETS_USER_GUID like", value, "reqTargetsUserGuid");
            return (Criteria) this;
        }

        public Criteria andReqTargetsUserGuidNotLike(String value) {
            addCriterion("REQ_TARGETS_USER_GUID not like", value, "reqTargetsUserGuid");
            return (Criteria) this;
        }

        public Criteria andReqTargetsUserGuidIn(List<String> values) {
            addCriterion("REQ_TARGETS_USER_GUID in", values, "reqTargetsUserGuid");
            return (Criteria) this;
        }

        public Criteria andReqTargetsUserGuidNotIn(List<String> values) {
            addCriterion("REQ_TARGETS_USER_GUID not in", values, "reqTargetsUserGuid");
            return (Criteria) this;
        }

        public Criteria andReqTargetsUserGuidBetween(String value1, String value2) {
            addCriterion("REQ_TARGETS_USER_GUID between", value1, value2, "reqTargetsUserGuid");
            return (Criteria) this;
        }

        public Criteria andReqTargetsUserGuidNotBetween(String value1, String value2) {
            addCriterion("REQ_TARGETS_USER_GUID not between", value1, value2, "reqTargetsUserGuid");
            return (Criteria) this;
        }

        public Criteria andReqActualDurationTimeIsNull() {
            addCriterion("REQ_ACTUAL_DURATION_TIME is null");
            return (Criteria) this;
        }

        public Criteria andReqActualDurationTimeIsNotNull() {
            addCriterion("REQ_ACTUAL_DURATION_TIME is not null");
            return (Criteria) this;
        }

        public Criteria andReqActualDurationTimeEqualTo(Integer value) {
            addCriterion("REQ_ACTUAL_DURATION_TIME =", value, "reqActualDurationTime");
            return (Criteria) this;
        }

        public Criteria andReqActualDurationTimeNotEqualTo(Integer value) {
            addCriterion("REQ_ACTUAL_DURATION_TIME <>", value, "reqActualDurationTime");
            return (Criteria) this;
        }

        public Criteria andReqActualDurationTimeGreaterThan(Integer value) {
            addCriterion("REQ_ACTUAL_DURATION_TIME >", value, "reqActualDurationTime");
            return (Criteria) this;
        }

        public Criteria andReqActualDurationTimeGreaterThanOrEqualTo(Integer value) {
            addCriterion("REQ_ACTUAL_DURATION_TIME >=", value, "reqActualDurationTime");
            return (Criteria) this;
        }

        public Criteria andReqActualDurationTimeLessThan(Integer value) {
            addCriterion("REQ_ACTUAL_DURATION_TIME <", value, "reqActualDurationTime");
            return (Criteria) this;
        }

        public Criteria andReqActualDurationTimeLessThanOrEqualTo(Integer value) {
            addCriterion("REQ_ACTUAL_DURATION_TIME <=", value, "reqActualDurationTime");
            return (Criteria) this;
        }

        public Criteria andReqActualDurationTimeIn(List<Integer> values) {
            addCriterion("REQ_ACTUAL_DURATION_TIME in", values, "reqActualDurationTime");
            return (Criteria) this;
        }

        public Criteria andReqActualDurationTimeNotIn(List<Integer> values) {
            addCriterion("REQ_ACTUAL_DURATION_TIME not in", values, "reqActualDurationTime");
            return (Criteria) this;
        }

        public Criteria andReqActualDurationTimeBetween(Integer value1, Integer value2) {
            addCriterion("REQ_ACTUAL_DURATION_TIME between", value1, value2, "reqActualDurationTime");
            return (Criteria) this;
        }

        public Criteria andReqActualDurationTimeNotBetween(Integer value1, Integer value2) {
            addCriterion("REQ_ACTUAL_DURATION_TIME not between", value1, value2, "reqActualDurationTime");
            return (Criteria) this;
        }

        public Criteria andReqPersonNumIsNull() {
            addCriterion("REQ_PERSON_NUM is null");
            return (Criteria) this;
        }

        public Criteria andReqPersonNumIsNotNull() {
            addCriterion("REQ_PERSON_NUM is not null");
            return (Criteria) this;
        }

        public Criteria andReqPersonNumEqualTo(Integer value) {
            addCriterion("REQ_PERSON_NUM =", value, "reqPersonNum");
            return (Criteria) this;
        }

        public Criteria andReqPersonNumNotEqualTo(Integer value) {
            addCriterion("REQ_PERSON_NUM <>", value, "reqPersonNum");
            return (Criteria) this;
        }

        public Criteria andReqPersonNumGreaterThan(Integer value) {
            addCriterion("REQ_PERSON_NUM >", value, "reqPersonNum");
            return (Criteria) this;
        }

        public Criteria andReqPersonNumGreaterThanOrEqualTo(Integer value) {
            addCriterion("REQ_PERSON_NUM >=", value, "reqPersonNum");
            return (Criteria) this;
        }

        public Criteria andReqPersonNumLessThan(Integer value) {
            addCriterion("REQ_PERSON_NUM <", value, "reqPersonNum");
            return (Criteria) this;
        }

        public Criteria andReqPersonNumLessThanOrEqualTo(Integer value) {
            addCriterion("REQ_PERSON_NUM <=", value, "reqPersonNum");
            return (Criteria) this;
        }

        public Criteria andReqPersonNumIn(List<Integer> values) {
            addCriterion("REQ_PERSON_NUM in", values, "reqPersonNum");
            return (Criteria) this;
        }

        public Criteria andReqPersonNumNotIn(List<Integer> values) {
            addCriterion("REQ_PERSON_NUM not in", values, "reqPersonNum");
            return (Criteria) this;
        }

        public Criteria andReqPersonNumBetween(Integer value1, Integer value2) {
            addCriterion("REQ_PERSON_NUM between", value1, value2, "reqPersonNum");
            return (Criteria) this;
        }

        public Criteria andReqPersonNumNotBetween(Integer value1, Integer value2) {
            addCriterion("REQ_PERSON_NUM not between", value1, value2, "reqPersonNum");
            return (Criteria) this;
        }

        public Criteria andReqTypeGuidUrgencyIsNull() {
            addCriterion("REQ_TYPE_GUID_URGENCY is null");
            return (Criteria) this;
        }

        public Criteria andReqTypeGuidUrgencyIsNotNull() {
            addCriterion("REQ_TYPE_GUID_URGENCY is not null");
            return (Criteria) this;
        }

        public Criteria andReqTypeGuidUrgencyEqualTo(String value) {
            addCriterion("REQ_TYPE_GUID_URGENCY =", value, "reqTypeGuidUrgency");
            return (Criteria) this;
        }

        public Criteria andReqTypeGuidUrgencyNotEqualTo(String value) {
            addCriterion("REQ_TYPE_GUID_URGENCY <>", value, "reqTypeGuidUrgency");
            return (Criteria) this;
        }

        public Criteria andReqTypeGuidUrgencyGreaterThan(String value) {
            addCriterion("REQ_TYPE_GUID_URGENCY >", value, "reqTypeGuidUrgency");
            return (Criteria) this;
        }

        public Criteria andReqTypeGuidUrgencyGreaterThanOrEqualTo(String value) {
            addCriterion("REQ_TYPE_GUID_URGENCY >=", value, "reqTypeGuidUrgency");
            return (Criteria) this;
        }

        public Criteria andReqTypeGuidUrgencyLessThan(String value) {
            addCriterion("REQ_TYPE_GUID_URGENCY <", value, "reqTypeGuidUrgency");
            return (Criteria) this;
        }

        public Criteria andReqTypeGuidUrgencyLessThanOrEqualTo(String value) {
            addCriterion("REQ_TYPE_GUID_URGENCY <=", value, "reqTypeGuidUrgency");
            return (Criteria) this;
        }

        public Criteria andReqTypeGuidUrgencyLike(String value) {
            addCriterion("REQ_TYPE_GUID_URGENCY like", value, "reqTypeGuidUrgency");
            return (Criteria) this;
        }

        public Criteria andReqTypeGuidUrgencyNotLike(String value) {
            addCriterion("REQ_TYPE_GUID_URGENCY not like", value, "reqTypeGuidUrgency");
            return (Criteria) this;
        }

        public Criteria andReqTypeGuidUrgencyIn(List<String> values) {
            addCriterion("REQ_TYPE_GUID_URGENCY in", values, "reqTypeGuidUrgency");
            return (Criteria) this;
        }

        public Criteria andReqTypeGuidUrgencyNotIn(List<String> values) {
            addCriterion("REQ_TYPE_GUID_URGENCY not in", values, "reqTypeGuidUrgency");
            return (Criteria) this;
        }

        public Criteria andReqTypeGuidUrgencyBetween(String value1, String value2) {
            addCriterion("REQ_TYPE_GUID_URGENCY between", value1, value2, "reqTypeGuidUrgency");
            return (Criteria) this;
        }

        public Criteria andReqTypeGuidUrgencyNotBetween(String value1, String value2) {
            addCriterion("REQ_TYPE_GUID_URGENCY not between", value1, value2, "reqTypeGuidUrgency");
            return (Criteria) this;
        }

        public Criteria andReqFromWeightGuidIsNull() {
            addCriterion("REQ_FROM_WEIGHT_GUID is null");
            return (Criteria) this;
        }

        public Criteria andReqFromWeightGuidIsNotNull() {
            addCriterion("REQ_FROM_WEIGHT_GUID is not null");
            return (Criteria) this;
        }

        public Criteria andReqFromWeightGuidEqualTo(String value) {
            addCriterion("REQ_FROM_WEIGHT_GUID =", value, "reqFromWeightGuid");
            return (Criteria) this;
        }

        public Criteria andReqFromWeightGuidNotEqualTo(String value) {
            addCriterion("REQ_FROM_WEIGHT_GUID <>", value, "reqFromWeightGuid");
            return (Criteria) this;
        }

        public Criteria andReqFromWeightGuidGreaterThan(String value) {
            addCriterion("REQ_FROM_WEIGHT_GUID >", value, "reqFromWeightGuid");
            return (Criteria) this;
        }

        public Criteria andReqFromWeightGuidGreaterThanOrEqualTo(String value) {
            addCriterion("REQ_FROM_WEIGHT_GUID >=", value, "reqFromWeightGuid");
            return (Criteria) this;
        }

        public Criteria andReqFromWeightGuidLessThan(String value) {
            addCriterion("REQ_FROM_WEIGHT_GUID <", value, "reqFromWeightGuid");
            return (Criteria) this;
        }

        public Criteria andReqFromWeightGuidLessThanOrEqualTo(String value) {
            addCriterion("REQ_FROM_WEIGHT_GUID <=", value, "reqFromWeightGuid");
            return (Criteria) this;
        }

        public Criteria andReqFromWeightGuidLike(String value) {
            addCriterion("REQ_FROM_WEIGHT_GUID like", value, "reqFromWeightGuid");
            return (Criteria) this;
        }

        public Criteria andReqFromWeightGuidNotLike(String value) {
            addCriterion("REQ_FROM_WEIGHT_GUID not like", value, "reqFromWeightGuid");
            return (Criteria) this;
        }

        public Criteria andReqFromWeightGuidIn(List<String> values) {
            addCriterion("REQ_FROM_WEIGHT_GUID in", values, "reqFromWeightGuid");
            return (Criteria) this;
        }

        public Criteria andReqFromWeightGuidNotIn(List<String> values) {
            addCriterion("REQ_FROM_WEIGHT_GUID not in", values, "reqFromWeightGuid");
            return (Criteria) this;
        }

        public Criteria andReqFromWeightGuidBetween(String value1, String value2) {
            addCriterion("REQ_FROM_WEIGHT_GUID between", value1, value2, "reqFromWeightGuid");
            return (Criteria) this;
        }

        public Criteria andReqFromWeightGuidNotBetween(String value1, String value2) {
            addCriterion("REQ_FROM_WEIGHT_GUID not between", value1, value2, "reqFromWeightGuid");
            return (Criteria) this;
        }

        public Criteria andReqTypeGuidProcessStatusIsNull() {
            addCriterion("REQ_TYPE_GUID_PROCESS_STATUS is null");
            return (Criteria) this;
        }

        public Criteria andReqTypeGuidProcessStatusIsNotNull() {
            addCriterion("REQ_TYPE_GUID_PROCESS_STATUS is not null");
            return (Criteria) this;
        }

        public Criteria andReqTypeGuidProcessStatusEqualTo(String value) {
            addCriterion("REQ_TYPE_GUID_PROCESS_STATUS =", value, "reqTypeGuidProcessStatus");
            return (Criteria) this;
        }

        public Criteria andReqTypeGuidProcessStatusNotEqualTo(String value) {
            addCriterion("REQ_TYPE_GUID_PROCESS_STATUS <>", value, "reqTypeGuidProcessStatus");
            return (Criteria) this;
        }

        public Criteria andReqTypeGuidProcessStatusGreaterThan(String value) {
            addCriterion("REQ_TYPE_GUID_PROCESS_STATUS >", value, "reqTypeGuidProcessStatus");
            return (Criteria) this;
        }

        public Criteria andReqTypeGuidProcessStatusGreaterThanOrEqualTo(String value) {
            addCriterion("REQ_TYPE_GUID_PROCESS_STATUS >=", value, "reqTypeGuidProcessStatus");
            return (Criteria) this;
        }

        public Criteria andReqTypeGuidProcessStatusLessThan(String value) {
            addCriterion("REQ_TYPE_GUID_PROCESS_STATUS <", value, "reqTypeGuidProcessStatus");
            return (Criteria) this;
        }

        public Criteria andReqTypeGuidProcessStatusLessThanOrEqualTo(String value) {
            addCriterion("REQ_TYPE_GUID_PROCESS_STATUS <=", value, "reqTypeGuidProcessStatus");
            return (Criteria) this;
        }

        public Criteria andReqTypeGuidProcessStatusLike(String value) {
            addCriterion("REQ_TYPE_GUID_PROCESS_STATUS like", value, "reqTypeGuidProcessStatus");
            return (Criteria) this;
        }

        public Criteria andReqTypeGuidProcessStatusNotLike(String value) {
            addCriterion("REQ_TYPE_GUID_PROCESS_STATUS not like", value, "reqTypeGuidProcessStatus");
            return (Criteria) this;
        }

        public Criteria andReqTypeGuidProcessStatusIn(List<String> values) {
            addCriterion("REQ_TYPE_GUID_PROCESS_STATUS in", values, "reqTypeGuidProcessStatus");
            return (Criteria) this;
        }

        public Criteria andReqTypeGuidProcessStatusNotIn(List<String> values) {
            addCriterion("REQ_TYPE_GUID_PROCESS_STATUS not in", values, "reqTypeGuidProcessStatus");
            return (Criteria) this;
        }

        public Criteria andReqTypeGuidProcessStatusBetween(String value1, String value2) {
            addCriterion("REQ_TYPE_GUID_PROCESS_STATUS between", value1, value2, "reqTypeGuidProcessStatus");
            return (Criteria) this;
        }

        public Criteria andReqTypeGuidProcessStatusNotBetween(String value1, String value2) {
            addCriterion("REQ_TYPE_GUID_PROCESS_STATUS not between", value1, value2, "reqTypeGuidProcessStatus");
            return (Criteria) this;
        }

        public Criteria andReqProcessUserGuidIsNull() {
            addCriterion("REQ_PROCESS_USER_GUID is null");
            return (Criteria) this;
        }

        public Criteria andReqProcessUserGuidIsNotNull() {
            addCriterion("REQ_PROCESS_USER_GUID is not null");
            return (Criteria) this;
        }

        public Criteria andReqProcessUserGuidEqualTo(String value) {
            addCriterion("REQ_PROCESS_USER_GUID =", value, "reqProcessUserGuid");
            return (Criteria) this;
        }

        public Criteria andReqProcessUserGuidNotEqualTo(String value) {
            addCriterion("REQ_PROCESS_USER_GUID <>", value, "reqProcessUserGuid");
            return (Criteria) this;
        }

        public Criteria andReqProcessUserGuidGreaterThan(String value) {
            addCriterion("REQ_PROCESS_USER_GUID >", value, "reqProcessUserGuid");
            return (Criteria) this;
        }

        public Criteria andReqProcessUserGuidGreaterThanOrEqualTo(String value) {
            addCriterion("REQ_PROCESS_USER_GUID >=", value, "reqProcessUserGuid");
            return (Criteria) this;
        }

        public Criteria andReqProcessUserGuidLessThan(String value) {
            addCriterion("REQ_PROCESS_USER_GUID <", value, "reqProcessUserGuid");
            return (Criteria) this;
        }

        public Criteria andReqProcessUserGuidLessThanOrEqualTo(String value) {
            addCriterion("REQ_PROCESS_USER_GUID <=", value, "reqProcessUserGuid");
            return (Criteria) this;
        }

        public Criteria andReqProcessUserGuidLike(String value) {
            addCriterion("REQ_PROCESS_USER_GUID like", value, "reqProcessUserGuid");
            return (Criteria) this;
        }

        public Criteria andReqProcessUserGuidNotLike(String value) {
            addCriterion("REQ_PROCESS_USER_GUID not like", value, "reqProcessUserGuid");
            return (Criteria) this;
        }

        public Criteria andReqProcessUserGuidIn(List<String> values) {
            addCriterion("REQ_PROCESS_USER_GUID in", values, "reqProcessUserGuid");
            return (Criteria) this;
        }

        public Criteria andReqProcessUserGuidNotIn(List<String> values) {
            addCriterion("REQ_PROCESS_USER_GUID not in", values, "reqProcessUserGuid");
            return (Criteria) this;
        }

        public Criteria andReqProcessUserGuidBetween(String value1, String value2) {
            addCriterion("REQ_PROCESS_USER_GUID between", value1, value2, "reqProcessUserGuid");
            return (Criteria) this;
        }

        public Criteria andReqProcessUserGuidNotBetween(String value1, String value2) {
            addCriterion("REQ_PROCESS_USER_GUID not between", value1, value2, "reqProcessUserGuid");
            return (Criteria) this;
        }

        public Criteria andReqTargetsUserAccountIsNull() {
            addCriterion("REQ_TARGETS_USER_ACCOUNT is null");
            return (Criteria) this;
        }

        public Criteria andReqTargetsUserAccountIsNotNull() {
            addCriterion("REQ_TARGETS_USER_ACCOUNT is not null");
            return (Criteria) this;
        }

        public Criteria andReqTargetsUserAccountEqualTo(String value) {
            addCriterion("REQ_TARGETS_USER_ACCOUNT =", value, "reqTargetsUserAccount");
            return (Criteria) this;
        }

        public Criteria andReqTargetsUserAccountNotEqualTo(String value) {
            addCriterion("REQ_TARGETS_USER_ACCOUNT <>", value, "reqTargetsUserAccount");
            return (Criteria) this;
        }

        public Criteria andReqTargetsUserAccountGreaterThan(String value) {
            addCriterion("REQ_TARGETS_USER_ACCOUNT >", value, "reqTargetsUserAccount");
            return (Criteria) this;
        }

        public Criteria andReqTargetsUserAccountGreaterThanOrEqualTo(String value) {
            addCriterion("REQ_TARGETS_USER_ACCOUNT >=", value, "reqTargetsUserAccount");
            return (Criteria) this;
        }

        public Criteria andReqTargetsUserAccountLessThan(String value) {
            addCriterion("REQ_TARGETS_USER_ACCOUNT <", value, "reqTargetsUserAccount");
            return (Criteria) this;
        }

        public Criteria andReqTargetsUserAccountLessThanOrEqualTo(String value) {
            addCriterion("REQ_TARGETS_USER_ACCOUNT <=", value, "reqTargetsUserAccount");
            return (Criteria) this;
        }

        public Criteria andReqTargetsUserAccountLike(String value) {
            addCriterion("REQ_TARGETS_USER_ACCOUNT like", value, "reqTargetsUserAccount");
            return (Criteria) this;
        }

        public Criteria andReqTargetsUserAccountNotLike(String value) {
            addCriterion("REQ_TARGETS_USER_ACCOUNT not like", value, "reqTargetsUserAccount");
            return (Criteria) this;
        }

        public Criteria andReqTargetsUserAccountIn(List<String> values) {
            addCriterion("REQ_TARGETS_USER_ACCOUNT in", values, "reqTargetsUserAccount");
            return (Criteria) this;
        }

        public Criteria andReqTargetsUserAccountNotIn(List<String> values) {
            addCriterion("REQ_TARGETS_USER_ACCOUNT not in", values, "reqTargetsUserAccount");
            return (Criteria) this;
        }

        public Criteria andReqTargetsUserAccountBetween(String value1, String value2) {
            addCriterion("REQ_TARGETS_USER_ACCOUNT between", value1, value2, "reqTargetsUserAccount");
            return (Criteria) this;
        }

        public Criteria andReqTargetsUserAccountNotBetween(String value1, String value2) {
            addCriterion("REQ_TARGETS_USER_ACCOUNT not between", value1, value2, "reqTargetsUserAccount");
            return (Criteria) this;
        }

        public Criteria andReqPhoneIsNull() {
            addCriterion("REQ_PHONE is null");
            return (Criteria) this;
        }

        public Criteria andReqPhoneIsNotNull() {
            addCriterion("REQ_PHONE is not null");
            return (Criteria) this;
        }

        public Criteria andReqPhoneEqualTo(String value) {
            addCriterion("REQ_PHONE =", value, "reqPhone");
            return (Criteria) this;
        }

        public Criteria andReqPhoneNotEqualTo(String value) {
            addCriterion("REQ_PHONE <>", value, "reqPhone");
            return (Criteria) this;
        }

        public Criteria andReqPhoneGreaterThan(String value) {
            addCriterion("REQ_PHONE >", value, "reqPhone");
            return (Criteria) this;
        }

        public Criteria andReqPhoneGreaterThanOrEqualTo(String value) {
            addCriterion("REQ_PHONE >=", value, "reqPhone");
            return (Criteria) this;
        }

        public Criteria andReqPhoneLessThan(String value) {
            addCriterion("REQ_PHONE <", value, "reqPhone");
            return (Criteria) this;
        }

        public Criteria andReqPhoneLessThanOrEqualTo(String value) {
            addCriterion("REQ_PHONE <=", value, "reqPhone");
            return (Criteria) this;
        }

        public Criteria andReqPhoneLike(String value) {
            addCriterion("REQ_PHONE like", value, "reqPhone");
            return (Criteria) this;
        }

        public Criteria andReqPhoneNotLike(String value) {
            addCriterion("REQ_PHONE not like", value, "reqPhone");
            return (Criteria) this;
        }

        public Criteria andReqPhoneIn(List<String> values) {
            addCriterion("REQ_PHONE in", values, "reqPhone");
            return (Criteria) this;
        }

        public Criteria andReqPhoneNotIn(List<String> values) {
            addCriterion("REQ_PHONE not in", values, "reqPhone");
            return (Criteria) this;
        }

        public Criteria andReqPhoneBetween(String value1, String value2) {
            addCriterion("REQ_PHONE between", value1, value2, "reqPhone");
            return (Criteria) this;
        }

        public Criteria andReqPhoneNotBetween(String value1, String value2) {
            addCriterion("REQ_PHONE not between", value1, value2, "reqPhone");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table dbo.REQEST
     *
     * @mbg.generated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table dbo.REQEST
     *
     * @mbg.generated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}