package com.timebank.domain;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class RespondExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table dbo.RESPOND
     *
     * @mbg.generated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table dbo.RESPOND
     *
     * @mbg.generated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table dbo.RESPOND
     *
     * @mbg.generated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dbo.RESPOND
     *
     * @mbg.generated
     */
    public RespondExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dbo.RESPOND
     *
     * @mbg.generated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dbo.RESPOND
     *
     * @mbg.generated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dbo.RESPOND
     *
     * @mbg.generated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dbo.RESPOND
     *
     * @mbg.generated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dbo.RESPOND
     *
     * @mbg.generated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dbo.RESPOND
     *
     * @mbg.generated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dbo.RESPOND
     *
     * @mbg.generated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dbo.RESPOND
     *
     * @mbg.generated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dbo.RESPOND
     *
     * @mbg.generated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dbo.RESPOND
     *
     * @mbg.generated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table dbo.RESPOND
     *
     * @mbg.generated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andResGuidIsNull() {
            addCriterion("RES_GUID is null");
            return (Criteria) this;
        }

        public Criteria andResGuidIsNotNull() {
            addCriterion("RES_GUID is not null");
            return (Criteria) this;
        }

        public Criteria andResGuidEqualTo(String value) {
            addCriterion("RES_GUID =", value, "resGuid");
            return (Criteria) this;
        }

        public Criteria andResGuidNotEqualTo(String value) {
            addCriterion("RES_GUID <>", value, "resGuid");
            return (Criteria) this;
        }

        public Criteria andResGuidGreaterThan(String value) {
            addCriterion("RES_GUID >", value, "resGuid");
            return (Criteria) this;
        }

        public Criteria andResGuidGreaterThanOrEqualTo(String value) {
            addCriterion("RES_GUID >=", value, "resGuid");
            return (Criteria) this;
        }

        public Criteria andResGuidLessThan(String value) {
            addCriterion("RES_GUID <", value, "resGuid");
            return (Criteria) this;
        }

        public Criteria andResGuidLessThanOrEqualTo(String value) {
            addCriterion("RES_GUID <=", value, "resGuid");
            return (Criteria) this;
        }

        public Criteria andResGuidLike(String value) {
            addCriterion("RES_GUID like", value, "resGuid");
            return (Criteria) this;
        }

        public Criteria andResGuidNotLike(String value) {
            addCriterion("RES_GUID not like", value, "resGuid");
            return (Criteria) this;
        }

        public Criteria andResGuidIn(List<String> values) {
            addCriterion("RES_GUID in", values, "resGuid");
            return (Criteria) this;
        }

        public Criteria andResGuidNotIn(List<String> values) {
            addCriterion("RES_GUID not in", values, "resGuid");
            return (Criteria) this;
        }

        public Criteria andResGuidBetween(String value1, String value2) {
            addCriterion("RES_GUID between", value1, value2, "resGuid");
            return (Criteria) this;
        }

        public Criteria andResGuidNotBetween(String value1, String value2) {
            addCriterion("RES_GUID not between", value1, value2, "resGuid");
            return (Criteria) this;
        }

        public Criteria andResReqGuidIsNull() {
            addCriterion("RES_REQ_GUID is null");
            return (Criteria) this;
        }

        public Criteria andResReqGuidIsNotNull() {
            addCriterion("RES_REQ_GUID is not null");
            return (Criteria) this;
        }

        public Criteria andResReqGuidEqualTo(String value) {
            addCriterion("RES_REQ_GUID =", value, "resReqGuid");
            return (Criteria) this;
        }

        public Criteria andResReqGuidNotEqualTo(String value) {
            addCriterion("RES_REQ_GUID <>", value, "resReqGuid");
            return (Criteria) this;
        }

        public Criteria andResReqGuidGreaterThan(String value) {
            addCriterion("RES_REQ_GUID >", value, "resReqGuid");
            return (Criteria) this;
        }

        public Criteria andResReqGuidGreaterThanOrEqualTo(String value) {
            addCriterion("RES_REQ_GUID >=", value, "resReqGuid");
            return (Criteria) this;
        }

        public Criteria andResReqGuidLessThan(String value) {
            addCriterion("RES_REQ_GUID <", value, "resReqGuid");
            return (Criteria) this;
        }

        public Criteria andResReqGuidLessThanOrEqualTo(String value) {
            addCriterion("RES_REQ_GUID <=", value, "resReqGuid");
            return (Criteria) this;
        }

        public Criteria andResReqGuidLike(String value) {
            addCriterion("RES_REQ_GUID like", value, "resReqGuid");
            return (Criteria) this;
        }

        public Criteria andResReqGuidNotLike(String value) {
            addCriterion("RES_REQ_GUID not like", value, "resReqGuid");
            return (Criteria) this;
        }

        public Criteria andResReqGuidIn(List<String> values) {
            addCriterion("RES_REQ_GUID in", values, "resReqGuid");
            return (Criteria) this;
        }

        public Criteria andResReqGuidNotIn(List<String> values) {
            addCriterion("RES_REQ_GUID not in", values, "resReqGuid");
            return (Criteria) this;
        }

        public Criteria andResReqGuidBetween(String value1, String value2) {
            addCriterion("RES_REQ_GUID between", value1, value2, "resReqGuid");
            return (Criteria) this;
        }

        public Criteria andResReqGuidNotBetween(String value1, String value2) {
            addCriterion("RES_REQ_GUID not between", value1, value2, "resReqGuid");
            return (Criteria) this;
        }

        public Criteria andResUserGuidIsNull() {
            addCriterion("RES_USER_GUID is null");
            return (Criteria) this;
        }

        public Criteria andResUserGuidIsNotNull() {
            addCriterion("RES_USER_GUID is not null");
            return (Criteria) this;
        }

        public Criteria andResUserGuidEqualTo(String value) {
            addCriterion("RES_USER_GUID =", value, "resUserGuid");
            return (Criteria) this;
        }

        public Criteria andResUserGuidNotEqualTo(String value) {
            addCriterion("RES_USER_GUID <>", value, "resUserGuid");
            return (Criteria) this;
        }

        public Criteria andResUserGuidGreaterThan(String value) {
            addCriterion("RES_USER_GUID >", value, "resUserGuid");
            return (Criteria) this;
        }

        public Criteria andResUserGuidGreaterThanOrEqualTo(String value) {
            addCriterion("RES_USER_GUID >=", value, "resUserGuid");
            return (Criteria) this;
        }

        public Criteria andResUserGuidLessThan(String value) {
            addCriterion("RES_USER_GUID <", value, "resUserGuid");
            return (Criteria) this;
        }

        public Criteria andResUserGuidLessThanOrEqualTo(String value) {
            addCriterion("RES_USER_GUID <=", value, "resUserGuid");
            return (Criteria) this;
        }

        public Criteria andResUserGuidLike(String value) {
            addCriterion("RES_USER_GUID like", value, "resUserGuid");
            return (Criteria) this;
        }

        public Criteria andResUserGuidNotLike(String value) {
            addCriterion("RES_USER_GUID not like", value, "resUserGuid");
            return (Criteria) this;
        }

        public Criteria andResUserGuidIn(List<String> values) {
            addCriterion("RES_USER_GUID in", values, "resUserGuid");
            return (Criteria) this;
        }

        public Criteria andResUserGuidNotIn(List<String> values) {
            addCriterion("RES_USER_GUID not in", values, "resUserGuid");
            return (Criteria) this;
        }

        public Criteria andResUserGuidBetween(String value1, String value2) {
            addCriterion("RES_USER_GUID between", value1, value2, "resUserGuid");
            return (Criteria) this;
        }

        public Criteria andResUserGuidNotBetween(String value1, String value2) {
            addCriterion("RES_USER_GUID not between", value1, value2, "resUserGuid");
            return (Criteria) this;
        }

        public Criteria andResAcceptTimeIsNull() {
            addCriterion("RES_ACCEPT_TIME is null");
            return (Criteria) this;
        }

        public Criteria andResAcceptTimeIsNotNull() {
            addCriterion("RES_ACCEPT_TIME is not null");
            return (Criteria) this;
        }

        public Criteria andResAcceptTimeEqualTo(Date value) {
            addCriterion("RES_ACCEPT_TIME =", value, "resAcceptTime");
            return (Criteria) this;
        }

        public Criteria andResAcceptTimeNotEqualTo(Date value) {
            addCriterion("RES_ACCEPT_TIME <>", value, "resAcceptTime");
            return (Criteria) this;
        }

        public Criteria andResAcceptTimeGreaterThan(Date value) {
            addCriterion("RES_ACCEPT_TIME >", value, "resAcceptTime");
            return (Criteria) this;
        }

        public Criteria andResAcceptTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("RES_ACCEPT_TIME >=", value, "resAcceptTime");
            return (Criteria) this;
        }

        public Criteria andResAcceptTimeLessThan(Date value) {
            addCriterion("RES_ACCEPT_TIME <", value, "resAcceptTime");
            return (Criteria) this;
        }

        public Criteria andResAcceptTimeLessThanOrEqualTo(Date value) {
            addCriterion("RES_ACCEPT_TIME <=", value, "resAcceptTime");
            return (Criteria) this;
        }

        public Criteria andResAcceptTimeIn(List<Date> values) {
            addCriterion("RES_ACCEPT_TIME in", values, "resAcceptTime");
            return (Criteria) this;
        }

        public Criteria andResAcceptTimeNotIn(List<Date> values) {
            addCriterion("RES_ACCEPT_TIME not in", values, "resAcceptTime");
            return (Criteria) this;
        }

        public Criteria andResAcceptTimeBetween(Date value1, Date value2) {
            addCriterion("RES_ACCEPT_TIME between", value1, value2, "resAcceptTime");
            return (Criteria) this;
        }

        public Criteria andResAcceptTimeNotBetween(Date value1, Date value2) {
            addCriterion("RES_ACCEPT_TIME not between", value1, value2, "resAcceptTime");
            return (Criteria) this;
        }

        public Criteria andResAcceptAddressIsNull() {
            addCriterion("RES_ACCEPT_ADDRESS is null");
            return (Criteria) this;
        }

        public Criteria andResAcceptAddressIsNotNull() {
            addCriterion("RES_ACCEPT_ADDRESS is not null");
            return (Criteria) this;
        }

        public Criteria andResAcceptAddressEqualTo(String value) {
            addCriterion("RES_ACCEPT_ADDRESS =", value, "resAcceptAddress");
            return (Criteria) this;
        }

        public Criteria andResAcceptAddressNotEqualTo(String value) {
            addCriterion("RES_ACCEPT_ADDRESS <>", value, "resAcceptAddress");
            return (Criteria) this;
        }

        public Criteria andResAcceptAddressGreaterThan(String value) {
            addCriterion("RES_ACCEPT_ADDRESS >", value, "resAcceptAddress");
            return (Criteria) this;
        }

        public Criteria andResAcceptAddressGreaterThanOrEqualTo(String value) {
            addCriterion("RES_ACCEPT_ADDRESS >=", value, "resAcceptAddress");
            return (Criteria) this;
        }

        public Criteria andResAcceptAddressLessThan(String value) {
            addCriterion("RES_ACCEPT_ADDRESS <", value, "resAcceptAddress");
            return (Criteria) this;
        }

        public Criteria andResAcceptAddressLessThanOrEqualTo(String value) {
            addCriterion("RES_ACCEPT_ADDRESS <=", value, "resAcceptAddress");
            return (Criteria) this;
        }

        public Criteria andResAcceptAddressLike(String value) {
            addCriterion("RES_ACCEPT_ADDRESS like", value, "resAcceptAddress");
            return (Criteria) this;
        }

        public Criteria andResAcceptAddressNotLike(String value) {
            addCriterion("RES_ACCEPT_ADDRESS not like", value, "resAcceptAddress");
            return (Criteria) this;
        }

        public Criteria andResAcceptAddressIn(List<String> values) {
            addCriterion("RES_ACCEPT_ADDRESS in", values, "resAcceptAddress");
            return (Criteria) this;
        }

        public Criteria andResAcceptAddressNotIn(List<String> values) {
            addCriterion("RES_ACCEPT_ADDRESS not in", values, "resAcceptAddress");
            return (Criteria) this;
        }

        public Criteria andResAcceptAddressBetween(String value1, String value2) {
            addCriterion("RES_ACCEPT_ADDRESS between", value1, value2, "resAcceptAddress");
            return (Criteria) this;
        }

        public Criteria andResAcceptAddressNotBetween(String value1, String value2) {
            addCriterion("RES_ACCEPT_ADDRESS not between", value1, value2, "resAcceptAddress");
            return (Criteria) this;
        }

        public Criteria andResServiceStartTimeIsNull() {
            addCriterion("RES_SERVICE_START_TIME is null");
            return (Criteria) this;
        }

        public Criteria andResServiceStartTimeIsNotNull() {
            addCriterion("RES_SERVICE_START_TIME is not null");
            return (Criteria) this;
        }

        public Criteria andResServiceStartTimeEqualTo(Date value) {
            addCriterion("RES_SERVICE_START_TIME =", value, "resServiceStartTime");
            return (Criteria) this;
        }

        public Criteria andResServiceStartTimeNotEqualTo(Date value) {
            addCriterion("RES_SERVICE_START_TIME <>", value, "resServiceStartTime");
            return (Criteria) this;
        }

        public Criteria andResServiceStartTimeGreaterThan(Date value) {
            addCriterion("RES_SERVICE_START_TIME >", value, "resServiceStartTime");
            return (Criteria) this;
        }

        public Criteria andResServiceStartTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("RES_SERVICE_START_TIME >=", value, "resServiceStartTime");
            return (Criteria) this;
        }

        public Criteria andResServiceStartTimeLessThan(Date value) {
            addCriterion("RES_SERVICE_START_TIME <", value, "resServiceStartTime");
            return (Criteria) this;
        }

        public Criteria andResServiceStartTimeLessThanOrEqualTo(Date value) {
            addCriterion("RES_SERVICE_START_TIME <=", value, "resServiceStartTime");
            return (Criteria) this;
        }

        public Criteria andResServiceStartTimeIn(List<Date> values) {
            addCriterion("RES_SERVICE_START_TIME in", values, "resServiceStartTime");
            return (Criteria) this;
        }

        public Criteria andResServiceStartTimeNotIn(List<Date> values) {
            addCriterion("RES_SERVICE_START_TIME not in", values, "resServiceStartTime");
            return (Criteria) this;
        }

        public Criteria andResServiceStartTimeBetween(Date value1, Date value2) {
            addCriterion("RES_SERVICE_START_TIME between", value1, value2, "resServiceStartTime");
            return (Criteria) this;
        }

        public Criteria andResServiceStartTimeNotBetween(Date value1, Date value2) {
            addCriterion("RES_SERVICE_START_TIME not between", value1, value2, "resServiceStartTime");
            return (Criteria) this;
        }

        public Criteria andResServiceEndTimeIsNull() {
            addCriterion("RES_SERVICE_END_TIME is null");
            return (Criteria) this;
        }

        public Criteria andResServiceEndTimeIsNotNull() {
            addCriterion("RES_SERVICE_END_TIME is not null");
            return (Criteria) this;
        }

        public Criteria andResServiceEndTimeEqualTo(Date value) {
            addCriterion("RES_SERVICE_END_TIME =", value, "resServiceEndTime");
            return (Criteria) this;
        }

        public Criteria andResServiceEndTimeNotEqualTo(Date value) {
            addCriterion("RES_SERVICE_END_TIME <>", value, "resServiceEndTime");
            return (Criteria) this;
        }

        public Criteria andResServiceEndTimeGreaterThan(Date value) {
            addCriterion("RES_SERVICE_END_TIME >", value, "resServiceEndTime");
            return (Criteria) this;
        }

        public Criteria andResServiceEndTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("RES_SERVICE_END_TIME >=", value, "resServiceEndTime");
            return (Criteria) this;
        }

        public Criteria andResServiceEndTimeLessThan(Date value) {
            addCriterion("RES_SERVICE_END_TIME <", value, "resServiceEndTime");
            return (Criteria) this;
        }

        public Criteria andResServiceEndTimeLessThanOrEqualTo(Date value) {
            addCriterion("RES_SERVICE_END_TIME <=", value, "resServiceEndTime");
            return (Criteria) this;
        }

        public Criteria andResServiceEndTimeIn(List<Date> values) {
            addCriterion("RES_SERVICE_END_TIME in", values, "resServiceEndTime");
            return (Criteria) this;
        }

        public Criteria andResServiceEndTimeNotIn(List<Date> values) {
            addCriterion("RES_SERVICE_END_TIME not in", values, "resServiceEndTime");
            return (Criteria) this;
        }

        public Criteria andResServiceEndTimeBetween(Date value1, Date value2) {
            addCriterion("RES_SERVICE_END_TIME between", value1, value2, "resServiceEndTime");
            return (Criteria) this;
        }

        public Criteria andResServiceEndTimeNotBetween(Date value1, Date value2) {
            addCriterion("RES_SERVICE_END_TIME not between", value1, value2, "resServiceEndTime");
            return (Criteria) this;
        }

        public Criteria andResTypeGuidProcessStatusIsNull() {
            addCriterion("RES_TYPE_GUID_PROCESS_STATUS is null");
            return (Criteria) this;
        }

        public Criteria andResTypeGuidProcessStatusIsNotNull() {
            addCriterion("RES_TYPE_GUID_PROCESS_STATUS is not null");
            return (Criteria) this;
        }

        public Criteria andResTypeGuidProcessStatusEqualTo(String value) {
            addCriterion("RES_TYPE_GUID_PROCESS_STATUS =", value, "resTypeGuidProcessStatus");
            return (Criteria) this;
        }

        public Criteria andResTypeGuidProcessStatusNotEqualTo(String value) {
            addCriterion("RES_TYPE_GUID_PROCESS_STATUS <>", value, "resTypeGuidProcessStatus");
            return (Criteria) this;
        }

        public Criteria andResTypeGuidProcessStatusGreaterThan(String value) {
            addCriterion("RES_TYPE_GUID_PROCESS_STATUS >", value, "resTypeGuidProcessStatus");
            return (Criteria) this;
        }

        public Criteria andResTypeGuidProcessStatusGreaterThanOrEqualTo(String value) {
            addCriterion("RES_TYPE_GUID_PROCESS_STATUS >=", value, "resTypeGuidProcessStatus");
            return (Criteria) this;
        }

        public Criteria andResTypeGuidProcessStatusLessThan(String value) {
            addCriterion("RES_TYPE_GUID_PROCESS_STATUS <", value, "resTypeGuidProcessStatus");
            return (Criteria) this;
        }

        public Criteria andResTypeGuidProcessStatusLessThanOrEqualTo(String value) {
            addCriterion("RES_TYPE_GUID_PROCESS_STATUS <=", value, "resTypeGuidProcessStatus");
            return (Criteria) this;
        }

        public Criteria andResTypeGuidProcessStatusLike(String value) {
            addCriterion("RES_TYPE_GUID_PROCESS_STATUS like", value, "resTypeGuidProcessStatus");
            return (Criteria) this;
        }

        public Criteria andResTypeGuidProcessStatusNotLike(String value) {
            addCriterion("RES_TYPE_GUID_PROCESS_STATUS not like", value, "resTypeGuidProcessStatus");
            return (Criteria) this;
        }

        public Criteria andResTypeGuidProcessStatusIn(List<String> values) {
            addCriterion("RES_TYPE_GUID_PROCESS_STATUS in", values, "resTypeGuidProcessStatus");
            return (Criteria) this;
        }

        public Criteria andResTypeGuidProcessStatusNotIn(List<String> values) {
            addCriterion("RES_TYPE_GUID_PROCESS_STATUS not in", values, "resTypeGuidProcessStatus");
            return (Criteria) this;
        }

        public Criteria andResTypeGuidProcessStatusBetween(String value1, String value2) {
            addCriterion("RES_TYPE_GUID_PROCESS_STATUS between", value1, value2, "resTypeGuidProcessStatus");
            return (Criteria) this;
        }

        public Criteria andResTypeGuidProcessStatusNotBetween(String value1, String value2) {
            addCriterion("RES_TYPE_GUID_PROCESS_STATUS not between", value1, value2, "resTypeGuidProcessStatus");
            return (Criteria) this;
        }

        public Criteria andResEvaluateIsNull() {
            addCriterion("RES_EVALUATE is null");
            return (Criteria) this;
        }

        public Criteria andResEvaluateIsNotNull() {
            addCriterion("RES_EVALUATE is not null");
            return (Criteria) this;
        }

        public Criteria andResEvaluateEqualTo(Byte value) {
            addCriterion("RES_EVALUATE =", value, "resEvaluate");
            return (Criteria) this;
        }

        public Criteria andResEvaluateNotEqualTo(Byte value) {
            addCriterion("RES_EVALUATE <>", value, "resEvaluate");
            return (Criteria) this;
        }

        public Criteria andResEvaluateGreaterThan(Byte value) {
            addCriterion("RES_EVALUATE >", value, "resEvaluate");
            return (Criteria) this;
        }

        public Criteria andResEvaluateGreaterThanOrEqualTo(Byte value) {
            addCriterion("RES_EVALUATE >=", value, "resEvaluate");
            return (Criteria) this;
        }

        public Criteria andResEvaluateLessThan(Byte value) {
            addCriterion("RES_EVALUATE <", value, "resEvaluate");
            return (Criteria) this;
        }

        public Criteria andResEvaluateLessThanOrEqualTo(Byte value) {
            addCriterion("RES_EVALUATE <=", value, "resEvaluate");
            return (Criteria) this;
        }

        public Criteria andResEvaluateIn(List<Byte> values) {
            addCriterion("RES_EVALUATE in", values, "resEvaluate");
            return (Criteria) this;
        }

        public Criteria andResEvaluateNotIn(List<Byte> values) {
            addCriterion("RES_EVALUATE not in", values, "resEvaluate");
            return (Criteria) this;
        }

        public Criteria andResEvaluateBetween(Byte value1, Byte value2) {
            addCriterion("RES_EVALUATE between", value1, value2, "resEvaluate");
            return (Criteria) this;
        }

        public Criteria andResEvaluateNotBetween(Byte value1, Byte value2) {
            addCriterion("RES_EVALUATE not between", value1, value2, "resEvaluate");
            return (Criteria) this;
        }

        public Criteria andResEarnCurrencyIsNull() {
            addCriterion("RES_EARN_CURRENCY is null");
            return (Criteria) this;
        }

        public Criteria andResEarnCurrencyIsNotNull() {
            addCriterion("RES_EARN_CURRENCY is not null");
            return (Criteria) this;
        }

        public Criteria andResEarnCurrencyEqualTo(Double value) {
            addCriterion("RES_EARN_CURRENCY =", value, "resEarnCurrency");
            return (Criteria) this;
        }

        public Criteria andResEarnCurrencyNotEqualTo(Double value) {
            addCriterion("RES_EARN_CURRENCY <>", value, "resEarnCurrency");
            return (Criteria) this;
        }

        public Criteria andResEarnCurrencyGreaterThan(Double value) {
            addCriterion("RES_EARN_CURRENCY >", value, "resEarnCurrency");
            return (Criteria) this;
        }

        public Criteria andResEarnCurrencyGreaterThanOrEqualTo(Double value) {
            addCriterion("RES_EARN_CURRENCY >=", value, "resEarnCurrency");
            return (Criteria) this;
        }

        public Criteria andResEarnCurrencyLessThan(Double value) {
            addCriterion("RES_EARN_CURRENCY <", value, "resEarnCurrency");
            return (Criteria) this;
        }

        public Criteria andResEarnCurrencyLessThanOrEqualTo(Double value) {
            addCriterion("RES_EARN_CURRENCY <=", value, "resEarnCurrency");
            return (Criteria) this;
        }

        public Criteria andResEarnCurrencyIn(List<Double> values) {
            addCriterion("RES_EARN_CURRENCY in", values, "resEarnCurrency");
            return (Criteria) this;
        }

        public Criteria andResEarnCurrencyNotIn(List<Double> values) {
            addCriterion("RES_EARN_CURRENCY not in", values, "resEarnCurrency");
            return (Criteria) this;
        }

        public Criteria andResEarnCurrencyBetween(Double value1, Double value2) {
            addCriterion("RES_EARN_CURRENCY between", value1, value2, "resEarnCurrency");
            return (Criteria) this;
        }

        public Criteria andResEarnCurrencyNotBetween(Double value1, Double value2) {
            addCriterion("RES_EARN_CURRENCY not between", value1, value2, "resEarnCurrency");
            return (Criteria) this;
        }

        public Criteria andResProcessUserGuidIsNull() {
            addCriterion("RES_PROCESS_USER_GUID is null");
            return (Criteria) this;
        }

        public Criteria andResProcessUserGuidIsNotNull() {
            addCriterion("RES_PROCESS_USER_GUID is not null");
            return (Criteria) this;
        }

        public Criteria andResProcessUserGuidEqualTo(String value) {
            addCriterion("RES_PROCESS_USER_GUID =", value, "resProcessUserGuid");
            return (Criteria) this;
        }

        public Criteria andResProcessUserGuidNotEqualTo(String value) {
            addCriterion("RES_PROCESS_USER_GUID <>", value, "resProcessUserGuid");
            return (Criteria) this;
        }

        public Criteria andResProcessUserGuidGreaterThan(String value) {
            addCriterion("RES_PROCESS_USER_GUID >", value, "resProcessUserGuid");
            return (Criteria) this;
        }

        public Criteria andResProcessUserGuidGreaterThanOrEqualTo(String value) {
            addCriterion("RES_PROCESS_USER_GUID >=", value, "resProcessUserGuid");
            return (Criteria) this;
        }

        public Criteria andResProcessUserGuidLessThan(String value) {
            addCriterion("RES_PROCESS_USER_GUID <", value, "resProcessUserGuid");
            return (Criteria) this;
        }

        public Criteria andResProcessUserGuidLessThanOrEqualTo(String value) {
            addCriterion("RES_PROCESS_USER_GUID <=", value, "resProcessUserGuid");
            return (Criteria) this;
        }

        public Criteria andResProcessUserGuidLike(String value) {
            addCriterion("RES_PROCESS_USER_GUID like", value, "resProcessUserGuid");
            return (Criteria) this;
        }

        public Criteria andResProcessUserGuidNotLike(String value) {
            addCriterion("RES_PROCESS_USER_GUID not like", value, "resProcessUserGuid");
            return (Criteria) this;
        }

        public Criteria andResProcessUserGuidIn(List<String> values) {
            addCriterion("RES_PROCESS_USER_GUID in", values, "resProcessUserGuid");
            return (Criteria) this;
        }

        public Criteria andResProcessUserGuidNotIn(List<String> values) {
            addCriterion("RES_PROCESS_USER_GUID not in", values, "resProcessUserGuid");
            return (Criteria) this;
        }

        public Criteria andResProcessUserGuidBetween(String value1, String value2) {
            addCriterion("RES_PROCESS_USER_GUID between", value1, value2, "resProcessUserGuid");
            return (Criteria) this;
        }

        public Criteria andResProcessUserGuidNotBetween(String value1, String value2) {
            addCriterion("RES_PROCESS_USER_GUID not between", value1, value2, "resProcessUserGuid");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table dbo.RESPOND
     *
     * @mbg.generated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table dbo.RESPOND
     *
     * @mbg.generated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}