package com.timebank.domain;

import org.springframework.format.annotation.DateTimeFormat;

import java.util.Date;

public class Respond {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.RESPOND.RES_GUID
     *
     * @mbg.generated
     */
    private String resGuid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.RESPOND.RES_REQ_GUID
     *
     * @mbg.generated
     */
    private String resReqGuid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.RESPOND.RES_USER_GUID
     *
     * @mbg.generated
     */
    private String resUserGuid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.RESPOND.RES_ACCEPT_TIME
     *
     * @mbg.generated
     */
    @DateTimeFormat(pattern = "yyyy-MM-dd HH:mm:ss")
    private Date resAcceptTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.RESPOND.RES_ACCEPT_ADDRESS
     *
     * @mbg.generated
     */
    private String resAcceptAddress;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.RESPOND.RES_SERVICE_START_TIME
     *
     * @mbg.generated
     */
    @DateTimeFormat(pattern = "yyyy-MM-dd HH:mm:ss")
    private Date resServiceStartTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.RESPOND.RES_SERVICE_END_TIME
     *
     * @mbg.generated
     */
    @DateTimeFormat(pattern = "yyyy-MM-dd HH:mm:ss")
    private Date resServiceEndTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.RESPOND.RES_TYPE_GUID_PROCESS_STATUS
     *
     * @mbg.generated
     */
    private String resTypeGuidProcessStatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.RESPOND.RES_EVALUATE
     *
     * @mbg.generated
     */
    private Integer resEvaluate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.RESPOND.RES_EARN_CURRENCY
     *
     * @mbg.generated
     */
    private Double resEarnCurrency;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.RESPOND.RES_PROCESS_USER_GUID
     *
     * @mbg.generated
     */
    private String resProcessUserGuid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.RESPOND.RES_REQ_ADDR
     *
     * @mbg.generated
     */
    private String resReqAddr;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.RESPOND.RES_REQ_TITLE
     *
     * @mbg.generated
     */
    private String resReqTitle;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.RESPOND.RES_EVALUATE_DES
     *
     * @mbg.generated
     */
    private String resEvaluateDes;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.RESPOND.RES_REQ_START_USER_ACCOUNT
     *
     * @mbg.generated
     */
    private String resReqStartUserAccount;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.RESPOND.RES_GUID
     *
     * @return the value of dbo.RESPOND.RES_GUID
     *
     * @mbg.generated
     */
    public String getResGuid() {
        return resGuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.RESPOND.RES_GUID
     *
     * @param resGuid the value for dbo.RESPOND.RES_GUID
     *
     * @mbg.generated
     */
    public void setResGuid(String resGuid) {
        this.resGuid = resGuid == null ? null : resGuid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.RESPOND.RES_REQ_GUID
     *
     * @return the value of dbo.RESPOND.RES_REQ_GUID
     *
     * @mbg.generated
     */
    public String getResReqGuid() {
        return resReqGuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.RESPOND.RES_REQ_GUID
     *
     * @param resReqGuid the value for dbo.RESPOND.RES_REQ_GUID
     *
     * @mbg.generated
     */
    public void setResReqGuid(String resReqGuid) {
        this.resReqGuid = resReqGuid == null ? null : resReqGuid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.RESPOND.RES_USER_GUID
     *
     * @return the value of dbo.RESPOND.RES_USER_GUID
     *
     * @mbg.generated
     */
    public String getResUserGuid() {
        return resUserGuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.RESPOND.RES_USER_GUID
     *
     * @param resUserGuid the value for dbo.RESPOND.RES_USER_GUID
     *
     * @mbg.generated
     */
    public void setResUserGuid(String resUserGuid) {
        this.resUserGuid = resUserGuid == null ? null : resUserGuid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.RESPOND.RES_ACCEPT_TIME
     *
     * @return the value of dbo.RESPOND.RES_ACCEPT_TIME
     *
     * @mbg.generated
     */
    @DateTimeFormat(pattern = "yyyy-MM-dd HH:mm:ss")
    public Date getResAcceptTime() {
        return resAcceptTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.RESPOND.RES_ACCEPT_TIME
     *
     * @param resAcceptTime the value for dbo.RESPOND.RES_ACCEPT_TIME
     *
     * @mbg.generated
     */
    public void setResAcceptTime(Date resAcceptTime) {
        this.resAcceptTime = resAcceptTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.RESPOND.RES_ACCEPT_ADDRESS
     *
     * @return the value of dbo.RESPOND.RES_ACCEPT_ADDRESS
     *
     * @mbg.generated
     */
    public String getResAcceptAddress() {
        return resAcceptAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.RESPOND.RES_ACCEPT_ADDRESS
     *
     * @param resAcceptAddress the value for dbo.RESPOND.RES_ACCEPT_ADDRESS
     *
     * @mbg.generated
     */
    public void setResAcceptAddress(String resAcceptAddress) {
        this.resAcceptAddress = resAcceptAddress == null ? null : resAcceptAddress.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.RESPOND.RES_SERVICE_START_TIME
     *
     * @return the value of dbo.RESPOND.RES_SERVICE_START_TIME
     *
     * @mbg.generated
     */
    @DateTimeFormat(pattern = "yyyy-MM-dd HH:mm:ss")
    public Date getResServiceStartTime() {
        return resServiceStartTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.RESPOND.RES_SERVICE_START_TIME
     *
     * @param resServiceStartTime the value for dbo.RESPOND.RES_SERVICE_START_TIME
     *
     * @mbg.generated
     */
    public void setResServiceStartTime(Date resServiceStartTime) {
        this.resServiceStartTime = resServiceStartTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.RESPOND.RES_SERVICE_END_TIME
     *
     * @return the value of dbo.RESPOND.RES_SERVICE_END_TIME
     *
     * @mbg.generated
     */
    @DateTimeFormat(pattern = "yyyy-MM-dd HH:mm:ss")
    public Date getResServiceEndTime() {
        return resServiceEndTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.RESPOND.RES_SERVICE_END_TIME
     *
     * @param resServiceEndTime the value for dbo.RESPOND.RES_SERVICE_END_TIME
     *
     * @mbg.generated
     */
    public void setResServiceEndTime(Date resServiceEndTime) {
        this.resServiceEndTime = resServiceEndTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.RESPOND.RES_TYPE_GUID_PROCESS_STATUS
     *
     * @return the value of dbo.RESPOND.RES_TYPE_GUID_PROCESS_STATUS
     *
     * @mbg.generated
     */
    public String getResTypeGuidProcessStatus() {
        return resTypeGuidProcessStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.RESPOND.RES_TYPE_GUID_PROCESS_STATUS
     *
     * @param resTypeGuidProcessStatus the value for dbo.RESPOND.RES_TYPE_GUID_PROCESS_STATUS
     *
     * @mbg.generated
     */
    public void setResTypeGuidProcessStatus(String resTypeGuidProcessStatus) {
        this.resTypeGuidProcessStatus = resTypeGuidProcessStatus == null ? null : resTypeGuidProcessStatus.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.RESPOND.RES_EVALUATE
     *
     * @return the value of dbo.RESPOND.RES_EVALUATE
     *
     * @mbg.generated
     */
    public Integer getResEvaluate() {
        return resEvaluate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.RESPOND.RES_EVALUATE
     *
     * @param resEvaluate the value for dbo.RESPOND.RES_EVALUATE
     *
     * @mbg.generated
     */
    public void setResEvaluate(Integer resEvaluate) {
        this.resEvaluate = resEvaluate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.RESPOND.RES_EARN_CURRENCY
     *
     * @return the value of dbo.RESPOND.RES_EARN_CURRENCY
     *
     * @mbg.generated
     */
    public Double getResEarnCurrency() {
        return resEarnCurrency;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.RESPOND.RES_EARN_CURRENCY
     *
     * @param resEarnCurrency the value for dbo.RESPOND.RES_EARN_CURRENCY
     *
     * @mbg.generated
     */
    public void setResEarnCurrency(Double resEarnCurrency) {
        this.resEarnCurrency = resEarnCurrency;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.RESPOND.RES_PROCESS_USER_GUID
     *
     * @return the value of dbo.RESPOND.RES_PROCESS_USER_GUID
     *
     * @mbg.generated
     */
    public String getResProcessUserGuid() {
        return resProcessUserGuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.RESPOND.RES_PROCESS_USER_GUID
     *
     * @param resProcessUserGuid the value for dbo.RESPOND.RES_PROCESS_USER_GUID
     *
     * @mbg.generated
     */
    public void setResProcessUserGuid(String resProcessUserGuid) {
        this.resProcessUserGuid = resProcessUserGuid == null ? null : resProcessUserGuid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.RESPOND.RES_REQ_ADDR
     *
     * @return the value of dbo.RESPOND.RES_REQ_ADDR
     *
     * @mbg.generated
     */
    public String getResReqAddr() {
        return resReqAddr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.RESPOND.RES_REQ_ADDR
     *
     * @param resReqAddr the value for dbo.RESPOND.RES_REQ_ADDR
     *
     * @mbg.generated
     */
    public void setResReqAddr(String resReqAddr) {
        this.resReqAddr = resReqAddr == null ? null : resReqAddr.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.RESPOND.RES_REQ_TITLE
     *
     * @return the value of dbo.RESPOND.RES_REQ_TITLE
     *
     * @mbg.generated
     */
    public String getResReqTitle() {
        return resReqTitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.RESPOND.RES_REQ_TITLE
     *
     * @param resReqTitle the value for dbo.RESPOND.RES_REQ_TITLE
     *
     * @mbg.generated
     */
    public void setResReqTitle(String resReqTitle) {
        this.resReqTitle = resReqTitle == null ? null : resReqTitle.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.RESPOND.RES_EVALUATE_DES
     *
     * @return the value of dbo.RESPOND.RES_EVALUATE_DES
     *
     * @mbg.generated
     */
    public String getResEvaluateDes() {
        return resEvaluateDes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.RESPOND.RES_EVALUATE_DES
     *
     * @param resEvaluateDes the value for dbo.RESPOND.RES_EVALUATE_DES
     *
     * @mbg.generated
     */
    public void setResEvaluateDes(String resEvaluateDes) {
        this.resEvaluateDes = resEvaluateDes == null ? null : resEvaluateDes.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.RESPOND.RES_REQ_START_USER_ACCOUNT
     *
     * @return the value of dbo.RESPOND.RES_REQ_START_USER_ACCOUNT
     *
     * @mbg.generated
     */
    public String getResReqStartUserAccount() {
        return resReqStartUserAccount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.RESPOND.RES_REQ_START_USER_ACCOUNT
     *
     * @param resReqStartUserAccount the value for dbo.RESPOND.RES_REQ_START_USER_ACCOUNT
     *
     * @mbg.generated
     */
    public void setResReqStartUserAccount(String resReqStartUserAccount) {
        this.resReqStartUserAccount = resReqStartUserAccount == null ? null : resReqStartUserAccount.trim();
    }
}