package com.timebank.domain;

public class Role {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.ROLE.ROLE_GUID
     *
     * @mbg.generated
     */
    private String roleGuid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.ROLE.ROLE_TITLE
     *
     * @mbg.generated
     */
    private String roleTitle;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.ROLE.ROLE_VALUE
     *
     * @mbg.generated
     */
    private Integer roleValue;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.ROLE.ROLE_GUID
     *
     * @return the value of dbo.ROLE.ROLE_GUID
     *
     * @mbg.generated
     */
    public String getRoleGuid() {
        return roleGuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.ROLE.ROLE_GUID
     *
     * @param roleGuid the value for dbo.ROLE.ROLE_GUID
     *
     * @mbg.generated
     */
    public void setRoleGuid(String roleGuid) {
        this.roleGuid = roleGuid == null ? null : roleGuid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.ROLE.ROLE_TITLE
     *
     * @return the value of dbo.ROLE.ROLE_TITLE
     *
     * @mbg.generated
     */
    public String getRoleTitle() {
        return roleTitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.ROLE.ROLE_TITLE
     *
     * @param roleTitle the value for dbo.ROLE.ROLE_TITLE
     *
     * @mbg.generated
     */
    public void setRoleTitle(String roleTitle) {
        this.roleTitle = roleTitle == null ? null : roleTitle.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.ROLE.ROLE_VALUE
     *
     * @return the value of dbo.ROLE.ROLE_VALUE
     *
     * @mbg.generated
     */
    public Integer getRoleValue() {
        return roleValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.ROLE.ROLE_VALUE
     *
     * @param roleValue the value for dbo.ROLE.ROLE_VALUE
     *
     * @mbg.generated
     */
    public void setRoleValue(Integer roleValue) {
        this.roleValue = roleValue;
    }
}