package com.timebank.domain;

import java.util.ArrayList;
import java.util.List;

public class UsersExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table dbo.USERS
     *
     * @mbg.generated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table dbo.USERS
     *
     * @mbg.generated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table dbo.USERS
     *
     * @mbg.generated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dbo.USERS
     *
     * @mbg.generated
     */
    public UsersExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dbo.USERS
     *
     * @mbg.generated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dbo.USERS
     *
     * @mbg.generated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dbo.USERS
     *
     * @mbg.generated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dbo.USERS
     *
     * @mbg.generated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dbo.USERS
     *
     * @mbg.generated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dbo.USERS
     *
     * @mbg.generated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dbo.USERS
     *
     * @mbg.generated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dbo.USERS
     *
     * @mbg.generated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dbo.USERS
     *
     * @mbg.generated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dbo.USERS
     *
     * @mbg.generated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table dbo.USERS
     *
     * @mbg.generated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andUserGuidIsNull() {
            addCriterion("USER_GUID is null");
            return (Criteria) this;
        }

        public Criteria andUserGuidIsNotNull() {
            addCriterion("USER_GUID is not null");
            return (Criteria) this;
        }

        public Criteria andUserGuidEqualTo(String value) {
            addCriterion("USER_GUID =", value, "userGuid");
            return (Criteria) this;
        }

        public Criteria andUserGuidNotEqualTo(String value) {
            addCriterion("USER_GUID <>", value, "userGuid");
            return (Criteria) this;
        }

        public Criteria andUserGuidGreaterThan(String value) {
            addCriterion("USER_GUID >", value, "userGuid");
            return (Criteria) this;
        }

        public Criteria andUserGuidGreaterThanOrEqualTo(String value) {
            addCriterion("USER_GUID >=", value, "userGuid");
            return (Criteria) this;
        }

        public Criteria andUserGuidLessThan(String value) {
            addCriterion("USER_GUID <", value, "userGuid");
            return (Criteria) this;
        }

        public Criteria andUserGuidLessThanOrEqualTo(String value) {
            addCriterion("USER_GUID <=", value, "userGuid");
            return (Criteria) this;
        }

        public Criteria andUserGuidLike(String value) {
            addCriterion("USER_GUID like", value, "userGuid");
            return (Criteria) this;
        }

        public Criteria andUserGuidNotLike(String value) {
            addCriterion("USER_GUID not like", value, "userGuid");
            return (Criteria) this;
        }

        public Criteria andUserGuidIn(List<String> values) {
            addCriterion("USER_GUID in", values, "userGuid");
            return (Criteria) this;
        }

        public Criteria andUserGuidNotIn(List<String> values) {
            addCriterion("USER_GUID not in", values, "userGuid");
            return (Criteria) this;
        }

        public Criteria andUserGuidBetween(String value1, String value2) {
            addCriterion("USER_GUID between", value1, value2, "userGuid");
            return (Criteria) this;
        }

        public Criteria andUserGuidNotBetween(String value1, String value2) {
            addCriterion("USER_GUID not between", value1, value2, "userGuid");
            return (Criteria) this;
        }

        public Criteria andUserNameIsNull() {
            addCriterion("USER_NAME is null");
            return (Criteria) this;
        }

        public Criteria andUserNameIsNotNull() {
            addCriterion("USER_NAME is not null");
            return (Criteria) this;
        }

        public Criteria andUserNameEqualTo(String value) {
            addCriterion("USER_NAME =", value, "userName");
            return (Criteria) this;
        }

        public Criteria andUserNameNotEqualTo(String value) {
            addCriterion("USER_NAME <>", value, "userName");
            return (Criteria) this;
        }

        public Criteria andUserNameGreaterThan(String value) {
            addCriterion("USER_NAME >", value, "userName");
            return (Criteria) this;
        }

        public Criteria andUserNameGreaterThanOrEqualTo(String value) {
            addCriterion("USER_NAME >=", value, "userName");
            return (Criteria) this;
        }

        public Criteria andUserNameLessThan(String value) {
            addCriterion("USER_NAME <", value, "userName");
            return (Criteria) this;
        }

        public Criteria andUserNameLessThanOrEqualTo(String value) {
            addCriterion("USER_NAME <=", value, "userName");
            return (Criteria) this;
        }

        public Criteria andUserNameLike(String value) {
            addCriterion("USER_NAME like", value, "userName");
            return (Criteria) this;
        }

        public Criteria andUserNameNotLike(String value) {
            addCriterion("USER_NAME not like", value, "userName");
            return (Criteria) this;
        }

        public Criteria andUserNameIn(List<String> values) {
            addCriterion("USER_NAME in", values, "userName");
            return (Criteria) this;
        }

        public Criteria andUserNameNotIn(List<String> values) {
            addCriterion("USER_NAME not in", values, "userName");
            return (Criteria) this;
        }

        public Criteria andUserNameBetween(String value1, String value2) {
            addCriterion("USER_NAME between", value1, value2, "userName");
            return (Criteria) this;
        }

        public Criteria andUserNameNotBetween(String value1, String value2) {
            addCriterion("USER_NAME not between", value1, value2, "userName");
            return (Criteria) this;
        }

        public Criteria andUserAccountIsNull() {
            addCriterion("USER_ACCOUNT is null");
            return (Criteria) this;
        }

        public Criteria andUserAccountIsNotNull() {
            addCriterion("USER_ACCOUNT is not null");
            return (Criteria) this;
        }

        public Criteria andUserAccountEqualTo(String value) {
            addCriterion("USER_ACCOUNT =", value, "userAccount");
            return (Criteria) this;
        }

        public Criteria andUserAccountNotEqualTo(String value) {
            addCriterion("USER_ACCOUNT <>", value, "userAccount");
            return (Criteria) this;
        }

        public Criteria andUserAccountGreaterThan(String value) {
            addCriterion("USER_ACCOUNT >", value, "userAccount");
            return (Criteria) this;
        }

        public Criteria andUserAccountGreaterThanOrEqualTo(String value) {
            addCriterion("USER_ACCOUNT >=", value, "userAccount");
            return (Criteria) this;
        }

        public Criteria andUserAccountLessThan(String value) {
            addCriterion("USER_ACCOUNT <", value, "userAccount");
            return (Criteria) this;
        }

        public Criteria andUserAccountLessThanOrEqualTo(String value) {
            addCriterion("USER_ACCOUNT <=", value, "userAccount");
            return (Criteria) this;
        }

        public Criteria andUserAccountLike(String value) {
            addCriterion("USER_ACCOUNT like", value, "userAccount");
            return (Criteria) this;
        }

        public Criteria andUserAccountNotLike(String value) {
            addCriterion("USER_ACCOUNT not like", value, "userAccount");
            return (Criteria) this;
        }

        public Criteria andUserAccountIn(List<String> values) {
            addCriterion("USER_ACCOUNT in", values, "userAccount");
            return (Criteria) this;
        }

        public Criteria andUserAccountNotIn(List<String> values) {
            addCriterion("USER_ACCOUNT not in", values, "userAccount");
            return (Criteria) this;
        }

        public Criteria andUserAccountBetween(String value1, String value2) {
            addCriterion("USER_ACCOUNT between", value1, value2, "userAccount");
            return (Criteria) this;
        }

        public Criteria andUserAccountNotBetween(String value1, String value2) {
            addCriterion("USER_ACCOUNT not between", value1, value2, "userAccount");
            return (Criteria) this;
        }

        public Criteria andUserPasswordIsNull() {
            addCriterion("USER_PASSWORD is null");
            return (Criteria) this;
        }

        public Criteria andUserPasswordIsNotNull() {
            addCriterion("USER_PASSWORD is not null");
            return (Criteria) this;
        }

        public Criteria andUserPasswordEqualTo(String value) {
            addCriterion("USER_PASSWORD =", value, "userPassword");
            return (Criteria) this;
        }

        public Criteria andUserPasswordNotEqualTo(String value) {
            addCriterion("USER_PASSWORD <>", value, "userPassword");
            return (Criteria) this;
        }

        public Criteria andUserPasswordGreaterThan(String value) {
            addCriterion("USER_PASSWORD >", value, "userPassword");
            return (Criteria) this;
        }

        public Criteria andUserPasswordGreaterThanOrEqualTo(String value) {
            addCriterion("USER_PASSWORD >=", value, "userPassword");
            return (Criteria) this;
        }

        public Criteria andUserPasswordLessThan(String value) {
            addCriterion("USER_PASSWORD <", value, "userPassword");
            return (Criteria) this;
        }

        public Criteria andUserPasswordLessThanOrEqualTo(String value) {
            addCriterion("USER_PASSWORD <=", value, "userPassword");
            return (Criteria) this;
        }

        public Criteria andUserPasswordLike(String value) {
            addCriterion("USER_PASSWORD like", value, "userPassword");
            return (Criteria) this;
        }

        public Criteria andUserPasswordNotLike(String value) {
            addCriterion("USER_PASSWORD not like", value, "userPassword");
            return (Criteria) this;
        }

        public Criteria andUserPasswordIn(List<String> values) {
            addCriterion("USER_PASSWORD in", values, "userPassword");
            return (Criteria) this;
        }

        public Criteria andUserPasswordNotIn(List<String> values) {
            addCriterion("USER_PASSWORD not in", values, "userPassword");
            return (Criteria) this;
        }

        public Criteria andUserPasswordBetween(String value1, String value2) {
            addCriterion("USER_PASSWORD between", value1, value2, "userPassword");
            return (Criteria) this;
        }

        public Criteria andUserPasswordNotBetween(String value1, String value2) {
            addCriterion("USER_PASSWORD not between", value1, value2, "userPassword");
            return (Criteria) this;
        }

        public Criteria andUserFromRoleGuidIsNull() {
            addCriterion("USER_FROM_ROLE_GUID is null");
            return (Criteria) this;
        }

        public Criteria andUserFromRoleGuidIsNotNull() {
            addCriterion("USER_FROM_ROLE_GUID is not null");
            return (Criteria) this;
        }

        public Criteria andUserFromRoleGuidEqualTo(String value) {
            addCriterion("USER_FROM_ROLE_GUID =", value, "userFromRoleGuid");
            return (Criteria) this;
        }

        public Criteria andUserFromRoleGuidNotEqualTo(String value) {
            addCriterion("USER_FROM_ROLE_GUID <>", value, "userFromRoleGuid");
            return (Criteria) this;
        }

        public Criteria andUserFromRoleGuidGreaterThan(String value) {
            addCriterion("USER_FROM_ROLE_GUID >", value, "userFromRoleGuid");
            return (Criteria) this;
        }

        public Criteria andUserFromRoleGuidGreaterThanOrEqualTo(String value) {
            addCriterion("USER_FROM_ROLE_GUID >=", value, "userFromRoleGuid");
            return (Criteria) this;
        }

        public Criteria andUserFromRoleGuidLessThan(String value) {
            addCriterion("USER_FROM_ROLE_GUID <", value, "userFromRoleGuid");
            return (Criteria) this;
        }

        public Criteria andUserFromRoleGuidLessThanOrEqualTo(String value) {
            addCriterion("USER_FROM_ROLE_GUID <=", value, "userFromRoleGuid");
            return (Criteria) this;
        }

        public Criteria andUserFromRoleGuidLike(String value) {
            addCriterion("USER_FROM_ROLE_GUID like", value, "userFromRoleGuid");
            return (Criteria) this;
        }

        public Criteria andUserFromRoleGuidNotLike(String value) {
            addCriterion("USER_FROM_ROLE_GUID not like", value, "userFromRoleGuid");
            return (Criteria) this;
        }

        public Criteria andUserFromRoleGuidIn(List<String> values) {
            addCriterion("USER_FROM_ROLE_GUID in", values, "userFromRoleGuid");
            return (Criteria) this;
        }

        public Criteria andUserFromRoleGuidNotIn(List<String> values) {
            addCriterion("USER_FROM_ROLE_GUID not in", values, "userFromRoleGuid");
            return (Criteria) this;
        }

        public Criteria andUserFromRoleGuidBetween(String value1, String value2) {
            addCriterion("USER_FROM_ROLE_GUID between", value1, value2, "userFromRoleGuid");
            return (Criteria) this;
        }

        public Criteria andUserFromRoleGuidNotBetween(String value1, String value2) {
            addCriterion("USER_FROM_ROLE_GUID not between", value1, value2, "userFromRoleGuid");
            return (Criteria) this;
        }

        public Criteria andUserTypeGuidGenderIsNull() {
            addCriterion("USER_TYPE_GUID_GENDER is null");
            return (Criteria) this;
        }

        public Criteria andUserTypeGuidGenderIsNotNull() {
            addCriterion("USER_TYPE_GUID_GENDER is not null");
            return (Criteria) this;
        }

        public Criteria andUserTypeGuidGenderEqualTo(String value) {
            addCriterion("USER_TYPE_GUID_GENDER =", value, "userTypeGuidGender");
            return (Criteria) this;
        }

        public Criteria andUserTypeGuidGenderNotEqualTo(String value) {
            addCriterion("USER_TYPE_GUID_GENDER <>", value, "userTypeGuidGender");
            return (Criteria) this;
        }

        public Criteria andUserTypeGuidGenderGreaterThan(String value) {
            addCriterion("USER_TYPE_GUID_GENDER >", value, "userTypeGuidGender");
            return (Criteria) this;
        }

        public Criteria andUserTypeGuidGenderGreaterThanOrEqualTo(String value) {
            addCriterion("USER_TYPE_GUID_GENDER >=", value, "userTypeGuidGender");
            return (Criteria) this;
        }

        public Criteria andUserTypeGuidGenderLessThan(String value) {
            addCriterion("USER_TYPE_GUID_GENDER <", value, "userTypeGuidGender");
            return (Criteria) this;
        }

        public Criteria andUserTypeGuidGenderLessThanOrEqualTo(String value) {
            addCriterion("USER_TYPE_GUID_GENDER <=", value, "userTypeGuidGender");
            return (Criteria) this;
        }

        public Criteria andUserTypeGuidGenderLike(String value) {
            addCriterion("USER_TYPE_GUID_GENDER like", value, "userTypeGuidGender");
            return (Criteria) this;
        }

        public Criteria andUserTypeGuidGenderNotLike(String value) {
            addCriterion("USER_TYPE_GUID_GENDER not like", value, "userTypeGuidGender");
            return (Criteria) this;
        }

        public Criteria andUserTypeGuidGenderIn(List<String> values) {
            addCriterion("USER_TYPE_GUID_GENDER in", values, "userTypeGuidGender");
            return (Criteria) this;
        }

        public Criteria andUserTypeGuidGenderNotIn(List<String> values) {
            addCriterion("USER_TYPE_GUID_GENDER not in", values, "userTypeGuidGender");
            return (Criteria) this;
        }

        public Criteria andUserTypeGuidGenderBetween(String value1, String value2) {
            addCriterion("USER_TYPE_GUID_GENDER between", value1, value2, "userTypeGuidGender");
            return (Criteria) this;
        }

        public Criteria andUserTypeGuidGenderNotBetween(String value1, String value2) {
            addCriterion("USER_TYPE_GUID_GENDER not between", value1, value2, "userTypeGuidGender");
            return (Criteria) this;
        }

        public Criteria andUserTypeAccountStatusIsNull() {
            addCriterion("USER_TYPE_ACCOUNT_STATUS is null");
            return (Criteria) this;
        }

        public Criteria andUserTypeAccountStatusIsNotNull() {
            addCriterion("USER_TYPE_ACCOUNT_STATUS is not null");
            return (Criteria) this;
        }

        public Criteria andUserTypeAccountStatusEqualTo(String value) {
            addCriterion("USER_TYPE_ACCOUNT_STATUS =", value, "userTypeAccountStatus");
            return (Criteria) this;
        }

        public Criteria andUserTypeAccountStatusNotEqualTo(String value) {
            addCriterion("USER_TYPE_ACCOUNT_STATUS <>", value, "userTypeAccountStatus");
            return (Criteria) this;
        }

        public Criteria andUserTypeAccountStatusGreaterThan(String value) {
            addCriterion("USER_TYPE_ACCOUNT_STATUS >", value, "userTypeAccountStatus");
            return (Criteria) this;
        }

        public Criteria andUserTypeAccountStatusGreaterThanOrEqualTo(String value) {
            addCriterion("USER_TYPE_ACCOUNT_STATUS >=", value, "userTypeAccountStatus");
            return (Criteria) this;
        }

        public Criteria andUserTypeAccountStatusLessThan(String value) {
            addCriterion("USER_TYPE_ACCOUNT_STATUS <", value, "userTypeAccountStatus");
            return (Criteria) this;
        }

        public Criteria andUserTypeAccountStatusLessThanOrEqualTo(String value) {
            addCriterion("USER_TYPE_ACCOUNT_STATUS <=", value, "userTypeAccountStatus");
            return (Criteria) this;
        }

        public Criteria andUserTypeAccountStatusLike(String value) {
            addCriterion("USER_TYPE_ACCOUNT_STATUS like", value, "userTypeAccountStatus");
            return (Criteria) this;
        }

        public Criteria andUserTypeAccountStatusNotLike(String value) {
            addCriterion("USER_TYPE_ACCOUNT_STATUS not like", value, "userTypeAccountStatus");
            return (Criteria) this;
        }

        public Criteria andUserTypeAccountStatusIn(List<String> values) {
            addCriterion("USER_TYPE_ACCOUNT_STATUS in", values, "userTypeAccountStatus");
            return (Criteria) this;
        }

        public Criteria andUserTypeAccountStatusNotIn(List<String> values) {
            addCriterion("USER_TYPE_ACCOUNT_STATUS not in", values, "userTypeAccountStatus");
            return (Criteria) this;
        }

        public Criteria andUserTypeAccountStatusBetween(String value1, String value2) {
            addCriterion("USER_TYPE_ACCOUNT_STATUS between", value1, value2, "userTypeAccountStatus");
            return (Criteria) this;
        }

        public Criteria andUserTypeAccountStatusNotBetween(String value1, String value2) {
            addCriterion("USER_TYPE_ACCOUNT_STATUS not between", value1, value2, "userTypeAccountStatus");
            return (Criteria) this;
        }

        public Criteria andUserSaltIsNull() {
            addCriterion("USER_SALT is null");
            return (Criteria) this;
        }

        public Criteria andUserSaltIsNotNull() {
            addCriterion("USER_SALT is not null");
            return (Criteria) this;
        }

        public Criteria andUserSaltEqualTo(String value) {
            addCriterion("USER_SALT =", value, "userSalt");
            return (Criteria) this;
        }

        public Criteria andUserSaltNotEqualTo(String value) {
            addCriterion("USER_SALT <>", value, "userSalt");
            return (Criteria) this;
        }

        public Criteria andUserSaltGreaterThan(String value) {
            addCriterion("USER_SALT >", value, "userSalt");
            return (Criteria) this;
        }

        public Criteria andUserSaltGreaterThanOrEqualTo(String value) {
            addCriterion("USER_SALT >=", value, "userSalt");
            return (Criteria) this;
        }

        public Criteria andUserSaltLessThan(String value) {
            addCriterion("USER_SALT <", value, "userSalt");
            return (Criteria) this;
        }

        public Criteria andUserSaltLessThanOrEqualTo(String value) {
            addCriterion("USER_SALT <=", value, "userSalt");
            return (Criteria) this;
        }

        public Criteria andUserSaltLike(String value) {
            addCriterion("USER_SALT like", value, "userSalt");
            return (Criteria) this;
        }

        public Criteria andUserSaltNotLike(String value) {
            addCriterion("USER_SALT not like", value, "userSalt");
            return (Criteria) this;
        }

        public Criteria andUserSaltIn(List<String> values) {
            addCriterion("USER_SALT in", values, "userSalt");
            return (Criteria) this;
        }

        public Criteria andUserSaltNotIn(List<String> values) {
            addCriterion("USER_SALT not in", values, "userSalt");
            return (Criteria) this;
        }

        public Criteria andUserSaltBetween(String value1, String value2) {
            addCriterion("USER_SALT between", value1, value2, "userSalt");
            return (Criteria) this;
        }

        public Criteria andUserSaltNotBetween(String value1, String value2) {
            addCriterion("USER_SALT not between", value1, value2, "userSalt");
            return (Criteria) this;
        }

        public Criteria andUserOwnCurrencyIsNull() {
            addCriterion("USER_OWN_CURRENCY is null");
            return (Criteria) this;
        }

        public Criteria andUserOwnCurrencyIsNotNull() {
            addCriterion("USER_OWN_CURRENCY is not null");
            return (Criteria) this;
        }

        public Criteria andUserOwnCurrencyEqualTo(Double value) {
            addCriterion("USER_OWN_CURRENCY =", value, "userOwnCurrency");
            return (Criteria) this;
        }

        public Criteria andUserOwnCurrencyNotEqualTo(Double value) {
            addCriterion("USER_OWN_CURRENCY <>", value, "userOwnCurrency");
            return (Criteria) this;
        }

        public Criteria andUserOwnCurrencyGreaterThan(Double value) {
            addCriterion("USER_OWN_CURRENCY >", value, "userOwnCurrency");
            return (Criteria) this;
        }

        public Criteria andUserOwnCurrencyGreaterThanOrEqualTo(Double value) {
            addCriterion("USER_OWN_CURRENCY >=", value, "userOwnCurrency");
            return (Criteria) this;
        }

        public Criteria andUserOwnCurrencyLessThan(Double value) {
            addCriterion("USER_OWN_CURRENCY <", value, "userOwnCurrency");
            return (Criteria) this;
        }

        public Criteria andUserOwnCurrencyLessThanOrEqualTo(Double value) {
            addCriterion("USER_OWN_CURRENCY <=", value, "userOwnCurrency");
            return (Criteria) this;
        }

        public Criteria andUserOwnCurrencyIn(List<Double> values) {
            addCriterion("USER_OWN_CURRENCY in", values, "userOwnCurrency");
            return (Criteria) this;
        }

        public Criteria andUserOwnCurrencyNotIn(List<Double> values) {
            addCriterion("USER_OWN_CURRENCY not in", values, "userOwnCurrency");
            return (Criteria) this;
        }

        public Criteria andUserOwnCurrencyBetween(Double value1, Double value2) {
            addCriterion("USER_OWN_CURRENCY between", value1, value2, "userOwnCurrency");
            return (Criteria) this;
        }

        public Criteria andUserOwnCurrencyNotBetween(Double value1, Double value2) {
            addCriterion("USER_OWN_CURRENCY not between", value1, value2, "userOwnCurrency");
            return (Criteria) this;
        }

        public Criteria andUserPreConsumeCurrencyIsNull() {
            addCriterion("USER_PRE_CONSUME_CURRENCY is null");
            return (Criteria) this;
        }

        public Criteria andUserPreConsumeCurrencyIsNotNull() {
            addCriterion("USER_PRE_CONSUME_CURRENCY is not null");
            return (Criteria) this;
        }

        public Criteria andUserPreConsumeCurrencyEqualTo(Double value) {
            addCriterion("USER_PRE_CONSUME_CURRENCY =", value, "userPreConsumeCurrency");
            return (Criteria) this;
        }

        public Criteria andUserPreConsumeCurrencyNotEqualTo(Double value) {
            addCriterion("USER_PRE_CONSUME_CURRENCY <>", value, "userPreConsumeCurrency");
            return (Criteria) this;
        }

        public Criteria andUserPreConsumeCurrencyGreaterThan(Double value) {
            addCriterion("USER_PRE_CONSUME_CURRENCY >", value, "userPreConsumeCurrency");
            return (Criteria) this;
        }

        public Criteria andUserPreConsumeCurrencyGreaterThanOrEqualTo(Double value) {
            addCriterion("USER_PRE_CONSUME_CURRENCY >=", value, "userPreConsumeCurrency");
            return (Criteria) this;
        }

        public Criteria andUserPreConsumeCurrencyLessThan(Double value) {
            addCriterion("USER_PRE_CONSUME_CURRENCY <", value, "userPreConsumeCurrency");
            return (Criteria) this;
        }

        public Criteria andUserPreConsumeCurrencyLessThanOrEqualTo(Double value) {
            addCriterion("USER_PRE_CONSUME_CURRENCY <=", value, "userPreConsumeCurrency");
            return (Criteria) this;
        }

        public Criteria andUserPreConsumeCurrencyIn(List<Double> values) {
            addCriterion("USER_PRE_CONSUME_CURRENCY in", values, "userPreConsumeCurrency");
            return (Criteria) this;
        }

        public Criteria andUserPreConsumeCurrencyNotIn(List<Double> values) {
            addCriterion("USER_PRE_CONSUME_CURRENCY not in", values, "userPreConsumeCurrency");
            return (Criteria) this;
        }

        public Criteria andUserPreConsumeCurrencyBetween(Double value1, Double value2) {
            addCriterion("USER_PRE_CONSUME_CURRENCY between", value1, value2, "userPreConsumeCurrency");
            return (Criteria) this;
        }

        public Criteria andUserPreConsumeCurrencyNotBetween(Double value1, Double value2) {
            addCriterion("USER_PRE_CONSUME_CURRENCY not between", value1, value2, "userPreConsumeCurrency");
            return (Criteria) this;
        }

        public Criteria andUserAddressIsNull() {
            addCriterion("USER_ADDRESS is null");
            return (Criteria) this;
        }

        public Criteria andUserAddressIsNotNull() {
            addCriterion("USER_ADDRESS is not null");
            return (Criteria) this;
        }

        public Criteria andUserAddressEqualTo(String value) {
            addCriterion("USER_ADDRESS =", value, "userAddress");
            return (Criteria) this;
        }

        public Criteria andUserAddressNotEqualTo(String value) {
            addCriterion("USER_ADDRESS <>", value, "userAddress");
            return (Criteria) this;
        }

        public Criteria andUserAddressGreaterThan(String value) {
            addCriterion("USER_ADDRESS >", value, "userAddress");
            return (Criteria) this;
        }

        public Criteria andUserAddressGreaterThanOrEqualTo(String value) {
            addCriterion("USER_ADDRESS >=", value, "userAddress");
            return (Criteria) this;
        }

        public Criteria andUserAddressLessThan(String value) {
            addCriterion("USER_ADDRESS <", value, "userAddress");
            return (Criteria) this;
        }

        public Criteria andUserAddressLessThanOrEqualTo(String value) {
            addCriterion("USER_ADDRESS <=", value, "userAddress");
            return (Criteria) this;
        }

        public Criteria andUserAddressLike(String value) {
            addCriterion("USER_ADDRESS like", value, "userAddress");
            return (Criteria) this;
        }

        public Criteria andUserAddressNotLike(String value) {
            addCriterion("USER_ADDRESS not like", value, "userAddress");
            return (Criteria) this;
        }

        public Criteria andUserAddressIn(List<String> values) {
            addCriterion("USER_ADDRESS in", values, "userAddress");
            return (Criteria) this;
        }

        public Criteria andUserAddressNotIn(List<String> values) {
            addCriterion("USER_ADDRESS not in", values, "userAddress");
            return (Criteria) this;
        }

        public Criteria andUserAddressBetween(String value1, String value2) {
            addCriterion("USER_ADDRESS between", value1, value2, "userAddress");
            return (Criteria) this;
        }

        public Criteria andUserAddressNotBetween(String value1, String value2) {
            addCriterion("USER_ADDRESS not between", value1, value2, "userAddress");
            return (Criteria) this;
        }

        public Criteria andUserCoordinateIsNull() {
            addCriterion("USER_COORDINATE is null");
            return (Criteria) this;
        }

        public Criteria andUserCoordinateIsNotNull() {
            addCriterion("USER_COORDINATE is not null");
            return (Criteria) this;
        }

        public Criteria andUserCoordinateEqualTo(String value) {
            addCriterion("USER_COORDINATE =", value, "userCoordinate");
            return (Criteria) this;
        }

        public Criteria andUserCoordinateNotEqualTo(String value) {
            addCriterion("USER_COORDINATE <>", value, "userCoordinate");
            return (Criteria) this;
        }

        public Criteria andUserCoordinateGreaterThan(String value) {
            addCriterion("USER_COORDINATE >", value, "userCoordinate");
            return (Criteria) this;
        }

        public Criteria andUserCoordinateGreaterThanOrEqualTo(String value) {
            addCriterion("USER_COORDINATE >=", value, "userCoordinate");
            return (Criteria) this;
        }

        public Criteria andUserCoordinateLessThan(String value) {
            addCriterion("USER_COORDINATE <", value, "userCoordinate");
            return (Criteria) this;
        }

        public Criteria andUserCoordinateLessThanOrEqualTo(String value) {
            addCriterion("USER_COORDINATE <=", value, "userCoordinate");
            return (Criteria) this;
        }

        public Criteria andUserCoordinateLike(String value) {
            addCriterion("USER_COORDINATE like", value, "userCoordinate");
            return (Criteria) this;
        }

        public Criteria andUserCoordinateNotLike(String value) {
            addCriterion("USER_COORDINATE not like", value, "userCoordinate");
            return (Criteria) this;
        }

        public Criteria andUserCoordinateIn(List<String> values) {
            addCriterion("USER_COORDINATE in", values, "userCoordinate");
            return (Criteria) this;
        }

        public Criteria andUserCoordinateNotIn(List<String> values) {
            addCriterion("USER_COORDINATE not in", values, "userCoordinate");
            return (Criteria) this;
        }

        public Criteria andUserCoordinateBetween(String value1, String value2) {
            addCriterion("USER_COORDINATE between", value1, value2, "userCoordinate");
            return (Criteria) this;
        }

        public Criteria andUserCoordinateNotBetween(String value1, String value2) {
            addCriterion("USER_COORDINATE not between", value1, value2, "userCoordinate");
            return (Criteria) this;
        }

        public Criteria andUserCommGuidIsNull() {
            addCriterion("USER_COMM_GUID is null");
            return (Criteria) this;
        }

        public Criteria andUserCommGuidIsNotNull() {
            addCriterion("USER_COMM_GUID is not null");
            return (Criteria) this;
        }

        public Criteria andUserCommGuidEqualTo(String value) {
            addCriterion("USER_COMM_GUID =", value, "userCommGuid");
            return (Criteria) this;
        }

        public Criteria andUserCommGuidNotEqualTo(String value) {
            addCriterion("USER_COMM_GUID <>", value, "userCommGuid");
            return (Criteria) this;
        }

        public Criteria andUserCommGuidGreaterThan(String value) {
            addCriterion("USER_COMM_GUID >", value, "userCommGuid");
            return (Criteria) this;
        }

        public Criteria andUserCommGuidGreaterThanOrEqualTo(String value) {
            addCriterion("USER_COMM_GUID >=", value, "userCommGuid");
            return (Criteria) this;
        }

        public Criteria andUserCommGuidLessThan(String value) {
            addCriterion("USER_COMM_GUID <", value, "userCommGuid");
            return (Criteria) this;
        }

        public Criteria andUserCommGuidLessThanOrEqualTo(String value) {
            addCriterion("USER_COMM_GUID <=", value, "userCommGuid");
            return (Criteria) this;
        }

        public Criteria andUserCommGuidLike(String value) {
            addCriterion("USER_COMM_GUID like", value, "userCommGuid");
            return (Criteria) this;
        }

        public Criteria andUserCommGuidNotLike(String value) {
            addCriterion("USER_COMM_GUID not like", value, "userCommGuid");
            return (Criteria) this;
        }

        public Criteria andUserCommGuidIn(List<String> values) {
            addCriterion("USER_COMM_GUID in", values, "userCommGuid");
            return (Criteria) this;
        }

        public Criteria andUserCommGuidNotIn(List<String> values) {
            addCriterion("USER_COMM_GUID not in", values, "userCommGuid");
            return (Criteria) this;
        }

        public Criteria andUserCommGuidBetween(String value1, String value2) {
            addCriterion("USER_COMM_GUID between", value1, value2, "userCommGuid");
            return (Criteria) this;
        }

        public Criteria andUserCommGuidNotBetween(String value1, String value2) {
            addCriterion("USER_COMM_GUID not between", value1, value2, "userCommGuid");
            return (Criteria) this;
        }

        public Criteria andUserRoleIsNull() {
            addCriterion("USER_ROLE is null");
            return (Criteria) this;
        }

        public Criteria andUserRoleIsNotNull() {
            addCriterion("USER_ROLE is not null");
            return (Criteria) this;
        }

        public Criteria andUserRoleEqualTo(String value) {
            addCriterion("USER_ROLE =", value, "userRole");
            return (Criteria) this;
        }

        public Criteria andUserRoleNotEqualTo(String value) {
            addCriterion("USER_ROLE <>", value, "userRole");
            return (Criteria) this;
        }

        public Criteria andUserRoleGreaterThan(String value) {
            addCriterion("USER_ROLE >", value, "userRole");
            return (Criteria) this;
        }

        public Criteria andUserRoleGreaterThanOrEqualTo(String value) {
            addCriterion("USER_ROLE >=", value, "userRole");
            return (Criteria) this;
        }

        public Criteria andUserRoleLessThan(String value) {
            addCriterion("USER_ROLE <", value, "userRole");
            return (Criteria) this;
        }

        public Criteria andUserRoleLessThanOrEqualTo(String value) {
            addCriterion("USER_ROLE <=", value, "userRole");
            return (Criteria) this;
        }

        public Criteria andUserRoleLike(String value) {
            addCriterion("USER_ROLE like", value, "userRole");
            return (Criteria) this;
        }

        public Criteria andUserRoleNotLike(String value) {
            addCriterion("USER_ROLE not like", value, "userRole");
            return (Criteria) this;
        }

        public Criteria andUserRoleIn(List<String> values) {
            addCriterion("USER_ROLE in", values, "userRole");
            return (Criteria) this;
        }

        public Criteria andUserRoleNotIn(List<String> values) {
            addCriterion("USER_ROLE not in", values, "userRole");
            return (Criteria) this;
        }

        public Criteria andUserRoleBetween(String value1, String value2) {
            addCriterion("USER_ROLE between", value1, value2, "userRole");
            return (Criteria) this;
        }

        public Criteria andUserRoleNotBetween(String value1, String value2) {
            addCriterion("USER_ROLE not between", value1, value2, "userRole");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table dbo.USERS
     *
     * @mbg.generated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table dbo.USERS
     *
     * @mbg.generated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}