package com.timebank.domain;

import java.util.ArrayList;
import java.util.List;

public class WeightExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table dbo.WEIGHT
     *
     * @mbg.generated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table dbo.WEIGHT
     *
     * @mbg.generated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table dbo.WEIGHT
     *
     * @mbg.generated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dbo.WEIGHT
     *
     * @mbg.generated
     */
    public WeightExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dbo.WEIGHT
     *
     * @mbg.generated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dbo.WEIGHT
     *
     * @mbg.generated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dbo.WEIGHT
     *
     * @mbg.generated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dbo.WEIGHT
     *
     * @mbg.generated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dbo.WEIGHT
     *
     * @mbg.generated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dbo.WEIGHT
     *
     * @mbg.generated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dbo.WEIGHT
     *
     * @mbg.generated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dbo.WEIGHT
     *
     * @mbg.generated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dbo.WEIGHT
     *
     * @mbg.generated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dbo.WEIGHT
     *
     * @mbg.generated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table dbo.WEIGHT
     *
     * @mbg.generated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andWeightGuidIsNull() {
            addCriterion("WEIGHT_GUID is null");
            return (Criteria) this;
        }

        public Criteria andWeightGuidIsNotNull() {
            addCriterion("WEIGHT_GUID is not null");
            return (Criteria) this;
        }

        public Criteria andWeightGuidEqualTo(String value) {
            addCriterion("WEIGHT_GUID =", value, "weightGuid");
            return (Criteria) this;
        }

        public Criteria andWeightGuidNotEqualTo(String value) {
            addCriterion("WEIGHT_GUID <>", value, "weightGuid");
            return (Criteria) this;
        }

        public Criteria andWeightGuidGreaterThan(String value) {
            addCriterion("WEIGHT_GUID >", value, "weightGuid");
            return (Criteria) this;
        }

        public Criteria andWeightGuidGreaterThanOrEqualTo(String value) {
            addCriterion("WEIGHT_GUID >=", value, "weightGuid");
            return (Criteria) this;
        }

        public Criteria andWeightGuidLessThan(String value) {
            addCriterion("WEIGHT_GUID <", value, "weightGuid");
            return (Criteria) this;
        }

        public Criteria andWeightGuidLessThanOrEqualTo(String value) {
            addCriterion("WEIGHT_GUID <=", value, "weightGuid");
            return (Criteria) this;
        }

        public Criteria andWeightGuidLike(String value) {
            addCriterion("WEIGHT_GUID like", value, "weightGuid");
            return (Criteria) this;
        }

        public Criteria andWeightGuidNotLike(String value) {
            addCriterion("WEIGHT_GUID not like", value, "weightGuid");
            return (Criteria) this;
        }

        public Criteria andWeightGuidIn(List<String> values) {
            addCriterion("WEIGHT_GUID in", values, "weightGuid");
            return (Criteria) this;
        }

        public Criteria andWeightGuidNotIn(List<String> values) {
            addCriterion("WEIGHT_GUID not in", values, "weightGuid");
            return (Criteria) this;
        }

        public Criteria andWeightGuidBetween(String value1, String value2) {
            addCriterion("WEIGHT_GUID between", value1, value2, "weightGuid");
            return (Criteria) this;
        }

        public Criteria andWeightGuidNotBetween(String value1, String value2) {
            addCriterion("WEIGHT_GUID not between", value1, value2, "weightGuid");
            return (Criteria) this;
        }

        public Criteria andWeightTitleIsNull() {
            addCriterion("WEIGHT_TITLE is null");
            return (Criteria) this;
        }

        public Criteria andWeightTitleIsNotNull() {
            addCriterion("WEIGHT_TITLE is not null");
            return (Criteria) this;
        }

        public Criteria andWeightTitleEqualTo(String value) {
            addCriterion("WEIGHT_TITLE =", value, "weightTitle");
            return (Criteria) this;
        }

        public Criteria andWeightTitleNotEqualTo(String value) {
            addCriterion("WEIGHT_TITLE <>", value, "weightTitle");
            return (Criteria) this;
        }

        public Criteria andWeightTitleGreaterThan(String value) {
            addCriterion("WEIGHT_TITLE >", value, "weightTitle");
            return (Criteria) this;
        }

        public Criteria andWeightTitleGreaterThanOrEqualTo(String value) {
            addCriterion("WEIGHT_TITLE >=", value, "weightTitle");
            return (Criteria) this;
        }

        public Criteria andWeightTitleLessThan(String value) {
            addCriterion("WEIGHT_TITLE <", value, "weightTitle");
            return (Criteria) this;
        }

        public Criteria andWeightTitleLessThanOrEqualTo(String value) {
            addCriterion("WEIGHT_TITLE <=", value, "weightTitle");
            return (Criteria) this;
        }

        public Criteria andWeightTitleLike(String value) {
            addCriterion("WEIGHT_TITLE like", value, "weightTitle");
            return (Criteria) this;
        }

        public Criteria andWeightTitleNotLike(String value) {
            addCriterion("WEIGHT_TITLE not like", value, "weightTitle");
            return (Criteria) this;
        }

        public Criteria andWeightTitleIn(List<String> values) {
            addCriterion("WEIGHT_TITLE in", values, "weightTitle");
            return (Criteria) this;
        }

        public Criteria andWeightTitleNotIn(List<String> values) {
            addCriterion("WEIGHT_TITLE not in", values, "weightTitle");
            return (Criteria) this;
        }

        public Criteria andWeightTitleBetween(String value1, String value2) {
            addCriterion("WEIGHT_TITLE between", value1, value2, "weightTitle");
            return (Criteria) this;
        }

        public Criteria andWeightTitleNotBetween(String value1, String value2) {
            addCriterion("WEIGHT_TITLE not between", value1, value2, "weightTitle");
            return (Criteria) this;
        }

        public Criteria andWeightValueIsNull() {
            addCriterion("WEIGHT_VALUE is null");
            return (Criteria) this;
        }

        public Criteria andWeightValueIsNotNull() {
            addCriterion("WEIGHT_VALUE is not null");
            return (Criteria) this;
        }

        public Criteria andWeightValueEqualTo(Double value) {
            addCriterion("WEIGHT_VALUE =", value, "weightValue");
            return (Criteria) this;
        }

        public Criteria andWeightValueNotEqualTo(Double value) {
            addCriterion("WEIGHT_VALUE <>", value, "weightValue");
            return (Criteria) this;
        }

        public Criteria andWeightValueGreaterThan(Double value) {
            addCriterion("WEIGHT_VALUE >", value, "weightValue");
            return (Criteria) this;
        }

        public Criteria andWeightValueGreaterThanOrEqualTo(Double value) {
            addCriterion("WEIGHT_VALUE >=", value, "weightValue");
            return (Criteria) this;
        }

        public Criteria andWeightValueLessThan(Double value) {
            addCriterion("WEIGHT_VALUE <", value, "weightValue");
            return (Criteria) this;
        }

        public Criteria andWeightValueLessThanOrEqualTo(Double value) {
            addCriterion("WEIGHT_VALUE <=", value, "weightValue");
            return (Criteria) this;
        }

        public Criteria andWeightValueIn(List<Double> values) {
            addCriterion("WEIGHT_VALUE in", values, "weightValue");
            return (Criteria) this;
        }

        public Criteria andWeightValueNotIn(List<Double> values) {
            addCriterion("WEIGHT_VALUE not in", values, "weightValue");
            return (Criteria) this;
        }

        public Criteria andWeightValueBetween(Double value1, Double value2) {
            addCriterion("WEIGHT_VALUE between", value1, value2, "weightValue");
            return (Criteria) this;
        }

        public Criteria andWeightValueNotBetween(Double value1, Double value2) {
            addCriterion("WEIGHT_VALUE not between", value1, value2, "weightValue");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table dbo.WEIGHT
     *
     * @mbg.generated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table dbo.WEIGHT
     *
     * @mbg.generated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}