package com.timebank.domain;

public class Weight {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.WEIGHT.WEIGHT_GUID
     *
     * @mbg.generated
     */
    private String weightGuid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.WEIGHT.WEIGHT_TITLE
     *
     * @mbg.generated
     */
    private String weightTitle;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.WEIGHT.WEIGHT_VALUE
     *
     * @mbg.generated
     */
    private Double weightValue;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.WEIGHT.WEIGHT_GUID
     *
     * @return the value of dbo.WEIGHT.WEIGHT_GUID
     *
     * @mbg.generated
     */
    public String getWeightGuid() {
        return weightGuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.WEIGHT.WEIGHT_GUID
     *
     * @param weightGuid the value for dbo.WEIGHT.WEIGHT_GUID
     *
     * @mbg.generated
     */
    public void setWeightGuid(String weightGuid) {
        this.weightGuid = weightGuid == null ? null : weightGuid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.WEIGHT.WEIGHT_TITLE
     *
     * @return the value of dbo.WEIGHT.WEIGHT_TITLE
     *
     * @mbg.generated
     */
    public String getWeightTitle() {
        return weightTitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.WEIGHT.WEIGHT_TITLE
     *
     * @param weightTitle the value for dbo.WEIGHT.WEIGHT_TITLE
     *
     * @mbg.generated
     */
    public void setWeightTitle(String weightTitle) {
        this.weightTitle = weightTitle == null ? null : weightTitle.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.WEIGHT.WEIGHT_VALUE
     *
     * @return the value of dbo.WEIGHT.WEIGHT_VALUE
     *
     * @mbg.generated
     */
    public Double getWeightValue() {
        return weightValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.WEIGHT.WEIGHT_VALUE
     *
     * @param weightValue the value for dbo.WEIGHT.WEIGHT_VALUE
     *
     * @mbg.generated
     */
    public void setWeightValue(Double weightValue) {
        this.weightValue = weightValue;
    }
}