package com.timebank.mapper;

import com.timebank.domain.Activity;
import com.timebank.domain.ActivityExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ActivityMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dbo.ACTIVITY
     *
     * @mbg.generated
     */
    long countByExample(ActivityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dbo.ACTIVITY
     *
     * @mbg.generated
     */
    int deleteByExample(ActivityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dbo.ACTIVITY
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String activityGuid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dbo.ACTIVITY
     *
     * @mbg.generated
     */
    int insert(Activity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dbo.ACTIVITY
     *
     * @mbg.generated
     */
    int insertSelective(Activity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dbo.ACTIVITY
     *
     * @mbg.generated
     */
    List<Activity> selectByExample(ActivityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dbo.ACTIVITY
     *
     * @mbg.generated
     */
    Activity selectByPrimaryKey(String activityGuid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dbo.ACTIVITY
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") Activity record, @Param("example") ActivityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dbo.ACTIVITY
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") Activity record, @Param("example") ActivityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dbo.ACTIVITY
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(Activity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dbo.ACTIVITY
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Activity record);
}