package com.timebank.mapper;

import com.timebank.domain.Community;
import com.timebank.domain.CommunityExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface CommunityMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dbo.COMMUNITY
     *
     * @mbg.generated
     */
    long countByExample(CommunityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dbo.COMMUNITY
     *
     * @mbg.generated
     */
    int deleteByExample(CommunityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dbo.COMMUNITY
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String commGuid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dbo.COMMUNITY
     *
     * @mbg.generated
     */
    int insert(Community record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dbo.COMMUNITY
     *
     * @mbg.generated
     */
    int insertSelective(Community record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dbo.COMMUNITY
     *
     * @mbg.generated
     */
    List<Community> selectByExample(CommunityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dbo.COMMUNITY
     *
     * @mbg.generated
     */
    Community selectByPrimaryKey(String commGuid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dbo.COMMUNITY
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") Community record, @Param("example") CommunityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dbo.COMMUNITY
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") Community record, @Param("example") CommunityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dbo.COMMUNITY
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(Community record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dbo.COMMUNITY
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Community record);
}