package com.timebank.mapper;

import com.timebank.domain.Complain;
import com.timebank.domain.ComplainExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ComplainMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dbo.COMPLAIN
     *
     * @mbg.generated
     */
    long countByExample(ComplainExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dbo.COMPLAIN
     *
     * @mbg.generated
     */
    int deleteByExample(ComplainExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dbo.COMPLAIN
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String compGuid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dbo.COMPLAIN
     *
     * @mbg.generated
     */
    int insert(Complain record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dbo.COMPLAIN
     *
     * @mbg.generated
     */
    int insertSelective(Complain record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dbo.COMPLAIN
     *
     * @mbg.generated
     */
    List<Complain> selectByExample(ComplainExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dbo.COMPLAIN
     *
     * @mbg.generated
     */
    Complain selectByPrimaryKey(String compGuid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dbo.COMPLAIN
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") Complain record, @Param("example") ComplainExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dbo.COMPLAIN
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") Complain record, @Param("example") ComplainExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dbo.COMPLAIN
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(Complain record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dbo.COMPLAIN
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Complain record);
}