package com.timebank.mapper;

import com.timebank.domain.Reqest;
import com.timebank.domain.ReqestExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ReqestMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dbo.REQEST
     *
     * @mbg.generated
     */
    long countByExample(ReqestExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dbo.REQEST
     *
     * @mbg.generated
     */
    int deleteByExample(ReqestExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dbo.REQEST
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String reqGuid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dbo.REQEST
     *
     * @mbg.generated
     */
    int insert(Reqest record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dbo.REQEST
     *
     * @mbg.generated
     */
    int insertSelective(Reqest record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dbo.REQEST
     *
     * @mbg.generated
     */
    List<Reqest> selectByExample(ReqestExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dbo.REQEST
     *
     * @mbg.generated
     */
    Reqest selectByPrimaryKey(String reqGuid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dbo.REQEST
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") Reqest record, @Param("example") ReqestExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dbo.REQEST
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") Reqest record, @Param("example") ReqestExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dbo.REQEST
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(Reqest record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dbo.REQEST
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Reqest record);
}