package com.timebank.mapper;

import com.timebank.domain.Respond;
import com.timebank.domain.RespondExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface RespondMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dbo.RESPOND
     *
     * @mbg.generated
     */
    long countByExample(RespondExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dbo.RESPOND
     *
     * @mbg.generated
     */
    int deleteByExample(RespondExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dbo.RESPOND
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String resGuid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dbo.RESPOND
     *
     * @mbg.generated
     */
    int insert(Respond record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dbo.RESPOND
     *
     * @mbg.generated
     */
    int insertSelective(Respond record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dbo.RESPOND
     *
     * @mbg.generated
     */
    List<Respond> selectByExample(RespondExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dbo.RESPOND
     *
     * @mbg.generated
     */
    Respond selectByPrimaryKey(String resGuid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dbo.RESPOND
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") Respond record, @Param("example") RespondExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dbo.RESPOND
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") Respond record, @Param("example") RespondExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dbo.RESPOND
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(Respond record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dbo.RESPOND
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Respond record);
}