package com.timebank.mapper;

import com.timebank.domain.Weight;
import com.timebank.domain.WeightExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface WeightMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dbo.WEIGHT
     *
     * @mbg.generated
     */
    long countByExample(WeightExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dbo.WEIGHT
     *
     * @mbg.generated
     */
    int deleteByExample(WeightExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dbo.WEIGHT
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String weightGuid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dbo.WEIGHT
     *
     * @mbg.generated
     */
    int insert(Weight record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dbo.WEIGHT
     *
     * @mbg.generated
     */
    int insertSelective(Weight record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dbo.WEIGHT
     *
     * @mbg.generated
     */
    List<Weight> selectByExample(WeightExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dbo.WEIGHT
     *
     * @mbg.generated
     */
    Weight selectByPrimaryKey(String weightGuid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dbo.WEIGHT
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") Weight record, @Param("example") WeightExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dbo.WEIGHT
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") Weight record, @Param("example") WeightExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dbo.WEIGHT
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(Weight record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dbo.WEIGHT
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Weight record);
}